### ISSUE TITLE
In-game chat got messed up after recent update

### ISSUE THREAD

**Issue by baranmod** [RocketMod/Rocket#1000]
Everything shown in the shot below. Got messed after recent update. All rocket servers facing same issue.
![update](https://user-images.githubusercontent.com/14231707/36325071-31c112c6-135f-11e8-8ae8-e953cfc68b08.png)

**Comment by Trojaner25** [comment]
Fixed: https://github.com/RocketMod/Rocket.Unturned/commit/62cd8e8d6c780b5b46bba4ee1dbddaf72224f064
