### ISSUE TITLE
Glitch/bug

### ISSUE THREAD

**Issue by Badminecraftdevelopment** [RocketMod/Rocket#1006]
if i enter a command it gets executed 4 times
 
i dont know how this happen but i enter /i in the conxole and it say
This Command cant be executed from the console 4 time
  or i use uconomy and enter /balance and it shows my balance 4 times
and if i enter /i 81 i get 4 mres

Operating System and Version: Windows 10 64-bit 

Unturned Version:  3.23.3.7

Rocketmod Version: 4.9.7.1

**Comment by persiafighter** [comment]
This is not a rocketmod code issue. This is caused by multiple installations of rocketmod existing in the modules folder, most likely caused by bad scripts of a host or bad install from the server owner. Delete all the installations of rocketmod except for 1 of them and it should work.

**Comment by Badminecraftdevelopment** [comment]
ok ill try it

2018-03-24 19:13 GMT+01:00 Vicente Pastor <notifications@github.com>:

**Comment by Badminecraftdevelopment** [comment]
still doesnt work

2018-03-24 20:57 GMT+01:00 Musik Live <jonnyniles64@gmail.com>:

**Comment by Badminecraftdevelopment** [comment]
oh i got it i just looked in the folder and just took the thing that sayed
soemthing with windows


2018-03-24 21:01 GMT+01:00 Musik Live <jonnyniles64@gmail.com>:

**Comment by Trojaner25** [comment]
Not a rocket bug.
You can join the discord for help
