### ISSUE TITLE
Random error during save

### ISSUE THREAD

**Issue by RainOfPain125** [RocketMod/Rocket#1015]
**What problem did you noticed?**
Rocket.Unturned >> Exception in FixedUpdate: System.NullReferenceException: Object reference not set to an instance of an object
  at SDG.Unturned.VehicleManager.save () [0x00000] in <filename unknown>:0
  at SDG.Unturned.SaveManager.save () [0x00000] in <filename unknown>:0
  at Rocket.Unturned.Utils.AutomaticSaveWatchdog.checkTimer () [0x00000] in <filename unknown>:0
**What is the expected result?**
No error / successful save
**What is the current result?**
Idk?
**How to reproduce the issue?**
No idea. Just hosting servers normally through SteamCMD

Operating System and Version:

Unturned Version:
3.23.8
Rocketmod Version:
Rocket v4.9.3.0 for Unturned v3.23.8.0

**Comment by Trojaner25** [comment]
This is an Unturned bug.

You can report ith ere:
https://github.com/SmartlyDressedGames/Unturned-3.x-Community
