### ISSUE TITLE
Rocket.API Documentation

### ISSUE THREAD

**Issue by Trojaner25** [RocketMod/Rocket#1023]
- [x] Chat
- [x] Commands
- [ ] Configuration
- [x] DI
- [x] Economy
- [x] Entities
- [x] Eventing 
- [x] I18N
- [x] Logging
- [x] Math
- [x] Permissions
- [x] Player
- [x] Plugins
- [x] Scheduler
- [x] Service Proxies
- [x] Misc

**Comment by fr34kyn01535** [comment]
I want to use http://www.mkdocs.org and https://github.com/squidfunk/mkdocs-material/
