### ISSUE TITLE
Rocketmod.Unturned linux install how to

### ISSUE THREAD

**Issue by Gladuin** [RocketMod/Rocket#1025]
Hello,

I followed the README file to install rocketmod but it turns out that that is horribly outdated. It still uses Debian 8 and because of that most of the packages aren't even available... I tried to do it anyways but then it always throws this error:
[test.log](https://github.com/RocketMod/Rocket/files/1893194/test.log)

I hope that you can help me quickly.
Thanks

**Comment by Trojaner25** [comment]
The error you face in the log has nothing to do with RocketMod.

Check https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/172

Yes, the linux installation guide is outdated, but we will update it with #1023
