### ISSUE TITLE
Database API

### ISSUE THREAD

**Issue by Trojaner** [RocketMod/Rocket#1037]
This was moved from the Alpha 2 Milestone.
Will likely be in its own NuGet package and depend on Entity Framework 5 or NHibernate.

**Comment by Trojaner25** [comment]
Will work on it once we know if Unturned 3 will support .NET 4.6 or not

**Comment by JustOneMoreBlock** [comment]
I was reading about the new RocketMod 5, and noticed this:
https://rocketmod.guide/development-guide/api/database/

_"plugins do not have to deal with database connections."_

I want to be able to have MySQL support. Is this going to be included here or will developers have to include a mysql.dll if they want to add that support?

**Comment by Trojaner** [comment]
At the moment we have Rocket.NHibernate and Rocket.EntityFrameworkCore as ORM implementations. However, these are not finished yet and will likely not be included in RM5 release. Until then you should include the MySql.Data.dll yourself  and use ADO.NET like in RM4.
