### ISSUE TITLE
Como actualizo el servidor

### ISSUE THREAD

**Issue by Nicolas2131311** [RocketMod/Rocket#1046]
¿Hay algun comando para actualizar el servidor si hay una actualizacion de unturned?

**Comment by persiafighter** [comment]
You have a few issues:

- This doesn't follow the format for issues.
- It is not in English.
- It is not a RocketMod issue

And here's your answer: You update your server the exact same way you installed it.


In Spanish/En Español:

Tienes varios problemas:

- Esto no sigue el formato para problemas en GitHub.
- No esta escrito en Español.
- No es un problema de RocketMod.

Y aquí tienes tu respuesta: Actualizas tu servidor de la misma manera que lo instalaste.
