### ISSUE TITLE
Chat Glitch

### ISSUE THREAD

**Issue by Dinoosawruss** [RocketMod/Rocket#1049]
**What problem did you noticed?**
The chat has strange symbols in it 

**What is the expected result?**
The chat looks nomral

**What is the current result?**
The chaat is unreadable and you cannot send messages

**How to reproduce the issue?**
I am not sure

Operating System and Version: Ubuntu 16.0

Unturned Version: Latest

Rocketmod Version: Latest
![image](https://user-images.githubusercontent.com/22278485/39537302-0a6ce7a6-4e31-11e8-8438-07fdcefb5cc6.png)

**Comment by ChubbyQuokka** [comment]
Update to the newest version of RocketMod.

**Comment by Dinoosawruss** [comment]
I am pretty sure its updated

**Comment by Dinoosawruss** [comment]
No I have updated and it is still happening. It also crashes every time someone types

**Comment by Dinoosawruss** [comment]
When I try to type I get this error

NullReferenceException: Object reference not set to an instance of an object - System.String.Concat (System.Object arg0, System.Object arg1)
SDG.Unturned.Block.write (System.Object objects)
SDG.Unturned.Block.write (System.Object[] objects)
SDG.Unturned.SteamPacker.getBytes (Int32 prefix, System.Int32& size, System.Object[] objects)
SDG.Unturned.SteamChannel.getPacket (ESteamPacket type, Int32 index, System.Int32& size, System.Byte[]& packet, System.Object[] arguments)
SDG.Unturned.SteamChannel.send (System.String name, ESteamCall mode, ESteamPacket type, System.Object[] arguments)
SDG.Unturned.ChatManager.askChat (CSteamID steamID, Byte mode, System.String text)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.Provider.receiveServer (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel)
SDG.Unturned.Provider.listenServer (Int32 channel)
SDG.Unturned.Provider.listen ()
SDG.Unturned.Provider.Update ()

**Comment by Trojaner25** [comment]
This is an unturned bug; not RocketMod.
