### ISSUE TITLE
Permissions Error Please Help 

### ISSUE THREAD

**Issue by SayeedBruh** [RocketMod/Rocket#1058]
NullReferenceException: Object reference not set to an instance of an object - Rocket.Core.Permissions.RocketPermissionsManager.HasPermission (IRocketPlayer player, System.Collections.Generic.List`1 permissions)
Essentials.Core.Permission.EssentialsPermissionsProvider.HasPermission (IRocketPlayer player, System.Collections.Generic.List`1 requestedPermissions)
Rocket.API.IRocketPermissionsProviderExtensions.HasPermission (IRocketPermissionsProvider rocketPermissionProvider, IRocketPlayer player, System.String permission)
LeeIzaZombie.ItemRestrictions.ItemRestrictions.IntegrityCheck ()
LeeIzaZombie.ItemRestrictions.ItemRestrictions.FixedUpdate ()

**Comment by Trojaner25** [comment]
Your permissions file is broken
