### ISSUE TITLE
RCON Command Line Arguments

### ISSUE THREAD

**Issue by hydeant** [RocketMod/Rocket#1068]
I asked about this in the Discord a while back and figured that I should properly submit a request.  Would it be possible to push the RCON configuration options via various command line arguments?  One scenario where this would be useful is, in my case, using a server management tool that toggles RCON and generates a random password on server start without having to write to the XML file each time.  I have included a concept list below.  

```
RCON Enabled="true" -> +enablercon true
Port="27115" -> +rconport 27115
Password="changeme" -> +rconpassword changeme
EnableMaxGlobalConnections="true" -> +enablemaxglobalconnections true
MaxGlobalConnections="10" -> +maxglobalconnections 10
EnableMaxLocalConnections="true" -> +enablemaxlocalconnections true
MaxLocalConnections="3" -> +maxlocalconnections 3
```

**Comment by Trojaner25** [comment]
Rcon is not part of RocketMod 5 and hence not supported anymore. Instead I'm planning on making it a plugin.
