### ISSUE TITLE
Permissions do not auto generate missing sections

### ISSUE THREAD

**Issue by Trojaner25** [RocketMod/Rocket#1077]
> [Info] [DefaultCommandHandler.HandleCommand] Trojaner executed command: "help"
KeyNotFoundException: Path "User" doesn't exist! - Rocket.Core.Configuration.JsonNetBase.JsonNetConfigurationElement.GetSection (System.String path)
Rocket.Core.Configuration.JsonNetBase.JsonNetConfigurationElement.get_Item (System.String path)
Rocket.Core.Permissions.ConfigurationPermissionProvider.GetConfigSection[PlayerPermissionSection] (IIdentity target, Boolean createIfNotFound)
Rocket.Core.Permissions.ConfigurationPermissionProvider.CheckPermission (IIdentity target, System.String permission)
Rocket.Core.Permissions.ConfigurationPermissionProvider.CheckPermission (IIdentity target, System.String permission)
Rocket.Core.Permissions.ConfigurationPermissionProvider.CheckHasAnyPermission (IIdentity target, System.String[] permissions)
Rocket.Core.Permissions.ProxyPermissionProvider.CheckHasAnyPermission (IIdentity target, System.String[] permissions)
Rocket.Core.Commands.DefaultCommandHandler.HandleCommand (IUser user, System.String commandLine, System.String prefix)
Rocket.Core.Commands.ProxyCommandHandler.HandleCommand (IUser user, System.String commandLine, System.String prefix)
Rocket.Unturned.RocketUnturnedHost+<>c__DisplayClass24_0.<OnServerHosted>b__0 (SDG.Unturned.SteamPlayer player, System.String commandLine, System.Boolean& shouldExecuteCommand, System.Boolean& shouldList)
SDG.Unturned.ChatManager.process (SDG.Unturned.SteamPlayer player, System.String cmd)
SDG.Unturned.ChatManager.askChat (CSteamID steamID, Byte mode, System.String text)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.Provider.receiveServer (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel)
SDG.Unturned.Provider.listenServer (Int32 channel)
SDG.Unturned.Provider.listen ()
SDG.Unturned.Provider.Update ()

**Comment by ChubbyQuokka** [comment]
Yup, I reported this a while ago.

I've gone ahead and made the implementation generate the missing sections for now.

**Comment by Trojaner25** [comment]
I will likely fix this tomorrow
