### ISSUE TITLE
Update wiki (rocket mod4) to 5

### ISSUE THREAD

**Issue by extreme4all** [RocketMod/Rocket#1086]
I want to make my own plugins and my own server to learn a bit more about programming etc.
but its pretty annoying if the wiki is not up to date #learningbyfrustration, could anyone update the wiki and sample code?
i found some things here but it does not seem to be updated:
https://rocketmod.guide/development-guide/concept/coding-style/
What i really want to know as a starter is:

1. how do i send something to a player, group, server
2. how can i make custom player/group attributes
3. how can access, modify things that a player does (places, shoots, attach)

**Comment by Trojaner25** [comment]
The wiki was abandoned and https://rocketmod.guide is the replacement for it.

The examples you posted are too specific, you can learn those things by inspecting open source plugins:
https://github.com/RocketModPlugins
