### ISSUE TITLE
Zombies not giving damage

### ISSUE THREAD

**Issue by LuxarPL** [RocketMod/Rocket#1093]
**What problem did you noticed?**
Zombies not giving damage + https://prnt.sc/k0vgyg

**What is the expected result?**
Getting damage

**What is the current result?**
Not getting damage

**How to reproduce the issue?**
Don't run away when zombies are chasing you

Operating System and Version: Windows Server 2012 R2

Unturned Version: 3.25.0.0

Rocketmod Version: 5.0.0.565

Rocket.Unturned Version: 5.0.0.163

**Comment by Trojaner25** [comment]
Regression of #1089

**Comment by Trojaner25** [comment]
Issue was fixed.
Apparently zombies have SteamIDs in Unturned and so Rocket tried to resolve them as players...
