### ISSUE TITLE
Logo Design Proposal

### ISSUE THREAD

**Issue by munadikiehl** [RocketMod/Rocket#1101]
Dear Sir/Madam,
Hi, my name is Munadi Kiehl. I'm a graphic designer and I would like to collaborate on your open source project and to propose free icon/logo design. If you're interested in, please, let me know.

Best Regard,
Munadi Kiehl

**Comment by Trojaner25** [comment]
@fr34kyn01535

**Comment by fr34kyn01535** [comment]
Well we are still looking for a new logo, could you show us a proposal?

**Comment by munadikiehl** [comment]
Hi @fr34kyn01535, and thank you for your reply! 

Could you please clarify some information that I could take into account to develop the most suitable design.

1. Where do you plan to use the logo - only for web or somewhere else?
2. Should it include any text or any specific object?
3. Colorful or black & white?
Any other wishes?

Best,
Munadi Kiehl

**Comment by fr34kyn01535** [comment]
Our current CI consists of the following banner-size logos which are basically just text:
![image](https://user-images.githubusercontent.com/898145/42417215-893b8b0a-8284-11e8-8ccf-d3f8d4994205.png) (on dark background)

![image](https://user-images.githubusercontent.com/898145/42417216-a78d8824-8284-11e8-9e15-825d711dce85.png) (on light background)

and the following square logo for social media, favicon etc:
![image](https://user-images.githubusercontent.com/898145/42417219-c9968e52-8284-11e8-9ee5-a1061dd17382.png)

I am currently reworking the logo to be similar across all our services, my current idea something like this (it is just a text logo again):
![rocketall](https://user-images.githubusercontent.com/898145/42417231-11376812-8285-11e8-9f5d-ea94c1abe617.png)

I don't have no idea for a square logo but i want to go away from the fontawesome-rocket logo we are currently using. 

Our current CI colors are:
RocketMod #13bfc1
RocketHarbor (The new name for the plugin repository) #c30125
RocketObservatory (Anti hack) #ef981b
RocketPlus #17b30f

**Comment by munadikiehl** [comment]
Hi @fr34kyn01535, thanks for all the information you give it to me! I will consider it in my design :)

**Comment by munadikiehl** [comment]
Hi @fr34kyn01535, I made some option of Rocket Logo, I use colors from your current CI . Please have a look. I'm waiting for your feedback. 
![rocket-01](https://user-images.githubusercontent.com/38290072/42422985-0ae062e2-831c-11e8-91af-f4b29acb1bec.jpg)

**Comment by fr34kyn01535** [comment]
I really appreciate your work, you did a brillant job. Unfortunatly I am not a big fan of the 3d look and find it a little to easy to just add a rocket next to the text. If you are still willing to work out some more ideas I'd propose a flatter style with fewer different colors, maybe let the symbol become more part of the text.

**Comment by baranmod** [comment]
Not really into logo design but maybe this will give some ideas
![rocket light](https://user-images.githubusercontent.com/14231707/42444543-0ebc9dec-8379-11e8-89df-aa6f5178f50e.jpg)
![rocket](https://user-images.githubusercontent.com/14231707/42444544-0ee0aa5c-8379-11e8-96a9-f207e29ad32b.jpg)

**Comment by fr34kyn01535** [comment]
@baranmod i am really digging this logo! Can you drop me a mail at fr34kyn01535@bam.yt with your terms?

**Comment by munadikiehl** [comment]
Hi @fr34kyn01535. This is the Rocket Logo become a part of the text. If there any revision, please just tell me. I'm waiting for your feedback.

![present 2-02](https://user-images.githubusercontent.com/38290072/42454047-b54b39cc-83b8-11e8-823d-00bf85b55ed6.jpg)

I hope you like it.
I'll provide all size and type file you needed.

**Comment by fr34kyn01535** [comment]
@munadikiehl could you drop me an e-mail aswell please with your terms?

**Comment by munadikiehl** [comment]
Hi @fr34kyn01535. Thanks for your feedback! I’ll prepare all the required file you needed via email : fr34kyn01535@bam.yt
Is that correct email sir?

**Comment by munadikiehl** [comment]
Hi @fr34kyn01535. I ‘ve sent you email, but action is delayed. 

Final-Recipient: rfc822; fr34kyn01535@bam.yt
Action: delayed
Status: 4.7.0
Remote-MTA: dns; mail.bam.yt. (89.163.129.20, the server for the domain bam.yt.)
Diagnostic-Code: smtp; 451 4.7.0 Temporary server error. Please try again later. PRX5
Last-Attempt-Date: Thu, 12 Jul 2018 00:02:34 -0700 (PDT)
Will-Retry-Until: Fri, 13 Jul 2018 23:36:13 -0700 (PDT)

**Comment by munadikiehl** [comment]
Hi @fr34kyn01535. I’ve sent you email twice, but action is still delayed. I don’t know why this could happen.

**Comment by fr34kyn01535** [comment]
It should work now, sorry.
