### ISSUE TITLE
Ip bind problem with rocket

### ISSUE THREAD

**Issue by gyzzako** [RocketMod/Rocket#1104]
Hello,

I have a vanilla server where i bound my local ip and everything worked properly. Recently I decided to create a rocket server. I did it but i've a problem. When I bind my local ip the server doesn't show up in server list and I can't connect, but when i don't bind my local ip i can see my server in server list but others people can't see it.

Thanks for your time.

**Comment by ChubbyQuokka** [comment]
I'm not sure that this is a RocketMod problem.

**Comment by gyzzako** [comment]
What's the problem ?
