### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by munadikieh** [RocketMod/Rocket#1107]
Dear Sir/ Madam,
Hi, I'm a Graphic Designer. I would like to make contributions to projects on Github.
After I review your project is great, I want to contribute to this projecy by creating new logo/icon for your web. I have made of sample of logo, is there anything you want to change, please let me know.
![present 2-02](https://user-images.githubusercontent.com/41304326/44330373-02dc3800-a491-11e8-9c7e-c51c37413321.jpg)

Best Regard, 
Munadi Kiehl

**Comment by fr34kyn01535** [comment]
Thanks for your contribution, we are gladly integrating them into our existing CI.
You were added to the list of contributors on our website https://rocketmod.net/contributors/.
