### ISSUE TITLE
error with loading plugins

### ISSUE THREAD

**Issue by spront5566** [RocketMod/Rocket#1115]
so when im trying to start up my server it gives me this exact error Failed to load ZaupShop, unloading now... :System.IO.FileNotFoundException: Could not load file or assembly 'I18N.West, Version=2.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies.
File name: 'I18N.West, Version=2.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'
  at ZaupShop.ZaupShop.Load () [0x00000] in <filename unknown>:0
  at Rocket.Core.Plugins.RocketPlugin.LoadPlugin () [0x00000] in <filename unknown>:0
and then it starts unloading the plugin how do I fix this

**Comment by Trojaner** [comment]
Not a RocketMod bug, you installed the plugin wrong.
Copy libraries folder next time.
