### ISSUE TITLE
Unturned rocket is broken

### ISSUE THREAD

**Issue by gregTHEworker** [RocketMod/Rocket#1116]
My unturned server rocket is broken so if i write for example /tpa it does nothing, it doesn´t say anything. And yes the tpa plugin is installed. If i write for example /abcd it says command not found. I removed all the plugins, but it didn´t help. I can´t even do /rocket reload.

**Comment by ChubbyQuokka** [comment]
If it does in-fact say `Command not found.` then Rocket is working fine. It's an issue with the plugin not working. Most likely a bad xml configuration for the plugin, or a bad install. Put the configuration file for the plugin through an xml validator such as https://www.xmlvalidation.com/ and fix all the errors it mentions.

**Comment by gregTHEworker** [comment]
Well as i said it doesn´t say anything like command not found. It doesn´t say anything

**Comment by gregTHEworker** [comment]
So what it says is 
[12/13/2018 4:08:48 PM] [Info] [World] Greg_the_worker [Greg]: "/i"

[12/13/2018 4:08:48 PM] [Info] General: Exception raised when RPC invoked askChat:

[12/13/2018 4:08:48 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - Rocket.Core.Permissions.RocketPermissionsManager.HasPermission (IRocketPlayer player, System.Collections.Generic.List`1 permissions)

Rocket.API.IRocketPermissionsProviderExtensions.HasPermission (IRocketPermissionsProvider rocketPermissionProvider, IRocketPlayer player, IRocketCommand command)

Rocket.Unturned.Permissions.UnturnedPermissions.CheckPermissions (SDG.Unturned.SteamPlayer caller, System.String permission)

Rocket.Unturned.U+<>c.<bindDelegates>b__16_3 (SDG.Unturned.SteamPlayer player, System.String text, System.Boolean& shouldExecuteCommand, System.Boolean& shouldList)

SDG.Unturned.ChatManager.process (SDG.Unturned.SteamPlayer player, System.String cmd)

SDG.Unturned.ChatManager.askChat (CSteamID steamID, Byte mode, System.String text)

System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)

Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.

System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)

System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)

SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)

UnityEngine.Debug:LogException(Exception)

SDG.Unturned.SteamChannel:receive(CSteamID, Byte[], Int32, Int32)

SDG.Unturned.Provider:receiveServer(CSteamID, Byte[], Int32, Int32, Int32)

SDG.Unturned.Provider:listenServer(Int32)

SDG.Unturned.Provider:listen()

SDG.Unturned.Provider:Update()

**Comment by gregTHEworker** [comment]
I removed entire permissions and it's still broken.

**Comment by gregTHEworker** [comment]
I got the rocket working, i don´t know what i did but it´s working. Thanks for the effort!

**Comment by Trojaner** [comment]
RockedMod is not broken. Your configuration is.
