### ISSUE TITLE
ZuapFeast not working

### ISSUE THREAD

**Issue by Adammild1** [RocketMod/Rocket#1119]
This is the error
[Error.txt](https://github.com/RocketMod/Rocket/files/2730120/Error.txt)

This is my configuration
[ZaupFeast.txt](https://github.com/RocketMod/Rocket/files/2730122/ZaupFeast.txt)

I turned it into a text file so that I could upload it. It is usually an XML file.

**Comment by Adammild1** [comment]
Well I figured it out with my very little knowledge on python with Booleans. If you run into this same error, you cannot have decimals for your chance. Sorry if this seams like spam, I should have checked for that before I posted here. This forum is dead anyway tho.

**Comment by Adammild1** [comment]
After turning my computer back on this morning, I now have another issue with workshop items. I do not think the mod can find the workshop items that I have downloaded. I would have posted this on the ZaupFeast github but it is dead.

**Comment by Trojaner** [comment]
This is not the place for reporting issues with plugins or workshop items.
