### ISSUE TITLE
unturned input string was not

### ISSUE THREAD

**Issue by XUGXs** [RocketMod/Rocket#1121]
when i start my server its says this error and when i use /kits and /kit (name) it says command not found but i wrote kits and permissions but its says not found..[https://ibb.co/KxsDRJc and
https://ibb.co/C0RDhSn](url)

**Comment by Trojaner** [comment]
Not a Rocketmod bug

**Comment by XUGXs** [comment]
then whats bug

**Comment by XUGXs** [comment]
help me please

**Comment by XUGXs** [comment]
> Not a Rocketmod bug

how can i fix

**Comment by Trojaner** [comment]
Contact the plugin author.
