### ISSUE TITLE
Player is not getting damage

### ISSUE THREAD

**Issue by RestoreMonarchy** [RocketMod/Rocket#1130]
Player character is not being damaged by any of the cases:
- Vehicle Explosion
- Zombie Bite
I'm getting error in console, but it's not included in the Rocket.log file. This is the gif of how it looks like in console [GIF](https://i.imgur.com/rlNqKCa.gifv) and this is it's part which I copied:

> NullReferenceException: Object reference not set to an instance of an object - Rocket.Unturned.RocketUnturnedHost.OnPlayerDamaged (SDG.Unturned.Player uPlayer, SDG.Unturned.EDeathCause& cause, SDG.Unturned.ELimb& limb, Steamworks.CSteamID& killerId, UnityEngine.Vector3& direction, System.Single& damage, System.Single& times, System.Boolean& canDamage) (at <970f00d6a2c841f2a29c108bde8ba95e>:0)
SDG.Unturned.DamageTool.damage (SDG.Unturned.Player player, SDG.Unturned.EDeathCause cause, SDG.Unturned.ELimb limb, Steamworks.CSteamID killer, UnityEngine.Vector3 direction, System.Single damage, System.Single times, SDG.Unturned.EPlayerKill& kill, System.Boolean applyGlobalArmorMultiplier, System.Boolean trackKill, SDG.Unturned.ERagdollEffect ragdollEffect) (at <2de13a8df2bb4bd79a2f1071f29293c3>:0)
SDG.Unturned.Zombie.tick () (at <2de13a8df2bb4bd79a2f1071f29293c3>:0)
SDG.Unturned.ZombieManager.Update () (at <2de13a8df2bb4bd79a2f1071f29293c3>:0)

**Comment by Trojaner** [comment]
Fixed

**Comment by Trojaner** [comment]
Regression of #1093

**Comment by Miltondax** [comment]
How can i fix that problem??
