### ISSUE TITLE
please help why are you closing you are not even looking -_-

### ISSUE THREAD

**Issue by sxugxs** [RocketMod/Rocket#1134]
https://imgur.com/gallery/JoK3dHh or https://imgur.com/a/JoK3dHh#0OXUdit
why are you not helping please i have 80 jobs RP server need to fix this

empathy please do 
empathy
if u fixed thank you ..
if you are not fixing please then tell me how..

**Comment by sxugxs** [comment]
helpppp

**Comment by Trojaner** [comment]
Stop spamming issues or we will take actions against you.
