### ISSUE TITLE
Runtime Error when Starting

### ISSUE THREAD

**Issue by Vloopic** [RocketMod/Rocket#1154]
**What problem did you notice?**
When starting my server I get an error saying:
```
Steam: UP TO DATE

WARNING: The runtime version supported by this application is unavailable.
```
I tried changing my mono version to the latest but that just game me more errors
I plan on trying to go back to 4.6.2 to get rid of the errors.

**What is the expected result?**
I expect that the server should start, but it gives me an error.

**What is the current result?**
Mono Runtime Warning, as stated above.

**How to reproduce the issue?**
Follow Rocketmods Wiki Guide and type ./start.sh.

Operating System and Version:
Linux using Ubuntu 18.04
Mono version was 4.6.2
Mono version now 6.0.0.313

Output of `/rocket install`:
`zsh: no such file of diectory /rocket`
This is probably because I'm on Linux.

**This probably wont help but here's the three lines that show up in the log.**
```
[04:16:56 - 31/07/2019] Steam: App: Unturned 3.30.4.1
[04:16:58 - 31/07/2019] Translations: Loaded "english" language "SDG" namespace
[04:16:58 - 31/07/2019] Translations: Loaded "testrussian" language "SDG" namespace
```

**Comment by Pustalorc** [comment]
> When starting my server I get an error saying:
> 
> Steam: UP TO DATE
> 
> WARNING: The runtime version supported by this application is unavailable.
> 
> I tried changing my mono version to the latest but that just game me more errors
> I plan on trying to go back to 4.6.2 to get rid of the errors.

That is not an error, it's a warning, and you can ignore it. It's the exact same reason why #1153 was closed and tagged as invalid.

**Comment by Vloopic** [comment]
The reason I was confused was that nothing else was being outputted.

There is another issue though that I had when I changed to 6.0.0.313
I got this after the warning. 
![image](https://user-images.githubusercontent.com/53507549/62237134-0ca33680-b396-11e9-8a5d-b520c6c46130.png)
then it stopped.

**Comment by Vloopic** [comment]
If when I change to 4,6,2 it fails, I'll send another issue, but I'm going to close this thread.
