### ISSUE TITLE
Servers\<name>\Rocket not downloading

### ISSUE THREAD

**Issue by NewbieHookTheWebhook** [RocketMod/Rocket#1155]
**What problem did you notice?**
Servers\<name>\Rocket not downloading
**What is the expected result?**
I expected it to download, but it didn't.
**What is the current result?**
Servers\Server1\Rocket is not valid.
**How to reproduce the issue?**
There is no way, unless I try again.

**Comment by Trojaner** [comment]
Closing since the issue is invalid
