### ISSUE TITLE
steamCMD wont install unturned

### ISSUE THREAD

**Issue by TheSkyes** [RocketMod/Rocket#1159]
hi im having problems with SteamCMD installing unturned for a server
i did this:
-logged in
-command i used: force_install_dir \unturned\app_update 304930
- tried other things
-tried searching on steam + google
i have no clue why its not working i hope some people can help me with this issue and i really do want to know if there are other ways to make a unturned server

**Comment by Trojaner** [comment]
Your issue is unrelated to RocketMod
