### ISSUE TITLE
Rocket.zip #404

### ISSUE THREAD

**Issue by kvxxx** [RocketMod/Rocket#1160]
Can you tell me what Rocket version is the latest version of unturned?

`https://ci.rocketmod.net/job/Rocket.Unturned/lastSuccessfulBuild/artifact/Rocket.Unturned/bin/Release/Rocket.zip` #404 can not download

**Comment by Pustalorc** [comment]
The download is here now: https://github.com/RocketMod/Rocket.Unturned/releases

Requesting to close this issue.
