### ISSUE TITLE
Cancelable events

### ISSUE THREAD

**Issue by fr34kyn01535** [RocketMod/Rocket#36]

**Comment by Trojaner25** [comment]
When will this be implemented? 
I can't implement features required for my safezone plugin, since e.g. I can't cancel picking or dropping items, or placing/destroying structures etc

**Comment by fr34kyn01535** [comment]
I know how events work. The problem is that i can't simply decompile unturned, add classes & change classes & recompile. All modifications to Unturned have to be done with IL instructions. Its possible, and i am able to do it - but its a lot of work, and not worth it right now as a) i dont need it and b) nelson changes something & everything breaks

**Comment by Trojaner25** [comment]
This was more like a suggestion to implement a custom event system, and not to use the C#'s one. It will allow you much more control over the events...

**Comment by fr34kyn01535** [comment]
Additionally i have to say that since events are not async, and in the proposed way being cancelable it would also mean i can't make them async. This means additional delay in the Unturned 3 networking for every plugin consumimg an event.

**Comment by Trojaner25** [comment]
I didn't say that you should make Unturned events async. I meant that plugins can define async events (e.g. IRC plugins, which want to create "OnIRCJoin" events for example)

**Comment by fr34kyn01535** [comment]
No, i said they have to be async. Doing extensive work in a event will cause the server to kick people because it would block networking. The way they are currently implemented there is no way to intersect events without slowing down the processing.

**Comment by Trojaner25** [comment]
Ok, I misunderstood it. I understand the problem now. Async events would also require thread-safe methods. E.g. If you wan't to kick a player from an async event, you would have to access the main thread, or some kind of queue...

Lets see what Nelson will do

**Comment by fr34kyn01535** [comment]
Using the Unity component model it can be achieved without another thread using the FixedUpdate method, i am afraid but Nelson will not do anything. The current events are completely hacked into the game, Nelson did not plan them in when he wrote Unturned.

**Comment by Trojaner25** [comment]
Is this implemented now?
