### ISSUE TITLE
Permissions with dot don't work?

### ISSUE THREAD

**Issue by ghost** [RocketMod/Rocket#449]
Code:
player.Permissions.ForEach(perm => Console.WriteLine(perm));

Console.WriteLine(player.HasPermission("uEssentials.warps.teste"));

Permissions:
      \<Commands\>
        \<Command\>warp\</Command\>
        \<Command\>uEssentials.warps.teste\</Command\>
        \<Command\>warps\</Command\>
        \<Command\>color.red\</Command\>
      \</Commands\>

Output:
http://i.imgur.com/Va6xX4o.png

**Comment by DevLeeo** [comment]
You fix?

**Comment by DevLeeo** [comment]
waiting...

**Comment by fr34kyn01535** [comment]
Have fun waiting ;)

**Comment by DevLeeo** [comment]
kid...
