### ISSUE TITLE
/save is causing lag (players get kicked)

### ISSUE THREAD

**Issue by alexr03** [RocketMod/Rocket#464]
Hi,
I don't know if its just me but when I use the Rcon and use the save command it saves fine but it also kicks a LOT of people out of the server giving them random messages like: "Server is now full", "Steam username is too long" "Authentication is invalid" ect. Is this a rocket issue??

![b099b8257af470010be5f9ded50b035d](https://cloud.githubusercontent.com/assets/11258483/8894483/fd30042c-33af-11e5-84e6-85b6bf2e3eb4.png)

Thanks!!

**Comment by fr34kyn01535** [comment]
Nope its not, Unturned does not handle this very well. Try to not let level save grow so big that saving takes so long...

**Comment by cartman-2000** [comment]
It's not really a problem with the size of the save file causing the disconnects. I've noticed this too on my server while trying to use the save command, it'll immediately disconnect most of the players off of the server when the command is used. You can also get random disconnects on other players with other commands used on the server too, through rcon.

The size of my world save generally doesn't go over 150kb for the PVP server, or 250kb for the PVE server.

**Comment by fr34kyn01535** [comment]
And the open player files?

**Comment by Sadusko** [comment]
Never had this issue?
Doesn't seem like a command issue.

**Comment by elfl0rd** [comment]
I really hate it...
