### ISSUE TITLE
Clear command not working

### ISSUE THREAD

**Issue by Riddler76** [RocketMod/Rocket#503]
Hi,

I'm running rocket 4.6.0.0.
The clear command is not operationnal, she say me 1... item delete but 0 item are deleted.

**Comment by cartman-2000** [comment]
I believe that this is more of a bug in Unturned, the commands works by setting the drop time on the items making them very old so Unturned's item clean up code "should" clean them up, but that has been broken somewhat in Unturned for the past few weeks.

**Comment by Riddler76** [comment]
Thanks :)
