### ISSUE TITLE
Request for new Player Events

### ISSUE THREAD

**Issue by robnauticus** [RocketMod/Rocket#509]
Hey, 
If possible please consider adding
OnPlayerCrafted(UnturnedPlayer, Item)
OnPlayerZombieKill(UnturnedPlayer)
OnPlayerAnimalKill(UnturnedPlayer)

If you could get the specific type of zombie / animal killed, that would help also.
Thanks

**Comment by robnauticus** [comment]
I think the Zombie / animal kill could be handled for now with the OnPlayerDeath EDeathCause variable. Not sure if animals can kill yet anyway...

**Comment by leonardosnt** [comment]
OnPlayerDamage(damagecause, damager, bla bla...)
