### ISSUE TITLE
Request for permission to not have any permissions

### ISSUE THREAD

**Issue by Zamirathe** [RocketMod/Rocket#511]
Essentially what was requested from me, and is not available to change as it would be a change in Rocket itself, is the ability to say "this group has no permissions".  So instead of this group inheriting from default, if there is the permissions none (just for example), then the check will essentially immediately return false for any permission check.

So if an admin wants to jail someone, run a mini-game where no commands are allowed, etc it can done fairly easy by just putting that person in a group with none as the permission.

**Comment by fr34kyn01535** [comment]
In your example that would be fairly easy to do by just SETTING them to a group with no permissions. You are requesting negative permissions here tho, am i right? (PermissionsEX for Bukkit did it with a exclamation mark in front of the permission afaik.

**Comment by Zamirathe** [comment]
Not sure what you mean by negative permissions.  However, afaik, just setting them to a group with no commands still gives them all of the default group commands as the default group is inherited even if no parent groups are assigned.  What I am asking for is a way to remove that.  If that is what you mean by negative permissions, then yes.

Now, not sure which way would be easiest, but this is what I thought.  In the checking of group permissions in Rocket.Core, if the permission "none" or whatever you want is added, then set the return value to an empty set and immediately return the empty set.

The only caveat I can see, is that if someone sets the parentgroup to that group with none it, it will then nullify the child commands also.  Which is fine by me.  Not sure why you would inherit from a group made to take away all command abilities.

For anyone else possibly reading, it also means that the person would lose their chat color too the way I am thinking.

**Comment by jjkrause** [comment]
Yeah, at the moment, the default group is always inherited no matter what, which causes issues if you're trying to create a tree-based permission system and don't want the default permissions inherited in all cases.  My default group has very basic permissions, such as rules and a list of jobs the players can choose from (Trojaner's Jobs plugin).  They cannot TPA, or do /home until they take a job.  Running the job command essentially places them in a permission group and then they have access to their commands.  I defined a permission group called 'CommonPerms' which contains permissions to commands all users need access to, and set this as the ParentGroup of all permission groups.  Unfortunately, its hard keeping things clean when the default group is automatically inherited.

Either of the 2 solutions would work fine, revoking permissions like PermissionsEX did, or not automatically inheriting the default group's permissions.  I think the second solution would be easier to implement and involve less entries in the Permissions.config.xml file though (removing the automatic inherit of the default group.

**Comment by fr34kyn01535** [comment]
#1007
