### ISSUE TITLE
NullReferenceException in SDG.Unturned.Block.write

### ISSUE THREAD

**Issue by LeeIzaZombie** [RocketMod/Rocket#517]
Since the new update, only one person can join the server, the other players make the following error show up and  no player can join the server:

[8/28/2015 9:53:06 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.Block.write (System.Object objects)
SDG.Unturned.Block.write (System.Object[] objects)
SDG.Unturned.SteamPacker.getBytes (Int32 prefix, System.Int32& size, System.Object[] objects)
SDG.Unturned.Steam.accept (SDG.Unturned.SteamPlayerID playerID, Boolean isPro, Boolean isAdmin, Byte face, Byte hair, Byte beard, Color skin, Color color, Boolean hand, Int32 shirtItem, Int32 pantsItem, Int32 hatItem, Int32 backpackItem, Int32 vestItem, Int32 maskItem, Int32 glassesItem, System.Int32[] skinItems, EPlayerSpeciality speciality)
SDG.Unturned.Steam.onInventoryResultReady (SteamInventoryResultReady_t callback)
Steamworks.Callback`1[Steamworks.SteamInventoryResultReady_t].OnRunCallback (IntPtr pvParam)
UnityEngine.Debug:LogException(Exception)
Steamworks.CallbackDispatcher:ExceptionHandler(Exception)
Steamworks.Callback`1:OnRunCallback(IntPtr)
Steamworks.NativeMethods:SteamGameServer_RunCallbacks()
Steamworks.GameServer:RunCallbacks()
SDG.Unturned.Steam:Update()

[8/28/2015 9:53:09 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.Block.write (System.Object objects)
SDG.Unturned.Block.write (System.Object[] objects)
SDG.Unturned.SteamPacker.getBytes (Int32 prefix, System.Int32& size, System.Object[] objects)
SDG.Unturned.Steam.accept (SDG.Unturned.SteamPlayerID playerID, Boolean isPro, Boolean isAdmin, Byte face, Byte hair, Byte beard, Color skin, Color color, Boolean hand, Int32 shirtItem, Int32 pantsItem, Int32 hatItem, Int32 backpackItem, Int32 vestItem, Int32 maskItem, Int32 glassesItem, System.Int32[] skinItems, EPlayerSpeciality speciality)
SDG.Unturned.Steam.onInventoryResultReady (SteamInventoryResultReady_t callback)
Steamworks.Callback`1[Steamworks.SteamInventoryResultReady_t].OnRunCallback (IntPtr pvParam)
UnityEngine.Debug:LogException(Exception)
Steamworks.CallbackDispatcher:ExceptionHandler(Exception)
Steamworks.Callback`1:OnRunCallback(IntPtr)
Steamworks.NativeMethods:SteamGameServer_RunCallbacks()
Steamworks.GameServer:RunCallbacks()
SDG.Unturned.Steam:Update()

(Sorry I don't know how to use BBCodes here)

**Comment by Kirollos** [comment]
Confirmed.

![](http://puu.sh/jRYq3/74758ac0a5.png)

**Comment by fr34kyn01535** [comment]
Reported

**Comment by fr34kyn01535** [comment]
Reopening to prevent double post, can't fix tho

**Comment by tenten8401** [comment]
Hoping this gets fixed soon.
