### ISSUE TITLE
Plugins & Permissions not loading under certain conditions

### ISSUE THREAD

**Issue by fizzyjoe908** [RocketMod/Rocket#529]
I have found that any Rocket plugin and permissions will not be loaded by the server when the server software is started from the Windows command line.

When running the following commands from command prompt, the Unturned server is started and states that it is running Rocket in the console window but permissions and plugins do NOT load.

    start U:\unturned_101\101Unturned.lnk
    U:\unturned_101\101Unturned.lnk
    U:\unturned_101\Unturned.exe -nographics -batchmode +secureserver/101

Again, by running any of those, the server is started WITH Rocket but plugins are not loaded. When trying to manually load plugins via the "rocket load pluginname" command, the plugin cannot be found.

Plugins and permissions are successfully loaded only when the server shortcut is run manually by double-clicking it.

**Comment by fr34kyn01535** [comment]
This is happening when the working directory is not set correctly to the unturned folder...

**Comment by falsechicken** [comment]
Yeah. In Windows your shortcut should have a text box that allows you to set your working directory. I think its call "Start in" or something. I had this issue when I first started using Rocket. Forgot to set the working directory.
