### ISSUE TITLE
Implement more generic features into the API

### ISSUE THREAD

**Issue by fr34kyn01535** [RocketMod/Rocket#530]
List of RocketPlayers connected
Chat event & Chat sending
##

**Comment by leonardosnt** [comment]
you are working alone in this project?

**Comment by fr34kyn01535** [comment]
Yes

**Comment by leonardosnt** [comment]
How can I help?

**Comment by fr34kyn01535** [comment]
Contact me on XMPP or E-Mail at fr34kyn01535@bam.yt
