### ISSUE TITLE
rocket(Linux #300 for Unturned 3.13.3.1) console didn't show any activity

### ISSUE THREAD

**Issue by CLSMCSMII** [RocketMod/Rocket#535]
The previous version of rocket-linux console will show game settings from Commands.dat and it will accept admin input after I execute "mono RocketLauncher.exe InstanceName"

After new update with Halloween PEI (3.13.3.1) and new rocket-linux update #300 the console shows nothing and admin cannot input any command.

![console_error](https://cloud.githubusercontent.com/assets/13549498/10708903/50dce8a8-7a44-11e5-919c-89926e3b2df8.jpg)

**Comment by fr34kyn01535** [comment]
fixed
