### ISSUE TITLE
Rocket creating/reading the folder outside the server folder

### ISSUE THREAD

**Issue by manuelbarbosa** [RocketMod/Rocket#536]
Since last halloween update, Rocket is creating/reading the files on a directory outside the server folder:

servers\
              SERVER 1\
              SERVER 2\
Rocket\

...instead of...

servers\
              SERVER 1\
                                 Rocket\
              SERVER 2
                                 Rocket\

**Comment by fr34kyn01535** [comment]
Just have been trying it and couldn't seem to replicate. Whats the instance name you tried? Please share the full command line u started the server with.. also check an instance name without spaces.

**Comment by manuelbarbosa** [comment]
I am sorry, seems to be fixed already, I just downloaded the version before the Halloween patch and for some reason was having that behaviour. You can close this issue.
