### ISSUE TITLE
Vanish - Since the last update.

### ISSUE THREAD

**Issue by Ayria** [RocketMod/Rocket#539]
Apparently since this last update, when vanished and moving you flicker in and out of existence. =\

This is bad if I'm trying to follow a player being accused of hacking.

**Comment by cartman-2000** [comment]
For me I've seen that you get stuck in the location that you last teleported to, when viewed by the other players, you would also walk/run in place when vanished when viewed by others. 

It is still possible to be vanished to other players, but you have to teleport either above them or close to them out of sight for them not to see your player model frozen in place.

**Comment by Ayria** [comment]
Yes, only just recently did I notice the walking in place.
