### ISSUE TITLE
Can't refuel a vehicle using gas can

### ISSUE THREAD

**Issue by Vertoix** [RocketMod/Rocket#540]
Hi.

I'm now having a problem in my own rocket server.
Usually I played with my friend, started from pvping and a race, but there's a big problem in there, the car can't be refueled, and it was a big mess

 so if the car fuel goes to 0%, there's nothing to do, respawning the car is such annoyance.

Hosting without rocket is fine, but this issue occurs when I hosted a server with rocket
and currently, I only have kits plugin.

Reinstalling it won't help, still the same

**Comment by alexr03** [comment]
Yes, I am also having this issue, works fine on singleplayer, but not on multiplayer along with the not being able to refuel cars, you cannot also do any of the new features like using generators to open military gate ect, I believe this maybe a rocket bug.
