### ISSUE TITLE
ReCAPTCHA not working on downloads

### ISSUE THREAD

**Issue by Superninjaman426** [RocketMod/Rocket#545]
I tried downloading rocket update #640 and it verify for me. I tried it on 2 separate computers and but the recaptcha just keeps going around and around.

**Comment by greendayss** [comment]
yes this problem is happen to me, the captcha don't working

**Comment by romponu** [comment]
Same for me, please fix this! :)

**Comment by sdssaeq** [comment]
me too

**Comment by xxFIGHTxMExx** [comment]
if u guys havent solved it yet i solved it by getting a API key (dont ask how cause i have forgotten) but after getting one i can download it fine hope this works for u guys ill try find how i got API key

**Comment by xxFIGHTxMExx** [comment]
okay got it on the rocket website click the tab "Get Rocket" then scroll to the bottom of page and on the right side there's the following tabs API, Wiki, Bugtracker, etc, etc. just click on API and it will take you to another page where u enter your server name and then its generates a API key for you, which you then copy and (put it somewhere safe so u can use it again) paste it into your web browser and it will automatically come up with the save thing without a verification im not a robot thing and you can just click save and the then your done, you then just have to install it into your server folder thing.
  


https://rocketmod.net/
