### ISSUE TITLE
Chapta Fix Error Solved !!!!

### ISSUE THREAD

**Issue by sdssaeq** [RocketMod/Rocket#549]
GET http://api.rocketmod.net/download/unturned/<latest|BUILD ID>/<API KEY>(/filename.zip)Download latest Unturned for Rocket
Example request:
GET http://api.rocketmod.net/download/unturned/latest/C6A10034-4EBA-42D2-86FD-15CF4E8BC281
GET http://api.rocketmod.net/download/unturned/641/C6A10034-4EBA-42D2-86FD-15CF4E8BC281/RocketUnturned.zip

Login To Get Api key 

THX

**Comment by axiomaticTwist** [comment]
Perfect!!! My server has been down for like, half a day! Thx much
