### ISSUE TITLE
Unturned Rocket: Steam can not be initialized

### ISSUE THREAD

**Issue by TheKigen** [RocketMod/Rocket#551]
So after recent updates where Vanish is also missing the Unturned server can no longer connect to Steam if Rocket is installed.  I've verified that Steam will function without Rocket installed.

**Comment by falsechicken** [comment]
I cannot replicate this (On Linux).

**Comment by TheKigen** [comment]
I'm getting the issue on Windows.  Should have specified that.  Windows 2012 R2 x64 bit server.

**Comment by falsechicken** [comment]
I cannot test in Windows at the moment. I can get Rocket to say It cannot connect to Steam if I close the Steam client. Unfortunately my knowledge of running on Windows server is limited. Have you tried reinstalling Rocket and verifying the game cache with Steam?

**Comment by TheKigen** [comment]
I update Unturned via SteamCMD.  I've tried with and without the Steam Client installed but it made no difference.  And yes, I run app_update validate.

**Comment by falsechicken** [comment]
Ok. And you mentioned that you tested running the server without Rocket? (I know you said "steam works without Rocket", just wanting clarification.)

**Comment by TheKigen** [comment]
Yes, I tested it via removing the download for Rocket.  I create a batch script that automatically updates Unturned then downloads and installs the Rocket zip.  I removed the Rocket update portion on the same server and Steam works.

**Comment by falsechicken** [comment]
Aright. Ill notify @fr34kyn01535 and see what he thinks.

**Comment by falsechicken** [comment]
This has also been confirmed by @ApokPT.

**Comment by fr34kyn01535** [comment]
If you look at the linux script, i recently modified it to get rid of the issue on linux (https://github.com/RocketMod/Rocket.Unturned/blob/master/Scripts/Linux/start.sh#L32).
Nelson seemed to ship outdated linux binaries in that case. The issue could be outdated libraries in Unturned/Unturned_Data/Plugins, try to update both, CSteamworks.dll and steam_api64.dll.

CSteamworks.dll is the C# binding/implementation of the linux SDK and available here: https://github.com/rlabrecque/Steamworks.NET/releases

**Comment by TheKigen** [comment]
It results in an instant crash if I attempt to use those binaries, with or without Rocket.

**Comment by fr34kyn01535** [comment]
Try running steam
