### ISSUE TITLE
Problem with Server

### ISSUE THREAD

**Issue by Gelonator** [RocketMod/Rocket#552]
Everything works fine with my server, i port forwarded it, and everything and set exceptions for the firewall and everything. EVRYTHING WORKS FINE... BUT... MY FRIENDS CANT JOIN AND EVEN MY BROTHER IN THE SAME HOUSE!!! it worked fine without rocket, and when installed rocket (new folder and game files) only i can join my server and noone else! 

Any solutions/comments i appreciate!!

**Comment by fr34kyn01535** [comment]
I dont believe that this is a rocket issue, do you have any plugins setup?

**Comment by Selected420** [comment]
Same for me. But when I turn off windows firewall players can join the server, I have all exeptions...

**Comment by fr34kyn01535** [comment]
Well then please make sure to forward all ports (27015,27016,27017)

**Comment by Selected420** [comment]
...

**Comment by Selected420** [comment]
Ok guys, I've fixed it. I just turned off and then turn on windows firewall and it's fixed lol :D
