### ISSUE TITLE
Add minHoursPlayed, VacBan and Limited check from steam api

### ISSUE THREAD

**Issue by fr34kyn01535** [RocketMod/Rocket#561]
Write a Class to retrieve infos from http://steamcommunity.com/profiles/76561198201629499?xml=1
(also groups you are member of) to be used in plugins, or in rocket.

**Comment by LeeIzaZombie** [comment]
By ApokPT if you didn't notice on XMPP: http://pastebin.com/K7DtvNDs

**Comment by manuelbarbosa** [comment]
@fr34kyn01535 for groups use:

http://steamcommunity.com/gid/103582791434248624/memberslistxml/?xml=1

<3 Apok

**Comment by fr34kyn01535** [comment]
Done,  to be found in Rocket.Core.Steam
