### ISSUE TITLE
OnPlayerInventoryAdded - parameters do not match signature

### ISSUE THREAD

**Issue by LeeIzaZombie** [RocketMod/Rocket#563]
How'ya,

So I was just testing a few things I decided why not try make an item restriction system, so I did some initial testing and came across this error.

This code returns the error:
```C#
UnturnedPlayerEvents.OnPlayerInventoryAdded += UnturnedPlayerEvents_OnPlayerInventoryAdded;
(^ On plugin load)

void UnturnedPlayerEvents_OnPlayerInventoryAdded(UnturnedPlayer player, InventoryGroup ig, byte invIndex, ItemJar P)
{
           
}
```

This is the error:
![capture](https://cloud.githubusercontent.com/assets/7387999/11867735/d19429a8-a4aa-11e5-88df-936e243f93cd.PNG)

Hope you can fix it! :)

**Comment by fr34kyn01535** [comment]
Should be fixed

**Comment by LeeIzaZombie** [comment]
Confirmed, thanks for the fix!
