### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by mra00** [RocketMod/Rocket#566]
When I try to download the most recent version, I confirm the re-capcha, press download and it brings me to a blank page and no download. Please fix this, my server runs on rocket and is a major part of it.

**Comment by LeeIzaZombie** [comment]
Works for me. Try again...

**Comment by mra00** [comment]
Ive been trying every few hours... Just blank page.... No download options or anything. My servers been running vanilla since Friday, and its boring now.
