### ISSUE TITLE
I need help to create Unturned server to VPS

### ISSUE THREAD

**Issue by DiKi777** [RocketMod/Rocket#567]
Hello friends. I need help to create Unturned server to VPS. I have 10 days I can not move. Can someone explain in detail. https://github.com/RocketMod/Rocket.Unturned/tree/f76d889fd4bfe865d443104f4f161c1821d8eb44/Scripts/Linux It does not help, it prints an error. Reinstall OS Linux Debian 86_64. Can install any kind will tell new

**Comment by fr34kyn01535** [comment]
This belongs into the forum..
