### ISSUE TITLE
rocket command not working 

### ISSUE THREAD

**Issue by sharkbound** [RocketMod/Rocket#569]
this is a screenshot of the error i get when trying to run it - https://gyazo.com/a1fe21bf81281a831bd6c010c2039528

also it only says this if you use the command from console

**Comment by axiomaticTwist** [comment]
I am getting this problem too. Any workarounds other than having to go in-game and type it?

**Comment by sharkbound** [comment]
only way i have found is to admin yourself then do them in game

**Comment by fr34kyn01535** [comment]
Fixed
