### ISSUE TITLE
NO Console Commands Work!

### ISSUE THREAD

**Issue by axiomaticTwist** [RocketMod/Rocket#570]
I have tried every command, and only a few work from the console. I can only do the extreme basic commands, such as broadcast, say, and help. Other than that, it gives me an "Object Reference Not Set to an Instance of an Object" error. Absolutely stumped! I believe in-game these commands work, but not in the console.

![image](https://cloud.githubusercontent.com/assets/15700084/11965999/99bc6b1a-a8ad-11e5-9fa9-82b89dc6ad65.png)

**Comment by cartman-2000** [comment]
I have the same problem one of my server's that I updated to the current build of rocket.

**Comment by eldimarzioxp** [comment]
Yes i have this problem. ¿How i can give me admin? i intent add my name in Adminlist.dat but this not work :/ Please help!

**Comment by fr34kyn01535** [comment]
Fixed
