### ISSUE TITLE
Issues with running built in command in RCON.

### ISSUE THREAD

**Issue by cartman-2000** [RocketMod/Rocket#574]
Any plugin command that was registered by rocket works, but any command built in to Unturned(Players, Save, Teleport, etc.) or commands that were registered outside of rocket(Commands registered in ZaupTextCommands for example.) don't work in RCON.

**Comment by falsechicken** [comment]
This was resolved with the introduction of the /exec command.

https://github.com/RocketMod/Rocket.Unturned/commit/e2af2dfdf0d8665dc96973a3e5306ad765ffb63d
