### ISSUE TITLE
Weird disconnect issue which shows in console

### ISSUE THREAD

**Issue by alexr03** [RocketMod/Rocket#575]
Hi,

When someone leaves my server I seem to get this message:

[issue server.txt](https://github.com/RocketMod/Rocket/files/71726/issue.server.txt)

Any Ideas?

**Comment by cartman-2000** [comment]
Have you tried to reset your map's barricades file, or use a backup of the file, if you have one?

**Comment by alexr03** [comment]
I will reset it tomorrow while everyone is spending time with family ect and not on games :P otherwise im'a get abused with messages lol. I'll keep you updated.

**Comment by fr34kyn01535** [comment]
Not a rocket bug
