### ISSUE TITLE
Bad encoding for start.sh and update.sh

### ISSUE THREAD

**Issue by odyss3y** [RocketMod/Rocket#576]
They just need dos2unix run on them.

**Comment by falsechicken** [comment]
Yeah. I informed Freaky about this issue. He said that dos2unix is already executed during the build. So I don't know whats up here.

**Comment by odyss3y** [comment]
4.7.0.0 had the same problem fwiw

**Comment by fr34kyn01535** [comment]
Fixed :P After fixing the Rocket.Unturned build job i copied the build preperation scripts that contained the execution of unix2dos for the windows scripts without changing to dos2unix :P Sorry :D
