### ISSUE TITLE
Cant verify my email in rocket.foundation

### ISSUE THREAD

**Issue by rapidecr7** [RocketMod/Rocket#577]
Hello, ive made several attempts to create an account it says my account is already created but i cant login since i need to verify my email and they dont send anything to my email :(

Can anyone help me?

**Comment by Watersoep** [comment]
I've got the excact same thing. Even when i tried to send the administrator a mail it gives me 504 Bad-Gateway

**Comment by fr34kyn01535** [comment]
Could you share the error report please?

**Comment by fr34kyn01535** [comment]
Okay,  I fixed an issue with the assp proxy,  confirmation mails from the forum were resend. Sorry :D

**Comment by Watersoep** [comment]
Thanks man!
