### ISSUE TITLE
Overriding a command from another plugin

### ISSUE THREAD

**Issue by lightphoenix2** [RocketMod/Rocket#579]
Since there is no order to which Rocket will choose which command to use if there are two same command, overriding a command from another plugin will be impossible. I would like to make it possible. 

Thanks!

**Comment by leonardosnt** [comment]
Use reflection to access the field "commands" in RocketCommandManager (R.Commands) and remove if name is equals to X.

commands.RemoveAll( cmd => cmd.Name.Equals("bla") );

Example: (used in my plugin, "uEssentials")

```c#
private static void UnregisterRocketCommand<T>() where T : IRocketCommand
{
    var rocketComamnds = AccessorFactory.AccessField<List<IRocketCommand>>( 
        R.Commands, "commands" );

    rocketComamnds.Value.RemoveAll( cmd => cmd is T );
}
```

**Comment by lightphoenix2** [comment]
Let say I want to replace zaupShop /buy command. How to I do that so the my /buy command will still be workable.

**Comment by fr34kyn01535** [comment]
The command mapping is used to do this. A developer should never force a user to choose their commands over other commands. Only exception i see is in overriding vanilla commands.
