### ISSUE TITLE
Rocket throws an exception then almost no plugins load after new update

### ISSUE THREAD

**Issue by nern9** [RocketMod/Rocket#580]
After starting up the unturned server, this error occurs, then every plugin that loads also throws more errors. Here is the first one that i see, and im assuming its Rocket.

```
Error in MulticastDelegate RockedInitialized: System.Reflection.TargetInvocation
Exception: Exception has been thrown by the target of an invocation. ---> System
.MissingFieldException: Field 'SDG.Unturned.ChatManager.voterate' not found.
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (ob
ject,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invoke
Attr, System.Reflection.Binder binder, System.Object[] parameters, System.Global
ization.CultureInfo culture) [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invoke
Attr, System.Reflection.Binder binder, System.Object[] parameters, System.Global
ization.CultureInfo culture) [0x00000] in <filename unknown>:0
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] par
ameters) [0x00000] in <filename unknown>:0
  at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x00000] in <file
name unknown>:0
  at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00000]
 in <filename unknown>:0
  at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <filename
 unknown>:0
  at Rocket.Core.Extensions.MulticastDelegateExtension.TryInvoke (System.Multica
stDelegate theDelegate, System.Object[] args) [0x00000] in <filename unknown>:0
```

Any help would be appreciated. Thanks!

**Comment by Phyb** [comment]
Same for me. And basically every rocket command doesn't work. Only Vanilla commands are left.

**Comment by SwagAf** [comment]
Same for me as well, please fix it asap thanks alot

**Comment by MashAngLaro** [comment]
yep ... it messed up my whole server now i have to wait till they fix all of this. please fix this i lost a save

**Comment by MashAngLaro** [comment]
is there a autosave plugin?

**Comment by SwagAf** [comment]
i think the server autosaves every 1800 seconds

**Comment by cartman-2000** [comment]
This Commit is to blame for this trace. The vote kick stuff was removed in the patch update.
https://github.com/RocketMod/Rocket.Unturned/commit/ad80315252599cbf6134950e7b98fbebbb5c1dd0

**Comment by nern9** [comment]
if thats all that was added, then ill just download the source and remove those lines, then compile it for use until another build is released on rocket

**Comment by nern9** [comment]
Alright, ive made the modifications. [Ill upload the source and the dll file to dropbox if anyone wants it. ](https://dl.dropboxusercontent.com/u/160303341/Rocket.Unturned-master.rar) Thanks @cartman-2000 for showing me the commit!

**Comment by SwagAf** [comment]
thanks alot @nern9

**Comment by minecraftfan367** [comment]
Nothing works...

**Comment by nern9** [comment]
What do you mean nothing works? Like what is it doing?

**Comment by michael5323** [comment]
@nern9 Hey my server seems to be stuck on gold mode after replacing the file.

**Comment by cartman-2000** [comment]
I also uploaded my build of it to git(built on VS2015).
https://github.com/cartman-2000/Rocket.Unturned/releases/tag/untagged-245b9142841f02ebc04e

**Comment by nern9** [comment]
@michael5323 make sure that you gold isnt set as the difficulty in your config for the server

**Comment by michael5323** [comment]
@nern9 I know it isn't set to gold but I found out the problem somehow my rocket files got corrupted causing issues.

**Comment by michael5323** [comment]
Also @cartman-2000 Just to tell you that link is invalid.

**Comment by cartman-2000** [comment]
Updated link.

**Comment by jorea143** [comment]
can anyone confirm if this is working?

**Comment by nern9** [comment]
I can confirm, im running it on my server right now. if you want the IP i can tell you it

**Comment by jorea143** [comment]
Thank you. I will try it on my server. Thank you for the share.

**Comment by nern9** [comment]
No problem :) Thank @cartman-2000 for the fix

**Comment by cartman-2000** [comment]
I sent in a pull request to revert the breaking commit and to fix a bug in the /p command.
https://github.com/RocketMod/Rocket.Unturned/pull/15

**Comment by odyss3y** [comment]
is this quick fix update working for anyone on linux? its not working for me.

**Comment by cartman-2000** [comment]
The build I uploaded was built for windows, I have no way to test it on Linux, I've never been able to get a linux Unturned server to work properly on one of my other comps with Linux on it.

**Comment by xyzdevdox** [comment]
Can someone make Linux Build ?

Thanks.

**Comment by fr34kyn01535** [comment]
The fix was merged, latest version was build & has the fix.

**Comment by Phyb** [comment]
I found where to put RocketUnturned.dll, but where do I put the other files?
