### ISSUE TITLE
Rocket's new update? Ruins every plugin

### ISSUE THREAD

**Issue by minecraftfan367** [RocketMod/Rocket#581]
Rocket's new update ruined everything...
Plugins, Kits, Permissions, Servers...
Mind for a quick fix??

**Comment by jonthegreat** [comment]
dude ik right i cant even use the normal admin commands because i don't know how to uninstall rocket :P

**Comment by cartman-2000** [comment]
I uploaded a build of rocket.unturned that reverts the commit that broke it(you will still need to download arc for build 732 of rocket, then extract this replacing the Rocket.Unturned.dll file.).
https://github.com/cartman-2000/Rocket.Unturned/releases/tag/untagged-245b9142841f02ebc04e

**Comment by jonthegreat** [comment]
that just comes up with a thing that says this is not what you where looking for

**Comment by cartman-2000** [comment]
updated link.
