### ISSUE TITLE
Rocket Unturned isuse Rocket 4.8.0.0 (#732) for Unturned 3.13.10.1

### ISSUE THREAD

**Issue by Manav307** [RocketMod/Rocket#582]
It ruined everything  players could not use the /i command even when i congigured the premmsions file  could not use tpa message announcer and also i would see a red long text like a lot of times.

**Comment by nern9** [comment]
Can you post the error? because we cannot tell you how to fix it if you dont tell us the exact error

**Comment by michael5323** [comment]
It's because nelson removed vote-kicking.
Go ahead and download this and put it in your Unturned Managed folder where the server is located.
https://github.com/cartman-2000/Rocket.Unturned/releases/tag/4.8.0.0

**Comment by odyss3y** [comment]
@michael5323 this didnt work for me. i get no error, either. ran update.sh, copied all the normal rocket stuff, then your update on top of that. any ideas? thanks for your effort.

**Comment by cartman-2000** [comment]
You may have tried to download it while I was updating the build with the fix for the /p command, you should be able to download it now.

**Comment by odyss3y** [comment]
@cartman-2000 i dont think so. now I'm getting "Steam: Updating"
steps:
run update.sh
download linux package from site
download Rocket.Unturned.dll
move to the correct folders
run start.sh

md5's below:
`4addabb2e40a4d2904a18c1607858673  RocketLauncher.exe
e8bf5ca1b453fe11b38b6a071cc1c1b8  Assembly-CSharp.dll
b25a066fe6b7f1c154bfc63f51a7c7f8  Rocket.API.dll
6c84a8d16316f0e1e1a7d4308ed10409  Rocket.Core.dll
76af37653f3584a8e6c448da6d5ab8b8  Rocket.Unturned.dll`

**Comment by LcATD** [comment]
@cartman-2000 Hello, just sayin my server(3.13.10.1) is having the same issue atm. The server is pretty much cracked as the permisson config doesnt seem to be working thus I cant save the server unless I'm on admin. (Before the update I'm in a permission group with 'save' and other command, now none of them are working.)
I've checked the log and found my log flooded with this error
'[Exception] Rocket.Unturned >> Exception in TriggerSend: System.NullReferenceException: Object reference not set to an instance of an object
  at Rocket.Unturned.Events.UnturnedPlayerEvents.TriggerSend (SDG.Unturned.SteamPlayer s, System.String W, ESteamCall X, ESteamPacket l, System.Object[] R) [0x00000] in <filename unknown>:0 '
Hope you can help to solve this, appreciated.
