### ISSUE TITLE
Am I allowed to contribute regularly?

### ISSUE THREAD

**Issue by dretax** [RocketMod/Rocket#584]
It seems like RocketMod lacks a bunch of things and many could be added such as hooks. I saw that Unturned has public delegates mostly which you can obviously subscribe to.

Take a look how we work on Pluton example. https://github.com/Notulp/Pluton

We also allow smaller languages to run suches Py, Js, Lua.

It's obvious that the doc is also missing stuff. Am I allowed to send a huge amount of pull requests so you guys decide what you need from It and what not?

**Comment by xyzdevdox** [comment]
That would be great writing plugins in Python :D

**Comment by fr34kyn01535** [comment]
Well, the core library is not open source.. The core library would be the right spot to start with this, since there was no public fuss around it yet it is still private..

**Comment by fr34kyn01535** [comment]
I will work towards making Rocket open source soon,  I will keep the patcher private tho it has been a great help for hack developers when it was open source a year ago

**Comment by fr34kyn01535** [comment]
And sure,  I am happy about every contributions as long as they follow the conventions. I am a lil lazy when it comes to documentation,  but this is simply a little to much to do for just one developer. Atleast the quality of code is something I am taking me time for -  everything should be easy to understand and follow common best practices,  if not then correct me.

**Comment by dretax** [comment]
To be honest Rocket needs plugin concept modifications. You can take a look at our Patcher, I don't know how you are patching correctly, but I already changed my server to have gold loot on a normal difficulty. (Which is obviously not hard) I have a great experience in unity due to Rust Experimental/Legacy, and now Interstellar Marines trusted Pluton team to create a mod for their server files. If you think you are interested, I can assist in developing RocketMod. I know, I know, I'm just a random guy, but a guy who has experience and would gladly spend time on this. And as I see we already have people interested in Python. Maybe there are people for js too?

**Comment by falsechicken** [comment]
I think any contributions you can make would be welcomed. Some PRs may be denied. But I am sure every one is appreciated.

**Comment by fr34kyn01535** [comment]
https://github.com/RocketMod/Rocket/commit/6cad743defb526a49cd0ee9b7aeca5a3f21a724a#commitcomment-15313236
