### ISSUE TITLE
I have checked on other issues about the new Rocket fix, and I am having trouble finding the place for the files

### ISSUE THREAD

**Issue by Phyb** [RocketMod/Rocket#587]
I know about 2 or 3 people came with a fix for the new update, and I can't find where to put the files. I know where to put RocketUnturned.dll, but all the other files are a  mystery to me.
https://gyazo.com/04c3f4262c254a38ee961074dbccd2ba
https://gyazo.com/683f967b5e1ee7ec2c2e99697073322b

**Comment by fr34kyn01535** [comment]
This hasn't changed and is documented
