### ISSUE TITLE
Request: User-to-Admin message system plugin

### ISSUE THREAD

**Issue by guttyrrrm** [RocketMod/Rocket#591]
Hi guys :) I came here to suggest you a plugin where users can easily talk with the server admins in order to ask questions or report players with a simple command like /uta . The admin group read the message sent to them and then they can talk to them in private. Is this possible? Thanks.

**Comment by falsechicken** [comment]
I am sure it is possible. But this is not really the place for plug-in suggestions. That would be here: https://rocketmod.net/viewforum.php?f=9
