### ISSUE TITLE
Unturned LAG

### ISSUE THREAD

**Issue by alphaangel** [RocketMod/Rocket#593]
Hello all,

It's been a while of waiting for an official solution to the lag problem. Which lag problem? 3 TPS problem. Server owners like my self should know immediately what I'm talking about. 

Server specs:
2x Xeon 5620
48 GB ram
2x 2TB RAID 0
gigabit Ethernet.

So far after years of hosting Unturned since back in version 2, I realize version 3 is much more efficient and I love how server files are not in the reg anymore. But WHY SO MUCH LAG?  After a ton of experimenting and doing research I've come to a 100% conclusion that after so many structure and barricade data saved, no matter if its 24 players or 12 players, without a level wipe there is absolutely no fix. Lag is 100% caused by level data. What I can't seem to understand is why?? 

This game has a HUGE focus on building yet building is what causes the server to lag?!?! Hey dev, don't you think it should be your number 1 priority to make it so that building does not cause lag? If I made a game where 1/3 or more of the game is about building awesome bases, I would make it so buildings don't cause lag. IT SHOULD BE THE FIRST THING YOU THOUGHT OF WHEN YOU MADE THE GAME! It's an awesome game but I can't play it my self because I'm too busy monitoring how old my level data gets, and responding to calls about lag this lag that... [End meaningful rant]

For anyone that stumbles on this article, if you have a solution please let me know but please remember I am an experienced server admin. I have tried different locations, different hardware, every plugin and configuration, so please don't ask me if I have enough internet or if I've tried restarting the servers.

For anyone looking for a solution, here is what I have. Having too many bases causes lag, especially in combination with lots of players. I have noticed that after a map wipe, it does NOT matter how many players join, there is no lag. I can have 30 players on a server and player ping will slightly increase just as long as it is a fresh wipe. After weeks of not wiping the server (if your server is popular), anything close to 20 players will cause... you guessed it, LAG!

I believe having a CPU better optimized for single core performance will definitely help but it does not fix the problem. I can have the worlds fastest Intel single core performance and still get crazy lag if the server fills up on 1 month of level data.

My current setup (don't judge, this isn't where I make my conclusion of lag): I have 12 Unturned servers on my dual Xeon server. I may be pushing limits here but surprisingly, my cpu usage has not hit over 70-80%. Ram usage is usually around 5-6 GB. To my knowledge I can probably host more on this server but my other 6 servers are on another machine and location, with 20Mb upload which is quite alright for 6 Unturned servers. I have monitored and my bandwidth is not close to capped on either server.

**Comment by falsechicken** [comment]
Many have complained about this. It is a real problem. But its not a Rocket one. And therefore does not belong here as a Rocket issue.

https://github.com/SmartlyDressedGames/Unturned/issues
