### ISSUE TITLE
Memory leak, or RAM allocation problem?

### ISSUE THREAD

**Issue by Larsdude** [RocketMod/Rocket#595]
I'm not sure which one it is, but whenever I try to run my Unturned server with Rocket (version 750), the server uses 6GB of RAM. I can't seem to find any kind of configurable ram allocation in any permissions, configs, or batch files that the server uses, so what's going on?
![unturned ram problem](https://cloud.githubusercontent.com/assets/16531822/12360981/d623d2a6-bb80-11e5-9030-0c4b1a02b204.png)

EDIT: Deleting my old world and using a new one fixed the problem. Seems the 4.14.0.1 update changed enough about levels to cause it to break my server. Not sure if anyone else will have the same problem, but that's how I fixed it for me.

**Comment by fr34kyn01535** [comment]
https://github.com/RocketMod/Rocket/issues/127
