### ISSUE TITLE
Making XmlException readable

### ISSUE THREAD

**Issue by fr34kyn01535** [RocketMod/Rocket#596]
I guess too many people can't read them, i guess i need to catch them specifly and make a longer explanation why the exception happened (Its >Always< malformed xml....)
##

**Comment by falsechicken** [comment]
Yeah... I guess it would help put a dent in the number of false reports that happen to be user error. Even though I feel like the exception already is pretty clear. Idk how its not being understood....

**Comment by cartman-2000** [comment]
It maybe a bit unclear to those that don't know xml syntax that well.

**Comment by fr34kyn01535** [comment]
https://rocketmod.net/viewtopic.php?f=7&t=1445

**Comment by falsechicken** [comment]
OK I do admit that one is a little more cryptic than a malformed XML error lol.

**Comment by fr34kyn01535** [comment]
Why? it states that there is text in the very first line & char where no text is expected :D

**Comment by falsechicken** [comment]
I feel that "Text node cannot appear in this state." is a bit cryptic to a non-programmer. Especially if they do not have a concept of what a "state" is lol.

**Comment by fr34kyn01535** [comment]
New idea: A "Report bug" button, where people can select their plugin / part that has an issue and paste the bug report, and automatically are offered to create a post in the correct forum, or directly offered a solution, based on the error.

**Comment by falsechicken** [comment]
I like this idea. Where would this be in the forum for within Rocket itself?

**Comment by fr34kyn01535** [comment]
Yes i would add it directly to the forum,  currently thinking bout a good backend,  i guess github is the best idea

Am 31. März 2016 03:16:56 MESZ, schrieb Jamie Morgan <notifications@github.com>:

**Comment by fr34kyn01535** [comment]
#1007
