### ISSUE TITLE
getting disconnected and unable to rejoin after use /tp sometimes

### ISSUE THREAD

**Issue by sharkbound** [RocketMod/Rocket#598]
so after i tp to someone sometimes i will be disconnected and unturned will be glitched on mainmenu, then you have to reopen unturned and you cant rejoin after it usally. the only fix i have found is to delete the players player.dat file in their server player folder for the current map. also this happens from flying planes too

edit: after i changed the servers map this doesn't seem to happen anymore

edit 2: it has been  happening to others but not me yet as of the map change

**Comment by cartman-2000** [comment]
Something like this can also happen if you have mods on the server and you have a mod on your client that that has an item id that conflicts with the mods on the server. If the server side object is a barricade/structure and there's one of those objects placed in range of your player, and the client side item is some other type of item, like a wearable, you would get disconnected from the server when you connect to it.

**Comment by sharkbound** [comment]
probly is. thanks for letting me know about this. i will have to look into the mods on the server and see if they all all updated and such.
