### ISSUE TITLE
Cant spawn the new helis?

### ISSUE THREAD

**Issue by Algurt** [RocketMod/Rocket#600]
Not sure if this is rocket or not. Server is updated and rocket is updated to the most recent version. Butttt console says that id's 92-95 are not linked to an object. Bug? Or am I doing something wrong?

**Comment by Airwarfare** [comment]
You are probably doing something wrong make sure unturned is updated and rocket if you have to do a fresh install to test, ive been able to spawn all the new vehicles with no problem so idk.
