### ISSUE TITLE
Severe and Rapid Memory leak

### ISSUE THREAD

**Issue by bakermiles** [RocketMod/Rocket#606]
I run a private server and after the update 3.14.3.1 with Rocket 4.9.0.0 my server had the error "This server is running a modified assembly", i fixed this after re installing unturned and now my server launches and loads like normal but in anywhere from 5 - 15 seconds the server uses every possible amount of ram it can causing less than helpfull symptoms. My stronger PC was able to withstand the stress (barely) but the server had to be forcfully shutdown to regain control of it.

**Comment by bakermiles** [comment]
The memory leak occors when "Decay" is turned on. My settings were "Decay 0/0".

**Comment by cartman-2000** [comment]
This is most likely an Unturned bug, and not a bug with rocket.

I've had the same problem with the decay command, I currently have it soft disabled by setting it to some really high value like: Decay 1000000000/1000000000
