### ISSUE TITLE
Утечка памяти!

### ISSUE THREAD

**Issue by hivork006** [RocketMod/Rocket#607]
Здравствуйте
давно пользуюсь вашей платформой и не было косяков.
Но в последних обновах 771,772,773 я заметил пару вещей:

1-оч много требует ОЗУ целых 6 гб и парой 12 гб

2-раньше мог сделать два три сервера и они не крошились(путем воссоздание разных папок и т п),теперь же это невозможно и если запустить 2 сервера,компьютер чуть ли не чувствует себя как 2000 годах,когда технология была слабая,а требовании к играм(к примеру) очень высокие!

что делать???

**Comment by hivork006** [comment]
Почему закрыли без ответа?

**Comment by fr34kyn01535** [comment]
English pls

**Comment by hivork006** [comment]
Hello
long time I use your platform, and had no stocks.
But in the last update 771,772,773 I noticed a couple of things:

1-requires a lot of RAM as much as 6 GB and a pair of 12 GB

2-could make two or three servers and they crumble(by recreating different folders, etc.), but now it's impossible and if you run 2 servers,the computer almost feels like the 2000s,when technology was weak,and the demand for the games(for example) is very high!

what to do???

**Comment by fr34kyn01535** [comment]
Delete the map data

**Comment by hivork006** [comment]
![default](https://cloud.githubusercontent.com/assets/16685790/12975094/0eda1570-d0ca-11e5-925d-6590682c4b00.png
Also I have a problem

**Comment by hivork006** [comment]
![default](https://cloud.githubusercontent.com/assets/16685790/13020698/e9c15a90-d1e7-11e5-9fb0-788dd0e7f045.png)
What to do?
