### ISSUE TITLE
Vehicles Stuck in Air Floating

### ISSUE THREAD

**Issue by axiomaticTwist** [RocketMod/Rocket#608]
The staff on my Rocket server have run into the issue that whenever they spawn a vehicle, it gets stuck where it would spawn to fall above their head. This used to rarely happen, but now it happens no matter what. Anything that could help would be greatly appreciated. Already tried deleting Vehicles.dat in my server folder.

**Comment by falsechicken** [comment]
Have you tried it without Rocket?

**Comment by jorea143** [comment]
happened to my server too. I just updated the game and rocket again, and it was fix.
