### ISSUE TITLE
/save not saving playermade structures

### ISSUE THREAD

**Issue by WGSRangerWolf** [RocketMod/Rocket#611]
Doing /save and restarting removes the barricades/ structures that were placed. its happening to me. if it isnt happening to anyone else can someone tell me whats going on?

**Comment by elfl0rd** [comment]
Show your server config please.

**Comment by WGSRangerWolf** [comment]
The latest unturned update fixed it.

**Comment by elfl0rd** [comment]
Really?
`Successfully saved the game.
[World] Golden Dragon [Golden Dragon]: "которая быстро уменьшается)))"
Connecting: PlayerID: 76561198118418720 Name: YtKa(kря-kря) Character: SkRaG
Disconnecting: PlayerID: 76561198099547251 Name: Qoqz Character: Qoqz
Disconnecting: PlayerID: 76561198081387102 Name: Abyss Walker Character: Путник Бездны
Disconnecting: PlayerID: 76561198185958539 Name: Sergei Character: Sergei
Disconnecting: PlayerID: 76561198093377445 Name: VanaDoRaptor Character: Креветка
Disconnecting: PlayerID: 76561198095785401 Name: S.V.A.T.U.M Artem Character: S.V.A.T.U.M Cockston
Disconnecting: PlayerID: 76561198137342990 Name: S.V.A.T.U.M. Uprising Character: Uprising
Disconnecting: PlayerID: 76561198195359828 Name: ForestGame Character: ^_Jesus_^
Disconnecting: PlayerID: 76561198284652390 Name: ctacpanasenko Character: Stas_Panasenko
Disconnecting: PlayerID: 76561198026926871 Name: Golden Dragon Character: Golden Dragon
Disconnecting: PlayerID: 76561198144197471 Name: Silver Character: jopa
Disconnecting: PlayerID: 76561198097223473 Name: Saegusa Mayumi Character: Saegusa Mayumi
Disconnecting: PlayerID: 76561198083990360 Name: - FB - Nitro Character: - FB - Nitro
Disconnecting: PlayerID: 76561198258760353 Name: Lydik Character: Lydik
Disconnecting: PlayerID: 76561198282151448 Name: skornyakov.20 Character: skornyakov.20
Disconnecting: PlayerID: 76561198144798435 Name: Spudir_Min Character: Mr.Цыган
Disconnecting: PlayerID: 76561198262653409 Name: stas.tagunov.02 Character: stas_tag`
