### ISSUE TITLE
errors on server start (since 3.14.4.0 unturned update)

### ISSUE THREAD

**Issue by sharkbound** [RocketMod/Rocket#612]
this is what it spam for a few seconds after it says after it says successfully set the map stuff - https://gyazo.com/dda3b55727557a901f5217f8d590da3c

then after all the spam rocket loads. everything seems to work fine from hte brief testing i did with commands. 

not sure if this is a unturned or rocket bug/issue

ps: im rocket build #784

**Comment by cartman-2000** [comment]
This is a strange bug, I've seen this on some of my server's on one comp(all of them on one comp), but not any of the other comps I have server's on.

**Comment by sharkbound** [comment]
@cartman-2000  you know a fix for this?

**Comment by cartman-2000** [comment]
No, I'm not sure what's causing the error message pericely.

**Comment by fr34kyn01535** [comment]
This indeed looks like an unturned bug, please report it to nelson.
