### ISSUE TITLE
New CommandMapping feature doesn't work properly with multiple attribute based commands in a plugin.

### ISSUE THREAD

**Issue by cartman-2000** [RocketMod/Rocket#613]
The first command name entry it has for the class in the CommandMapping list will be used for any other attribute commands that are registered under the same class.

(By default, only one of the attribute commands in the class is added to the list, the first one set in the plugin. I added the second one, which is the name of the other attribute command in the class.)
```
    <CommandMapping Name="w" Enabled="true">ApokPT.RocketPlugins.WreckingBall</CommandMapping>
    <CommandMapping Name="wreck" Enabled="false">ApokPT.RocketPlugins.WreckingBall</CommandMapping>
```

(It only uses the first one it sees in the list when registering the commands.)
```
Registering ApokPT.RocketPlugins.WreckingBall (w)
Registering ApokPT.RocketPlugins.WreckingBall (w)
```

**Comment by fr34kyn01535** [comment]
This is also  breaking MessageAnnouncer, will investigate soon

**Comment by elfl0rd** [comment]
Thx you! I will wait fix.

**Comment by fr34kyn01535** [comment]
Fixed today
