### ISSUE TITLE
ошибка

### ISSUE THREAD

**Issue by hivork006** [RocketMod/Rocket#614]
https://cloud.githubusercontent.com/assets/16685790/13020698/e9c15a90-d1e7-11e5-9fb0-788dd0e7f045.png
what to do?

**Comment by sharkbound** [comment]
according to the error its threw a error when trying to get the players permissions. Is your permissions file done correctly?

**Comment by hivork006** [comment]
Why very often fail with the barricades starts to weigh a lot of 60 MB,the server requires almost 12 GB and how to remove it,the server works well and takes a maximum of 40 MB?!

**Comment by hivork006** [comment]
"sharkbound commented just now
according to the error its threw a error when trying to get the players permissions. Is your permissions file done correctly?"

it seems everything is configured properly

**Comment by sharkbound** [comment]
copy and paste all the text in your permission file and paste it all onto the xml validator - http://www.w3schools.com/xml/xml_validator.asp  . (use control + a  to select all text in the file then do control  + c to copy it, then control + v to paste  it onto the website).

**Comment by hivork006** [comment]
I inserted my test and found no errors..
"<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<DefaultGroup>default</DefaultGroup>
<Groups>
<Group>
<Id>default</Id>
<DisplayName>Guest</DisplayName>
<Color>white</Color>
<Members />
<Commands>
<Command>motd.default</Command>
<Command>kit.start</Command>
<Command>home</Command>
<Command>tpa</Command>
<Command>kits</Command>
<Command>stats</Command>
<Command>tpa.send</Command>
<Command>tpa.accept</Command>
<Command>balance</Command>
<Command>buy</Command>
<Command>sell</Command>
<Command>cost</Command>
</Commands>
</Group>
<Group>
<Id>vip</Id>
<DisplayName>VIP</DisplayName>
<Color>ffa500</Color>
<Members>
<Member />
</Members>
<Commands>
<Command>motd.vip</Command>
<Command>kit.vip</Command>
<Command>home</Command>
<Command>stats</Command>
<Command>tpa</Command>
<Command>kits</Command>
<Command>tpa.send</Command>
<Command>tpa.accept</Command>
<Command>balance</Command>
<Command>buy</Command>
<Command>sell</Command>
</Commands>
</Group>
<Group>
<Id>LevduR</Id>
<DisplayName>LevduR</DisplayName>
<Color>ffa500</Color>
<Members>
<Member />
</Members>
<Commands>
<Command>motd.sw</Command>
<Command>kit.sw </Command>
<Command>home</Command>
<Command>tpa</Command>
<Command>kits</Command>
<Command>stats</Command>
<Command>tpa.send</Command>
<Command>tpa.accept</Command>
<Command>balance</Command>
<Command>buy</Command>
<Command>sell</Command>
<Command>cost</Command>
<Command>deathmessage</Command>
</Commands>
</Group>
<Group>
<Id>vap</Id>
<DisplayName>VaP</DisplayName>
<Color>FF9900</Color>
<Members>
<Member>76561198016438091</Member>
</Members>
<Commands>
<Command>effect</Command>
<Command Cooldown="120">heal</Command>
<Command Cooldown="30">v</Command>
</Commands>
<ParentGroup>default</ParentGroup>
</Group>
</Groups>
</RocketPermissions>"
Установите приложение на смартфон и работайте офлайн
+
7 9xx xxxxxxx
Установить Переводчик
 
Ru
 Мобильная версияНовости сервисаРазработчикамПользовательское соглашениеО сервисеОбратн

**Comment by sharkbound** [comment]
is it still going on? if it is try reinstalling rocket

**Comment by hivork006** [comment]
Yes, it does

**Comment by fr34kyn01535** [comment]
This is not happening in vanilla, one of your plugins is the reason for this exceptions, remove them one by one and report the culprit to its author
