### ISSUE TITLE
unresolved problem with RAM

### ISSUE THREAD

**Issue by hivork006** [RocketMod/Rocket#615]
https://github.com/RocketMod/Rocket/issues/614

I tried to remove cleanly all the plugins and still nothing, still memory is taken about 12 GB

**Comment by hivork006** [comment]
I probably found the cause
the reason was "Rocket.en.translation".Please in future updates to speak of such adjustments,because constantly so watch out,you'll get tired 
thanks for the earlier

**Comment by yawbanana** [comment]
check your Structure or object data files in PEI's folder
