### ISSUE TITLE
I'm in despair

### ISSUE THREAD

**Issue by hivork006** [RocketMod/Rocket#616]
https://github.com/RocketMod/Rocket/issues/615
https://github.com/RocketMod/Rocket/issues/614
https://github.com/RocketMod/Rocket/issues/607

I run the server,sometimes they both work well and not conflict,but sometimes you need 12 GB of RAM,on one server or the other. There are a lot of stupid mistakes besides the fact that I showed # 614 problem Help...

**Comment by falsechicken** [comment]
Does this happen without Rocket installed? I somehow doubt that this is a Rocket problem. Its likely an Unturned bug.

**Comment by hivork006** [comment]
this happens when launching the rocket, and the server requires 12 GB of RAM

**Comment by fr34kyn01535** [comment]
IT IS an unturned bug, report to nelson, i can't fix it. To fix, delete all userdata & mapdata.
