### ISSUE TITLE
Unturned server issu

### ISSUE THREAD

**Issue by OTNAngel** [RocketMod/Rocket#619]
ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index - System.Collections.Generic.List`1[UnityEngine.Transform].get_Item (Int32 index)
SDG.Unturned.BarricadeManager.askBarricades (CSteamID steamID, Byte x, Byte y, UInt16 plant)
SDG.Unturned.BarricadeManager.askPlants (CSteamID steamID)
SDG.Unturned.VehicleManager.askVehicles (CSteamID steamID)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.Provider.receiveServer (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel)
SDG.Unturned.Provider.listenServer (Int32 channel)
SDG.Unturned.Provider.listen ()
SDG.Unturned.Provider.Update ()

Please help whats causing this problem it didn't start doing this till after the 3.14.5.0 update

**Comment by WGSRangerWolf** [comment]
IT looks like a issue with file corruption or nelson has messed something up.
