### ISSUE TITLE
Disconnect Reason (on Ban and Kick Events)  [Improvement] [Suggestion]

### ISSUE THREAD

**Issue by Lion4K** [RocketMod/Rocket#620]
Add a Reason output on the Kick and Ban events(at least), for plugins like "join leave messages" could hook into and announce when a player is banned or kick from the server. 

Like:

"Player X Left the server {1}" 

where {1} would be "Reason" (Banned, Kicked)

Link to discussion: https://dev.rocketmod.net/?rplugin=joinleave-messages#comment-7201

**Comment by LeeIzaZombie** [comment]
You could make a custom version of /ban and /kick (disable core commands) to do that

**Comment by Lion4K** [comment]
Exactly how?

**Comment by LeeIzaZombie** [comment]
Just make your custom /kick command and disable Unturned's kick in the Commands.config.xml file, making sure that your custom command is enabled.

**Comment by Lion4K** [comment]
You pretty much wrote the same thing again, I was going to ask "Exactly how?" again, then I decided to break this cycle.
I need details on the "Make your custom /kick command" I'm not a programmer, if I was I would submit changes to Rocket Code, or pretty much had figured that I would need my own command before, made it, and never submitted here.

**Comment by Sadusko** [comment]
Lee means 'player.Kick();'
Practice.

**Comment by Lion4K** [comment]
I have no idea whatsoever of what that could mean, i'm not a programmer, the only thing closest to a program that i can do are batch scripts. i have no idea of how to make anything in C# or any other thing

**Comment by Lion4K** [comment]
thats why i'm writing suggestions.

**Comment by Sadusko** [comment]
Maybe try to find a way to learn it? :+1:

**Comment by Lion4K** [comment]
Thanks!!
I appreciate!

**Comment by fr34kyn01535** [comment]
There is no unified kick solution yet, so there is no way to implement such a thing. The only way right now is to have kick /ban plugins emmiting such an event, or give your own kick and ban commands
