### ISSUE TITLE
Server lost your connection (firewall off / ports 27015/27016/27017 opened)

### ISSUE THREAD

**Issue by arjetiko** [RocketMod/Rocket#621]
Hi I have a problem with my server, people is disconnnected randomly (including me) with the message "server lost your connection". The server is 20 slots and never gets more than 14 playes. If the player 15 joins then one of the existing players will be disconnected. so never exceeds the 14 players. Im using last version of rocket and uturned. 
The plugins installed are DeathMessages, JoinLeaveMessages,Kits,MessageAnnouncer and TPA. No errors in cmd.
The firewall/av avast premier is OFF (because when is on no one can connects despite having added excepetions) and I opened the port 27015/27016/27017 in the TP-LINK panel (virtual servers and port triggering)
Thank you

**Comment by fr34kyn01535** [comment]
Unless you can provide log files with errors or proof of a memory leak it is either an issue with one of the plugins or your server is to weak to host specified amount of players, compare to vanilla or try disabling plugins, its not a rocket issue.
