### ISSUE TITLE
Arena Mode: Determining the winner of a round

### ISSUE THREAD

**Issue by dtmcode** [RocketMod/Rocket#622]
Just a quick question,

Is there currently a way to find the winner of an arena round? I want to make a simple plugin to determine the winner(s) and reward them using Uconomy. Not sure if Rocket has a way to find the winner of an arena match yet. If it doesn't, I think it would be a good thing to have.

**Comment by leonardosnt** [comment]
LevelManager.arenaState (private) ...
LevelManager.arenaPlayers (private) ...

From unturned src

```c#
for (int i = 0; i < LevelManager.arenaPlayers.Count; i++)
{
    ArenaPlayer arenaPlayer = LevelManager.arenaPlayers[i];
    if (!arenaPlayer.hasDied && arenaPlayer.steamPlayer != null && !(arenaPlayer.steamPlayer.player == null))
    {
        arenaPlayer.steamPlayer.player.sendStat(EPlayerStat.ARENA_WINS);
    }
}
```

**Comment by shadyx** [comment]
Thankyou @leonardosnt

**Comment by fr34kyn01535** [comment]
I will make them public soon
