### ISSUE TITLE
Uninstalling Rocket Mod.

### ISSUE THREAD

**Issue by HermyHerman** [RocketMod/Rocket#623]
Hello. So the other night, I downloaded Rocket Mod. I opened up Unturned and it was saying that I couldn't play servers that didn't have Rocket Mod and it only gave me 2 options. Go to the wiki for help or to close the game. How do I go back to as if I never downloaded Rocket Mod in the first place?

I deleted the Rocket folder in my server, but I can't join any server now, not even my own. How do I fix this? I'm assuming a get a clean Managed folder without the Rocket files but I don't know how I would go about doing that. Please help? 

Thanks for reading and have a nice day/night

**Comment by sharkbound** [comment]
right click unturned in your steam library > click propperties > click local files > click verify integrity of game cache. 

also close unturned before doing this
