### ISSUE TITLE
Why my server is not visible in the internet tab

### ISSUE THREAD

**Issue by sashapontwo** [RocketMod/Rocket#624]
Why my server is not visible in the Internet tab
If you can help, leave comment here with a decision

**Comment by Sadusko** [comment]
Check if your ports are being blocked by firewall.
If you port forwarded the ports "27015, 27016 and 27017" you should allow it on firewall as well.
Google "Allow port through firewall" if [this link](http://www.dummies.com/how-to/content/how-to-open-a-port-in-the-windows-7-firewall.html) does not work.

**Comment by fr34kyn01535** [comment]
It looks like also servers are not listed if more then 24 users, anyway - not a rocket bug
