### ISSUE TITLE
Dictionary error

### ISSUE THREAD

**Issue by persiafighter** [RocketMod/Rocket#627]
Everytime I try to use in-plugin commands (or rocket commands like, /i) I get a dictionary error and it doesn't complete the command.

[Example with Rocket "/i"](http://i.imgur.com/Mk8wQLY.png)
[Example with ZaupShop "/buy"](http://i.imgur.com/o7GLcbc.png)

And pretty much this error shows up in any command (that uses item names and item IDs) that is not from Vanilla Unturned itself. (Rocket Build: 798, 800 both have the error.)

**Comment by Ejraiel** [comment]
Same.

![ugh wtf](https://cloud.githubusercontent.com/assets/17344624/13539816/89b5a810-e207-11e5-826b-5e03e7d9e57a.png)

**Comment by cartman-2000** [comment]
I was able to fix it on my end, it's the references Rocket.Unturned and zaupshop uses, they're out of date, it works properly when it's compiled against the newest references.

**Comment by Aiden1234** [comment]
Same here
[capture](https://cloud.githubusercontent.com/assets/17657257/13542054/7184c71e-e2b4-11e5-8efb-843892a330e6.PNG)

**Comment by cartman-2000** [comment]
I uploaded a build of Rocket.Unturned and ZaupShop with the updated references. Built against build 801.

Note: Rocket.Unturned is in a windows only build in this, this build of Rocket.Unturned will most likely not work on a Linux server.
http://sc.cartman-2000.net/files/updates.7z

**Comment by persiafighter** [comment]
@cartman-2000 I had an outdated version of zaupshop, which caused the library error, but now I updated, and the error doesn't show up anymore, just for /i though... going to use uEssentials /item though... thanks for the help anyways :)

**Comment by cartman-2000** [comment]
The Rocket.Unturned one should work if you replaced the one in the managed folder properly.

**Comment by Ejraiel** [comment]
Still an issue on:
Unturned 3.14.7.2
Rocket 801

However, works with cartman-2000's Unturned.dll.

**Comment by fr34kyn01535** [comment]
Fixed since yesterday
