### ISSUE TITLE
RCON minimal="true" Removed at Startup

### ISSUE THREAD

**Issue by humangenome** [RocketMod/Rocket#628]
/Rocket/Rocket.config.xml

`<RocketSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<RCON Enabled="true" Minimal="true" Port="25446" Password="changeme"/>
<AutomaticShutdown Enabled="false" Interval="86400"/>
<WebConfigurations Enabled="false" Url=""/>
<WebPermissions Enabled="false" Url="" Interval="180"/>
<LanguageCode>en</LanguageCode>
<MaxFrames>60</MaxFrames>
</RocketSettings>`

Gets reverted to

`<RocketSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<RCON Enabled="true" Port="25446" Password="changeme"/>
<AutomaticShutdown Enabled="false" Interval="86400"/>
<WebConfigurations Enabled="false" Url=""/>
<WebPermissions Enabled="false" Url="" Interval="180"/>
<LanguageCode>en</LanguageCode>
<MaxFrames>60</MaxFrames>
</RocketSettings>`

Every time I stop the server, make this change, then start the server.

**Comment by fr34kyn01535** [comment]
There is no minimal setting anymore, thats the reason...

**Comment by humangenome** [comment]
Where is the documentation for the current version of RCON?
