### ISSUE TITLE
[Error] NullReferenceException & Failed to find a server

### ISSUE THREAD

**Issue by arjetiko** [RocketMod/Rocket#630]
Hi Im hosting my server in a paid hosting but sometimes some players or all players are kicked with the message "server lost your connection" and also all my friends cant join and they receive the message "failed to find a server". I dont know why some people can join and others not. 
I spoke with hosting support about this but they insist that the problem is rocketmod
Please help me

Im using last version of rocket/plugins and unturned.

Plugins installed: DeathMessages, JoinLeaveMessages, Kits, MessageAnnouncer, RocketMod_TPA, ZaupFeast.

Timeout: 5000 AutomaticSave: 300

Rocket.Unturned.config.xml:
<?xml version="1.0" encoding="utf-8"?>
<UnturnedSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<AutomaticSave Enabled="true" Interval="300" />
<CharacterNameValidation>true</CharacterNameValidation>
<CharacterNameValidationRule>([\x00-\xAA]|[\w_\ \.\+\-])+</CharacterNameValidationRule>
<LogSuspiciousPlayerMovement>true</LogSuspiciousPlayerMovement>
</UnturnedSettings>

Console error:
[Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.PlayerInput.askAck (CSteamID steamID, Int32 ack)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.SteamChannel.send (ESteamCall mode, ESteamPacket type, Int32 size, System.Byte[] packet)
SDG.Unturned.SteamChannel.send (System.String name, ESteamCall mode, ESteamPacket type, System.Object[] arguments)
SDG.Unturned.PlayerClothing.askWearVest (UInt16 id, Byte quality, System.Byte[] state, Boolean auto)
SDG.Unturned.PlayerInventory.tryAddItem (SDG.Unturned.Item item, Boolean auto)
SDG.Unturned.ItemManager.askTakeItem (CSteamID steamID, Byte x, Byte y, Vector3 point)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.Provider.receiveServer (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel)
SDG.Unturned.Provider.listenServer (Int32 channel)
SDG.Unturned.Provider.listen ()
SDG.Unturned.Provider.Update ()

**Comment by fr34kyn01535** [comment]
This seems Unturned related, please report to Nelson.
