### ISSUE TITLE
I dont understand this new rocket for unturned 3.14.7.2

### ISSUE THREAD

**Issue by ProPi1ot** [RocketMod/Rocket#632]
Sorry in advance, I'm a noob. But with the most recent rocket for unturned it added two new folders and one new .bat file. The folders it added are a steam folder and an unturned folder, and they are both empty. Also it created a update.bat file in the scripts folder, and when i launch the myfirstrocketserver.bat, in the cmd it says "warning: unturned closed or crashed, restarting" then it spams the cmd with "unturned.exe is not recognized as an internal or external command, operable program or batch file". This is very frustrating and ive tried everything to my knowledge (which is pretty much nothing XD). 

Edit: Also id like to note that i have been doing this private server thing for quite a while now and its always worked before on this computer so I just dont know anything about these new additions and it doesnt work like it used to. Try and be easy on me because i know nothing about coding or those sort of things and to me this is a struggle. XD

**Comment by onurdj12** [comment]
thank you for explaining the same problem i have perfectly xD

**Comment by fr34kyn01535** [comment]
The new script works different.
How it works:

1. Create a new folder "MyFirstServer"
2. Paste the whole contents of the Rocket zip file
3. Go into the scripts folder, run MyFirstServer.bat, the script will then install SteamCMD and Unturned into /MyFirstServer/Unturned and /MyFirstServer/Steam, wait for it to finish, then it will start Unturned
4. Stop Unturned again, configure & install plugins, done
5. To update, download latest zip, copy over all the files in MyFirstServer and run update.bat

**Comment by ProPi1ot** [comment]
Sorry but once again didn't work, it did the exact same thing as before. It created a steam and unturned folder with nothing in it. After the MyFirstRocketServer.bat ran, a steamcmd.zip showed up in the scrips folder for a second then disappeared. I even tried to manually install steamcmd and that didn't work either. I know this is probably frustrating for you with my dumb questions and answers so ill just stick to regular servers and just stay away from rocket lol it was fun while it lasted, thanks for the help though.

**Comment by fr34kyn01535** [comment]
Yes, thats the problem, you did exactly the same thing as before, and the script changed, please read my answer. And in addition it may be to say that you don't need those scripts, putting all the *.dll files into Unturned/Unturned_data/Managed/ works aswell.

**Comment by ProPi1ot** [comment]
Ok, I don't want to say your wrong or anything I just want to explain to you how i used to do it and how i tried it the new way with the new version (the way you explained it). So the old way i used to do it is i would copy the whole unturned game folder and paste it to my desktop, then i would rename the folder to "Unturned Rocket Server" I would then open the folder and go into unturned data, managed then i would pasted all of the contents from the rocket zip into the managed folder. Then i would go into scripts, run the myfirstrocketserver.bat and then shut it down once it is done loading, next i would go back to the unturned folder and go into servers, my first rocket server, change the server commands and add my plugins. 

Now since this no longer works I came here to ask for help, and when I got your help i tried it many times EXACTLY how YOU said it, and i can't get it to work. I created a new folder, named it "My first server" extracted the rocket zip into the new empty folder (named "my first server"), I go into the scrips folder and run "myfirstrocketserver.bat", the console pops up like usual and it has a nice new little loading thing at the top in like a yellow green that says "reading web response" then changed to  "writing web request" and finishes loading. Then a red error pops up then shuts down the console, I am unable to read the error because it shuts down so fast, after it shuts down, in the scrips folder I see a steamcmd.zip file that disappears after one second. I back out of the scripts folder and I see a steam folder and a unturned folder, they are both empty.

Now i don't know if what I just explained is wrong and i just didn't understand your instructions, or if I'm doing it right and its just not working at all, and I know that first part where I explained how i used to make a server was probably unnecessary. Also i am using the newest rocket 809.

**Comment by fr34kyn01535** [comment]
Well its possible there is an error in the script, i am not perfect ;D Do you have time for a Teamviewer session? Join the chat room on https://rocketmod.net/chat to coordinate a session...

**Comment by ProPi1ot** [comment]
About halfway through the reply i ran the myfirstserver.bat and by the time i sent it I checked it again. The steamcmd.zip stayed in the scripts folder, so I unzipped it and placed the steamcmd.exe in the empty steam folder and let it run, i now have a unturned folder with content. Im not sure how it worked, i did nothing different, maybe a bug? But i have to go to work right now and ill give you more details later and also let you know in a few hours if the server works. Thank you for the help.

**Comment by fr34kyn01535** [comment]
Mhm.... could be a issue expanding the zip file (https://github.com/RocketMod/Rocket.Unturned/blob/master/Rocket.Unturned/Scripts/Windows/update.bat#L17)... Just found out its not available on Windows 7 / 8, i will look into finding another solution...

**Comment by ProPi1ot** [comment]
Ah ok, I am using Windows 8.1

**Comment by fr34kyn01535** [comment]
No problem, i changed the script to use vbs to unpack, try latest version, either download Rocket or get it from here https://github.com/RocketMod/Rocket.Unturned/blob/master/Rocket.Unturned/Scripts/Windows/update.bat

**Comment by ProPi1ot** [comment]
Ok thank you I will try that when I get home

**Comment by ProPi1ot** [comment]
The new rocket version worked perfect, but doesn't the steamcmd.exe have to be moved into the steam folder and ran there? Because the steamcmd.exe is in the scrips folder

**Comment by fr34kyn01535** [comment]
The script should move it to the Steam folder..
