### ISSUE TITLE
The problem with the launch Rocket

### ISSUE THREAD

**Issue by hivork006** [RocketMod/Rocket#635]
I'm trying to enable the server by clicking on MyFirstRocketServer and you get an error(screenshot)
![default](https://cloud.githubusercontent.com/assets/16685790/13762561/d311b3ea-ea50-11e5-9649-da10119a8f5e.png)

**Comment by fr34kyn01535** [comment]
I don't speak russian nor read cyrillic, what does it say?

**Comment by hivork006** [comment]
unturned directory:"\" 
The system cannot find the path specified
unturned started 
"unturned.exe"not recognized as an internal or external command,operable program or batch file.
Warning: Unturned close of crashed,restarting

**Comment by Sadusko** [comment]
You will have to check if the path in the .bat file is equal to the path your Unturned.exe file is in.

You would think the error was pretty self explanatory..

**Comment by joveice** [comment]
Had this issue alot of the times when downloading the script from rocket.
Problem is that "unturned.exe" isent a command so it doesent do anything, What i did was edit it and add "Start" infront of unturned.exe and that should solve the issue.
