### ISSUE TITLE
/vanish improvements

### ISSUE THREAD

**Issue by Ejraiel** [RocketMod/Rocket#636]
**Prevent these completely:**
Zombie attraction.
Animal running.
_etc._

**Prevent these from being shown to other players:**
Sound.
Light.
Blood.
Bullet trails.
_etc._
##

**Comment by Ejraiel** [comment]
If it's not possible to hide effects, perhaps it's possible to make shots and other damage types (explosion, melee, etc) pass through the player and cause no hit effects?

**Comment by Theboys619** [comment]
I'm not sure the effects will work, but the zombie attraction, animal running, etc. Will work but I really don't know it might and might not. Although those are good ideas for /vanish.

**Comment by ElementalVenom** [comment]
Its all very possible, its just a matter of what rocket man actually wants to work on.

**Comment by fr34kyn01535** [comment]
@ElementalVenom the repo is public, feel free to work on it yourself and PR.
