### ISSUE TITLE
/god improvements

### ISSUE THREAD

**Issue by Ejraiel** [RocketMod/Rocket#637]
Serverside:
Prevent server from displaying any signs of actual damage (not signs of being hit) from player using /god, such as blood, broken bone sounds, etc.

Clientside:  Is it possible to prevent the player's client from receiving any sort of damage packet, without preventing them from seeing the shots / hits that would cause the damage?  If so, this could prevent flinching, vision changes, blood, bleeding, broken bones, etc.

**Comment by fr34kyn01535** [comment]
Nope..

**Comment by Ejraiel** [comment]
Not possible?

**Comment by falsechicken** [comment]
@Ejraiel Don't think so. Would require client side stuff.

**Comment by Ejraiel** [comment]
=\
