### ISSUE TITLE
Remember last command states.

### ISSUE THREAD

**Issue by Ejraiel** [RocketMod/Rocket#639]
Such as when a player uses /god, logs out, and logs back in -- they would still be in godmode on login.

**Comment by fr34kyn01535** [comment]
Thats a task of a plugin...

**Comment by Ejraiel** [comment]
Commands such as /god and /vanish are part of Rocket.

Dealing with commands from plugins is a separate issue.

Rocket should behave properly.

**Comment by fr34kyn01535** [comment]
Properly != How you want them to behave

**Comment by Ejraiel** [comment]
In this case, it is very =.

**Comment by falsechicken** [comment]
Yeah... This would also require some sort of storage backed right? To persist states between server restarts? Also @Ejraiel Rocket is a one man project so it would be @fr34kyn01535 implementing all of this... His reasoning is probably a combination of his time weighed against the usefulness of such a feature that could be done with a plug-in.

**Comment by Ejraiel** [comment]
Yeah, I get all that.

Programming details aside, my main issue here is the automatic closure with no comment.

Feels very "I don't care" to receive that kind of treatment.

Even one sentence would be great; to show the thinking / reasoning, and not just toss people aside.

Thank you very much for your input here.

**Comment by fr34kyn01535** [comment]
Hum, i really don't ;D
Customization is up to plugin developers, i am sure i gave developers all the tools they need to do do something like that ...
