### ISSUE TITLE
Players can't join - Modified Assembly

### ISSUE THREAD

**Issue by diamondpumpkin** [RocketMod/Rocket#642]
This error is quite annoying, anyone know how to fix it? I am at #820 of Rocket and unturned is obviously at the latest as well. Yet no one can join due to "Server is using a modified assembly."

Please help!

**Comment by Sadusko** [comment]
Download the latest Rocket version again. If the Rocket's Unturned version isn't compatible with the Unturned version it will give that message.

**Comment by diamondpumpkin** [comment]
Still fucking can't join.

**Comment by Sadusko** [comment]
Don't get too frustrated.

A few steps that might help you out:

- Verify Unturned files (In SteamCMD "app_update 304930 validate").

- Make a backup of your servers folder, and delete the whole Unturned files or create a new directory for the Unturned files, then download the Unturned files and make sure you forced the install directory to be to the directory that you made.

- Download the latest version of Rocket and install it.


Next time try not to get too frustrated.

> Still **fucking** can't join.

**Comment by diamondpumpkin** [comment]
Finally, thank you.

**Comment by Sadusko** [comment]
No problem. Next time stay calm :+1:
