### ISSUE TITLE
Players can't join - Modified assembly

### ISSUE THREAD

**Issue by diamondpumpkin** [RocketMod/Rocket#644]
Still happening, on the latest of everything and it's still not letting me join.

**Comment by diamondpumpkin** [comment]
What a dick.

**Comment by Sadusko** [comment]
What a dick? This is stupid because there are loads topics on this and loads of issues on this.

You have to wait until Rocket has made a new version. Takes about 10 to 30 minutes to make it work.

I would've closed this without saying anything as well tbh.
