### ISSUE TITLE
Rocket for Linux is broken

### ISSUE THREAD

**Issue by srmcgann** [RocketMod/Rocket#645]
After the most recent update, Rocket fails to work. Normally when launching the game server with start.sh, there is feedback from Rocket about registering commands & plugins, but now there is nothing. The game server runs, and clients can connect, but all Rocket commands are not working.

![image](http://cantelope.org/error.jpg)

This has happened before. Any advice would be great.

I made sure to copy the updated Rocket files (RocketLauncher.exe, & .dll's into their appropriate directories)

**Comment by Gigawiz** [comment]
I am having this issue as well. Script says "Steam: UP TO DATE", server runs, but commands (like /god) just display in the chatbox and do nothing.

**Comment by fr34kyn01535** [comment]
The libraries belong into Unturned_Headless_Data,i changed the readme accordingly.

**Comment by srmcgann** [comment]
Copying the .dll files into ~/unturned/Unturned_Headless_Data/Managed solved the problem!

Thank you!!!

**Comment by Sadusko** [comment]
Added this to the fixing issues page on the wiki for future requests.
