### ISSUE TITLE
Server won't start tryed trubbelshooting (Ubuntu Linux)

### ISSUE THREAD

**Issue by joveice** [RocketMod/Rocket#647]
Error can be found here http://pastebin.com/gR6ARawc
What is the problem here?
Got latest version of Unturned, Rocket and my selected plugins.

**Comment by fr34kyn01535** [comment]
Linux troubleshooting is something for the forum, not to be officially reported as bug to Rocket, unless proven to really not work on any machine at all or otherwise being Rockets fault

**Comment by joveice** [comment]
Ubuntu forum said this wasent a linux bug, and this was tested on 2 linux machines which it did not work on any of them.
If this is not a Linux error or a Rocket error what is it then? I'm unable to use this until there is a fix.
Note:
It was working until latest rocket build.

**Comment by fr34kyn01535** [comment]
Sure its no linux bug -.-'

IOException: Sharing violation on path Logs/Rocket.log
  at System.IO.File.Move (System.String sourceFileName, System.String destFileName) [0x00000] in <filename unknown>:0
  at Rocket.Core.Environment.Initialize () [0x00000] in <filename unknown>:0
  at Rocket.Core.R.Initialize () [0x00000] in <filename unknown>:0
  at Rocket.Core.R.Awake () [0x00000] in <filename unknown>:0

Looks like you already have a server running or something else blocks the access to Logs/Rocket.log, just delete that file and try again.

**Comment by joveice** [comment]
That doesent solve the issue
