### ISSUE TITLE
* permission

### ISSUE THREAD

**Issue by Doten** [RocketMod/Rocket#651]
Today, I join to my server and try to write /god. BUT it don't work (Plugin LPX and config file Permission). I try to change. * delete, add god. This plugin does not handle *. Then I try do add * to permission.config and don't work! WTF? When this bug can to fix? (My english bad, so try to read this rubbish)

**Comment by sharkbound** [comment]
no permission are working for me ether. im not using lpx but nothing is working. (everything was working before updating rocket to 3.14.11.3)

**Comment by Animosity23** [comment]
I am having the same problem. I have just made a server and now I can't play Unturned because of the Rocket plugins and files I added. Why?

**Comment by DubFriendsFriendlyFriend** [comment]
yep yep same problem for me

pls fix soon

**Comment by Doten** [comment]
I found fix! I delete plugin uEssentials 1.1.8.0 (replace old version 1.1.7.0) and bug has been fixed!
