### ISSUE TITLE
Won't let me join any server with rocket.

### ISSUE THREAD

**Issue by Xenoframe** [RocketMod/Rocket#652]
I made my own server and when I click on it to join, it takes me to the loading screen and the bar doesn't move at all. I've left this overnight also. Please help

**Comment by DubFriendsFriendlyFriend** [comment]
Did you let the server completely turn on? Cause if you join the server while Rocket is initiating, as soon as Rocket is finished initiating it takes you to the loading screen, and the bar doesn't move (I've made this mistake myself a couple of times and had to reopen my Unturned)

**Comment by fr34kyn01535** [comment]
Read the logs...
