### ISSUE TITLE
Permissions are borked

### ISSUE THREAD

**Issue by EqlipseD** [RocketMod/Rocket#655]
Everyone has access to commands they otherwise should not have. There is nothing wrong with my permissions file I updated it to reflect the new system for permissions since the most recent update. They are getting a "command_no_permissions" message sent to their chat but they can still use commands they should not have access to.

**Comment by leonardosnt** [comment]
I can confirm..

https://github.com/RocketMod/Rocket.Unturned/issues/21

**Comment by Daniil1288** [comment]
can confirm too

**Comment by WGSRangerWolf** [comment]
Can confirm too

**Comment by EqlipseD** [comment]
Is there anyway to get a hold of a previous version? Keeping my servers down all day is going to kill my player base.

**Comment by leonardosnt** [comment]
I have 841 https://www.dropbox.com/s/vt7i2iu0mubsb6a/Rocket.Unturned_841.zip?dl=0

**Comment by EqlipseD** [comment]
Is that 3.14.11.3?

**Comment by leonardosnt** [comment]
Np :D

**Comment by Daniil1288** [comment]
still no answer :(

**Comment by leonardosnt** [comment]
We need to wait fr34k fix it

**Comment by EqlipseD** [comment]
Can anyone confirm that the latest updates are fixed? I am to scared to try them myself.

**Comment by leonardosnt** [comment]
@EqlipseD I will try.....

**Comment by leonardosnt** [comment]
@EqlipseD Was fixed, but there a new issue #656
