### ISSUE TITLE
SAY command not working

### ISSUE THREAD

**Issue by FicHitA** [RocketMod/Rocket#659]
When i 1st execute the SAY command after starting the server it works, but if i try to use it again i receive the following error:

**FAILED TO FIND PARAMETERS IN FORMAT [TEXT]/[R]/[G]/[B].**

PD: Sorry by my bad English

**Comment by fr34kyn01535** [comment]
Well are u using a plugin that overwrites say?

**Comment by FicHitA** [comment]
You have a point... i didnt check that, i will do it tomorrow... it´s time to sleep now

Im using 4 plugins

1. uEssentials
2. DeathMessages
3. RocketMod_ItemRestriction
4. ZaupFeast

**Comment by cartman-2000** [comment]
With the change with the builtin commands getting loaded on the server, you now need to disable(set to false) the built in command in rockets commands file before you will be able to replace a built in command.

**Comment by fr34kyn01535** [comment]
I introduced priority on command mappings, unturned commands are added with "Low", regenerate the Commands.config.xml and unturned commands will be always overwritten in the future.
