### ISSUE TITLE
Plugin config files reload problem

### ISSUE THREAD

**Issue by cartman-2000** [RocketMod/Rocket#661]
Config files for plugins no longer reload when reloading a plugin in the current rocket versions, so to change something in the config file, you have to restart the server for it to take effect or stick in the config file.

**Comment by fr34kyn01535** [comment]
Does this still occur in the latest version? it seems to work for me

**Comment by cartman-2000** [comment]
I still have the issue on my server's.

**Comment by cartman-2000** [comment]
I've also noticed this when I start the server's too.

```
  System.TypeInitializationException: An exception was thrown by the type initializer for Mono.CSharp.CSharpCodeCompiler ---> System.IO.FileNotFoundException: Windows mono path not found: S:\mono\mono\mini\mono.exe
  at Mono.CSharp.CSharpCodeCompiler..cctor () [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
  at Microsoft.CSharp.CSharpCodeProvider.CreateCompiler () [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializer.GenerateSerializers (System.Xml.Serialization.GenerationBatch batch, System.CodeDom.Compiler.CompilerParameters cp) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializer.RunSerializerGeneration (System.Object obj) [0x00000] in <filename unknown>:0
```

**Comment by fr34kyn01535** [comment]
The Mono exception is not an issue, does this happen with every plugin? I just tested it with MessageAnnouncer and it works well...

**Comment by cartman-2000** [comment]
It happens when you try to reload a one plugin, like /rocket reload wreck, a full reload still works.

**Comment by cartman-2000** [comment]
It's still an issue in build 862. I got it to work on my side in single plugin reload by changing this line in rocket core to "configuration.Load(null, true);"
https://github.com/RocketMod/Rocket/commit/1d2dc3da25e5c76c050d389f0dda8fef30dfe7df#diff-ea650540014b39b4f394783fd297a1c8R34

**Comment by fr34kyn01535** [comment]
Refactored the method to not have the update parameter anymore, should work now
