### ISSUE TITLE
Rocket not reading code for permissions file

### ISSUE THREAD

**Issue by ncataldo** [RocketMod/Rocket#662]
I am trying to set up my server, and currently have the uEssentials plugin installed. Rocket acts like the whole system of rocket itself is not installed at all, with or without the plugin. My file is as follows:
```
<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Color>white</Color>
      <Members />
      <Commands>
        <Command>p</Command>
        <Command>compass</Command>
        <Command>rocket</Command>
        <Command>kits</Command>
        <Command>kit</Command>
        <Command>home</Command>
        <Command>reply</Command>
        <Command>vote</Command>
        <Command>tell</Command>
        <Command>warp</Command>
        <Command>warps</Command>
      </Commands>
    </Group>
    <Group>
      <Id>ADMIN</Id>
      <DisplayName>Admin</DisplayName>
      <Color>000FFF</Color>
      <Members>
        <Member>76561198081746545</Member>
        <Member>76561198099302940</Member>
      </Members>
      <Commands>
        <Command>home</Command>
        <Command>jump</Command>
        <Command>spawnvehicle</Command>
        <Command>boom</Command>
        <Command>tp</Command>
        <Command>respawnzombies</Command>
        <Command>respawnanimals</Command>
        <Command>reply</Command>
        <Command>clearinventory</Command>
        <Command>vote</Command>
        <Command>repairvehicle</Command>
        <Command>refuelvehicle</Command>
        <Command>experience</Command>
        <Command>maxskills</Command>
        <Command>repair</Command>
        <Command>sudo</Command>
        <Command>back</Command>
        <Command>essentials</Command>
        <Command>killzombies</Command>
        <Command>tell</Command>
        <Command>resetplayer</Command>
        <Command>ping</Command>
        <Command>poll</Command>
        <Command>kill</Command>
        <Command>freeze</Command>
        <Command>tpall</Command>
        <Command>kickall</Command>
        <Command>unfreeze</Command>
        <Command>spawnitem</Command>
        <Command>ascend</Command>
        <Command>descend</Command>
        <Command>clear</Command>
        <Command>item</Command>
        <Command>iteminfo</Command>
        <Command>itemfeatures</Command>
        <Command>vehiclefeatures</Command>
        <Command>spy</Command>
        <Command>suicide</Command>
        <Command>position</Command>
        <Command>online</Command>
        <Command>respawnitems</Command>
        <Command>respawnvehicles</Command>
        <Command>shutdown</Command>
        <Command>vehicle</Command>
        <Command>systemtime</Command>
        <Command>skill</Command>
        <Command>warp</Command>
        <Command>warps</Command>
        <Command>setwarp</Command>
        <Command>delwarp</Command>
        <Command>deletekit</Command>
        <Command>createkit</Command>
        <Command>dropkit</Command>
        <Command>kits</Command>
        <Command>kit</Command>
        <Command>editkit</Command>
      </Commands>
    </Group>
  </Groups>
</RocketPermissions>
```

**Comment by Daniil1288** [comment]
Change <Command> to <Permission>; </Command> to </Permission>; <Commands> to <Permissions> and, finally, </Commands> to <Permissions>.

**Comment by ncataldo** [comment]
@Daniil1288 Any chance you could highlight them in the code or change it for me? I'm not seeing what you mean. Sorry, I'm new to all this.

**Comment by Daniil1288** [comment]
oh wow, github's formatting... this was what I originally wrote:
`Change <Command> to <Permission>; </Command> to </Permission>; <Commands> to <Permissions> and, finally, </Commands> to <Permissions>.`

**Comment by ncataldo** [comment]
@Daniil1288 Well it turns out that didn't work. My file now looks like this:
``<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Color>white</Color>
      <Members />
      <Permissions>
        <Permission>p</Permission>
        <Permission>compass</Permission>
        <Permission>rocket</Permission>
        <Permission>kits</Permission>
        <Permission>kit</Permission>
        <Permission>home</Permission>
        <Permission>reply</Permission>
        <Permission>vote</Permission>
        <Permission>tell</Permission>
        <Permission>warp</Permission>
        <Permission>warps</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>ADMIN</Id>
      <DisplayName>Admin</DisplayName>
      <Color>000FFF</Color>
      <Members>
        <Member>76561198081746545</Member>
        <Member>76561198099302940</Member>
      </Members>
      <Permissions>
        <Permission>home</Permission>
        <Permission>jump</Permission>
        <Permission>spawnvehicle</Permission>
        <Permission>boom</Permission>
        <Permission>tp</Permission>
        <Permission>respawnzombies</Permission>
        <Permission>respawnanimals</Permission>
        <Permission>reply</Permission>
        <Permission>clearinventory</Permission>
        <Permission>vote</Permission>
        <Permission>repairvehicle</Permission>
        <Permission>refuelvehicle</Permission>
        <Permission>experience</Permission>
        <Permission>maxskills</Permission>
        <Permission>repair</Permission>
        <Permission>sudo</Permission>
        <Permission>back</Permission>
        <Permission>essentials</Permission>
        <Permission>killzombies</Permission>
        <Permission>tell</Permission>
        <Permission>resetplayer</Permission>
        <Permission>ping</Permission>
        <Permission>poll</Permission>
        <Permission>kill</Permission>
        <Permission>freeze</Permission>
        <Permission>tpall</Permission>
        <Permission>kickall</Permission>
        <Permission>unfreeze</Permission>
        <Permission>spawnitem</Permission>
        <Permission>ascend</Permission>
        <Permission>descend</Permission>
        <Permission>clear</Permission>
        <Permission>item</Permission>
        <Permission>iteminfo</Permission>
        <Permission>itemfeatures</Permission>
        <Permission>vehiclefeatures</Permission>
        <Permission>spy</Permission>
        <Permission>suicide</Permission>
        <Permission>position</Permission>
        <Permission>online</Permission>
        <Permission>respawnitems</Permission>
        <Permission>respawnvehicles</Permission>
        <Permission>shutdown</Permission>
        <Permission>vehicle</Permission>
        <Permission>systemtime</Permission>
        <Permission>skill</Permission>
        <Permission>warp</Permission>
        <Permission>warps</Permission>
        <Permission>setwarp</Permission>
        <Permission>delwarp</Permission>
        <Permission>deletekit</Permission>
        <Permission>createkit</Permission>
        <Permission>dropkit</Permission>
        <Permission>kits</Permission>
        <Permission>kit</Permission>
        <Permission>editkit</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>``

**Comment by Daniil1288** [comment]
yes, this should be right, though in my Permissions.config.xml:
```
      <Members>
        <Member />
      </Members>
```
instead of
`      <Members />`

**Comment by ncataldo** [comment]
@daniil1288 that wouldn't affect the permissions of the admin group though, would it? Because we still didn't have permissions when I joined. Do I have to somehow register or overwrite the stock commands versus the uEssientials commands? I also installed JoinLeaveMessages into my adding folder and edited my settings file and nothing changed.

**Comment by ncataldo** [comment]
@Daniil1288 just checked the server and it still doesnt work

**Comment by ncataldo** [comment]
Why was this closed? @fr34kyn01535

**Comment by fr34kyn01535** [comment]
> rocket acts like the whole system of rocket itself is not installed at all
This is not a bug of rocket, but you seem to not have installed rocket correctly. I can not replicate nor is this a proper bug report. We need logs to figure what your problem is, and this belongs into the forum - not the bugtracker.

**Comment by ncataldo** [comment]
Sorry man. I didn't install Rocket myself, but rather using gameservers.com's install button. Everything that should be there was. Just don't know why it's not working. I'll see what I can find and report back to see if it's the websites fault.
