### ISSUE TITLE
permission file regenerates a new file every time i restart server 

### ISSUE THREAD

**Issue by frylockxxx** [RocketMod/Rocket#664]
sometimes i can pase new one load up server but the second i restart the server its back to auto generated file

**Comment by frylockxxx** [comment]
im the third person with this problem that u have closed leave this open so we can talk

**Comment by fr34kyn01535** [comment]
If you want to talk, go and create a topic on the forum, i can not replicate nor i really understand "sometimes i can pase new one load up server"
