### ISSUE TITLE
Say Command

### ISSUE THREAD

**Issue by Theboys619** [RocketMod/Rocket#666]
I tried to use the say command in the console. With spaces and didn't work. It worked before (3 Updates ago). I also added /R/G/B after this screenshot was taken.
![screenshot from 2016-04-11 16 21 30](https://cloud.githubusercontent.com/assets/18406461/14441183/8be68042-0001-11e6-9145-3abcd33fbc57.png)

**Comment by Theboys619** [comment]
Only works in-game.
:(

**Comment by Daniil1288** [comment]
hm, thought that this was caused by a plugin that I installed...

I have this bug, too. Can confirm. I use broadcast instead, as a workaround.

**Comment by cartman-2000** [comment]
It works for me, you have to use quotes around the command now, as the the Unturned base commands are ran through rocket now.

so something like say "message here" should work, as long as you don't have forward slashes in it, as rocket still collapses the string into a slash separated string when sending to the internal command.

**Comment by Daniil1288** [comment]
@cartman-2000 didn't even think about that, thanks

**Comment by fr34kyn01535** [comment]
@cartman-2000 , not completely true: https://github.com/RocketMod/Rocket.Unturned/blob/master/Rocket.Unturned/Commands/UnturnedCommands.cs#L90
