### ISSUE TITLE
I Get "This server is using a modified assembly" every time i join my server

### ISSUE THREAD

**Issue by MisterSfm** [RocketMod/Rocket#667]
So as it says in the title
i get
"This server is using a modified assembly"
every time i join my unturned server that ive created
now.. i got nothing on my unturned i reinstalled it and still i get this problem every time i place my Rocket Files in the Managed folder (Yes i do have an separated folder for my Unturned and for my server) Can you help me?
By the way, When i don't have rocket in my server folder it works fine

**Comment by fr34kyn01535** [comment]
Reinstall
