### ISSUE TITLE
Invalid IL code exception after the unturned 3.14.13.0 update

### ISSUE THREAD

**Issue by cartman-2000** [RocketMod/Rocket#668]
I get this error in the console when ever anyone tries to use the chat on the server.
```
[4/15/2016 10:17:46 AM] [Error] InvalidProgramException: Invalid IL code in SDG.Unturned.ChatManager:process (SDG.Unturned.SteamPlayer,string): IL_0019: call      0x0a0004de

 - SDG.Unturned.ChatManager.askChat (CSteamID steamID, Byte mode, System.String text)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.Provider.receiveServer (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel)
SDG.Unturned.Provider.listenServer (Int32 channel)
SDG.Unturned.Provider.listen ()
SDG.Unturned.Provider.Update ()
```

**Comment by Daniil1288** [comment]
can confirm
[4/15/2016 8:25:32 PM] [Info] [World] Daniil1288 [Daniil1288]: "/god"
[4/15/2016 8:25:32 PM] [Error] InvalidProgramException: Invalid IL code in SDG.Unturned.ChatManager:process (SDG.Unturned.SteamPlayer,string): IL_0019: call      0x0a0004de

 - SDG.Unturned.ChatManager.askChat (CSteamID steamID, Byte mode, System.String text)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.Provider.receiveServer (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel)
SDG.Unturned.Provider.listenServer (Int32 channel)
SDG.Unturned.Provider.listen ()
SDG.Unturned.Provider.Update ()

**Comment by cartman-2000** [comment]
The chat on the server doesn't work at all with this.

**Comment by Daniil1288** [comment]
yup, nice bugfix, Nelson ;)

**Comment by weespin** [comment]
Uhhh, update it faster

**Comment by cartman-2000** [comment]
... Nelson changed it so that it also looks for / too in vanilla commands, which would break rocket.

In ILSpy.
```
// SDG.Unturned.ChatManager
public static bool process(SteamPlayer player, string text)
{
	string a = text.Substring(0, 1);
	if (a == "@" || a == "/")
	{
		if (player.isAdmin)
		{
			Commander.execute(player.playerID.steamID, text.Substring(1));
		}
		return false;
	}
	return true;
}
```

**Comment by fr34kyn01535** [comment]
public static bool process(SteamPlayer player, string text)
        {
            string str = text.Substring(0, 1);
            if (!(str == "@") && !(str == "/"))
            {
                return true;
            }
            if (Interface.CheckPermissions(player, text))
            {
                Commander.execute(player.playerID.steamID, text.Substring(1));
            }
            return false;
        }
fixed from my android ;D

**Comment by Daniil1288** [comment]
where do I change that,sorry?

**Comment by Daniil1288** [comment]
pls help :(
