### ISSUE TITLE
Does not creating the "Server" folder

### ISSUE THREAD

**Issue by BalazsAdorjan** [RocketMod/Rocket#671]
I uzipped the rocket folder to the right place, and when I start the "MyFirstServer" it's downloading only a "Steam" and an "Unturned" folder, and there is nothing in them. What could be the problem?

**Comment by 906532645** [comment]
The server information is all in the unturned folder u created, it will run from the new folder. Btw don't use my first rocket thing, it would be easier if u just do a normal way of setting up a server like what u do without rocket
