### ISSUE TITLE
Weird Mod In Creative Server

### ISSUE THREAD

**Issue by 906532645** [RocketMod/Rocket#672]
Hey guys, I am reporting a bug for me in my creative server, it's a creative server as I said and people are spawning weird mods like domination pack and rainbow cars, I double checked my server workshop folder it's just no there, now everyone is spawning ntw which is a extremely op gun to have, it's a weird bug so I hop anyone can help me

**Comment by dtmcode** [comment]
The rainbow car is actually in the core unturned, as for the other things, there is no possible way they can spawn them if they are not added to your workshop content.

**Comment by cartman-2000** [comment]
Nelson snuck in the flying car in this weeks update, it's not in the update notes. As for the other workshop mods, players can't spawn items from them if the server doesn't have the mods loaded on it.

**Comment by 906532645** [comment]
Hey guys I figure out what actually happened, I download some mods from unturned mods.net or some websites like that I forgot about it after. Now when I make server it's still there. I corrected this thank you guys
