### ISSUE TITLE
Unreliable command mapping

### ISSUE THREAD

**Issue by Freenex1911** [RocketMod/Rocket#673]
Command mapping is buggy sometimes, also "/rocket reload" overwrites command mapping.
##

**Comment by cartman-2000** [comment]
The way it works currently you have to restart the server at least once if you put a plugin on the server that overrides commands in an another one. And I personally wouldn't use a full reload on a server.

**Comment by fr34kyn01535** [comment]
It looks like changing entries generated by rocket also seem to be buggy, will investigate when coming home from vacation ~ may 8

**Comment by fr34kyn01535** [comment]
#1007
