### ISSUE TITLE
Error after updating v.3.14.16.0!

### ISSUE THREAD

**Issue by vanya890** [RocketMod/Rocket#687]
After updating v.3.14.16.0 the error occurred. She appears at the entrance of a person on the server!
Rocket.Unturned >> Exception in TriggerSend: System.InvalidCastException: Cannot cast from source type to destination type. at Rocket.Unturned.Events.UnturnedPlayerEvents.TriggerSend (SDG.Unturned.SteamPlayer s, System.String W, ESteamCall X, ESteamPacket l, System.Object[] R) [0x00000] in <filename unknown>:0
Rocket.Unturned >> Exception in TriggerSend: System.InvalidCastException: Cannot cast from source type to destination type.
![error](https://cloud.githubusercontent.com/assets/19227465/15078837/e416e0d4-13bd-11e6-848c-e3e1b547fc76.png)

**Comment by cartman-2000** [comment]
It doesn't really seem to cause an issue with how the server works at least, or by what I can see so far.

**Comment by Daniil1288** [comment]
hm, I don't have this error, it's gone after I reinstalled rocket...

**Comment by cartman-2000** [comment]
It was fixed in the latest build of rocket.

**Comment by cartman-2000** [comment]
Well it wasn't entirely fixed, vanish mode is broken with that error.

**Comment by Daniil1288** [comment]
@cartman-2000 oh... so that's what's been happening to my server.
shame on me, my rocket.log weights 16mb now, ahaha.

**Comment by Daniil1288** [comment]
@cartman-2000 oh, by the way... any plans on updating ReservedSlots? been using it for about 2 months now, but with the newest update it only works partially... (I set max slots to be 48, but after the server is full the slots aren't being added for some reason.)

**Comment by cartman-2000** [comment]
The vanish bug also has the effect of freezing the player in place server side after it's been disabled, until the player reconnects to the server.

**Comment by cartman-2000** [comment]
The plugin still works properly for me.
