### ISSUE TITLE
Assembly Error

### ISSUE THREAD

**Issue by realtinymonster** [RocketMod/Rocket#691]
When I try to connect to my server, Unturned says "This server is using a modified assembly."
![2016-05-07 17_29_41-unturned 3](https://cloud.githubusercontent.com/assets/3966582/15095199/5c427e68-1479-11e6-9576-46270e6a6985.png)

**Comment by cartman-2000** [comment]
This usually means that the map on your server either didn't get updated correctly(official map), or that the map has update on the workshop, if that's the case, you will need to update the map on the server too.
