### ISSUE TITLE
Crash on server shutdown

### ISSUE THREAD

**Issue by BeRtRoLlT** [RocketMod/Rocket#697]
My servers crashes sometimes on shutdown. This makes me not able to use auto shutdown and the restart script to make auto restarts, becasue the game is still opened and says "the game has crashed". I'm not sure if this is a rocket bug, but it could be.

This is one error message:
[output_log.txt](https://github.com/RocketMod/Rocket/files/263421/output_log.txt)

**Comment by fr34kyn01535** [comment]
Does it crash without having rocket installed?

**Comment by BeRtRoLlT** [comment]
I don't know I only run the servers with rocket.
