### ISSUE TITLE
Players bug

### ISSUE THREAD

**Issue by Uneska** [RocketMod/Rocket#698]
hello new update rocketmod and unturned.
all people who connect with server they are invisible.
Please fix this :P

**Comment by Brizio94** [comment]
Fix it please, everyone in every server is invisible!

**Comment by ZOD2015** [comment]
Confirmed rocket 887 has not fixed the issue.

**Comment by Uneska** [comment]
i think this bug fixed tomorrow >..> all servers is pve now with this bug xD mehhh

**Comment by Uneska** [comment]
AHHAHA new motion bug this game hahaha XDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD canser emotion !!

**Comment by jorea143** [comment]
I can see players now. 889, confirmed working.

**Comment by Uneska** [comment]
all now work thanks :P
