### ISSUE TITLE
Vanish doesn't work

### ISSUE THREAD

**Issue by unturnedplayer** [RocketMod/Rocket#699]
The build 547 fixed the console error but now vanish doesn't even work.  Rocket reports vanish mode is enabled but everyone can still see the player who used vanish.

**Comment by jorea143** [comment]
True. Was walking around checking my server while in vanish mode, when a player started talking to me. He can see me! lol

**Comment by cartman-2000** [comment]
I've uploaded a pull request for a fix for vanish.
https://github.com/RocketMod/Rocket.Unturned/pull/23/files
