### ISSUE TITLE
Ghost Player Images after Teleport usage

### ISSUE THREAD

**Issue by Azmo84** [RocketMod/Rocket#703]
After using TP/TPA to other Players there sometimes remain ghost images from the teleported players. Hitting the Ghost images also hits the players even if they are already gone away.

**Comment by cartman-2000** [comment]
Try restarting your client if you notice stuck players on the server.

**Comment by Azmo84** [comment]
Relog of the Player also solves the Problem. But it is very often on my Server. From 10 Tpa request there is nearly 1 with a ghost player.
