### ISSUE TITLE
Rocketmod Fehler

### ISSUE THREAD

**Issue by PrinceHecke** [RocketMod/Rocket#704]
So  wenn mann diesen mod auf denn server installiert und denn server neustartet dann kommt dieser fehler

Fehler: The file '/home/s1151716/Unturned/Unturned_Headless_Data/mainData' is corrupted! Remove it and launch unity again!
[Position out of bounds!]

(Filename: Line: 241)

**Comment by fr34kyn01535** [comment]
Not an issue.
