### ISSUE TITLE
/p does not issue a permission group

### ISSUE THREAD

**Issue by xionserver** [RocketMod/Rocket#707]
With the command /p now it is impossible to give rights of the game or the server console.Says "Invalid Argument". Only in the config. Please correct.

**Comment by Daniil1288** [comment]
https://github.com/RocketMod/Rocket.Unturned/commit/80334ada4bd3ef3c5ae830c36189667d2607f270

**Comment by fr34kyn01535** [comment]
I've changed it to be /p add|remove <player> <group> , see the wiki for more information...
