### ISSUE TITLE
Server Problem

### ISSUE THREAD

**Issue by MrCraZyFx** [RocketMod/Rocket#708]
My server is having a error in console : http://imgur.com/KRVCaQd
Someone please help me to fix this problem anybody cant join on the sv.

**Comment by Daniil1288** [comment]
not critical, not a real error. look through issues - somebody has asked this already

**Comment by MrCraZyFx** [comment]
Can you give me a link please? I need to solve this problem :(

**Comment by Daniil1288** [comment]
I'd like to solve this "error", too, but here's what freaky said:
https://github.com/RocketMod/Rocket/issues/684#issuecomment-218714229
:(

**Comment by Uneska** [comment]
hmm maybe instal mono ? 
http://www.mono-project.com/docs/getting-started/install/windows/

**Comment by Daniil1288** [comment]
@Uneska maybe, but I don't think that the error is of any importance... Who knows what'll happen if you actually get it to find mono.exe

**Comment by Uneska** [comment]
hmm change location mono with source rocket mod

**Comment by Uneska** [comment]
;p

**Comment by fr34kyn01535** [comment]
IT IS NOT an issue...
