### ISSUE TITLE
webpermissions

### ISSUE THREAD

**Issue by xionserver** [RocketMod/Rocket#711]
![image](https://cloud.githubusercontent.com/assets/19553925/15640535/1bbc40da-264a-11e6-9e41-df5eb7df9e94.png)
Tried to configure webpermissions , but eventually gives this error. Tell me how to configure these settings)

**Comment by westonhowe98** [comment]
When using web permissions you the webpage has to return ONLY the xml for the permissions. I tried going to the web page and it was removed. So I may be wrong here but I think it is returning all the extra things used to create the webpage. Try going to the link in your web browser. It should look similar to this https://gyazo.com/c7f132f9052a54192d95b2888ba62019 if it doesn't its not going to work.

**Comment by xionserver** [comment]
And on what web-site it is better to put these webpermission to all that worked was the ability to edit the game?
