### ISSUE TITLE
Command.cs Serializer not referencing required assembly 

### ISSUE THREAD

**Issue by Maldaris** [RocketMod/Rocket#712]
```
Error while compiling generated serializer
/tmp/69f4214e/1a84b0dd.cs(27,36) : error CS0012: The type `Rocket.Core.Assets.IDefaultable' is defined in an assembly that is not referenced. Consider adding a reference to assembly `Rocket.API, Version=2.6.1.0, Culture=neutral, PublicKeyToken=null'
(0,0) : error : /root/unturned/Unturned_Headless_Data/Managed/Rocket.Core.dll (Location of the symbol related to previous error)
```

Same issue as #681

**Comment by fr34kyn01535** [comment]
How do you know its Command.cs? and does it cause any issues?

**Comment by evanejk** [comment]
I think I might be having the same issue

**Comment by fr34kyn01535** [comment]
Is it affecting the server!?

**Comment by evanejk** [comment]
Yes fr34kyn01535 I can't join the server and the server isn't showing up in the master server list.

**Comment by Maldaris** [comment]
I know it's Command.cs because I did some digging in your source code with the stacktrace ` error : /root/unturned/Unturned_Headless_Data/Managed/Rocket.Core.dll (Location of the symbol related to previous error)`

Sounds like it's a compilation configuration issue.

**Comment by Maldaris** [comment]
And to further answer your question it is affecting the server, because I'm unable to connect to the server after this error appears, same as #713.

**Comment by evanejk** [comment]
I appreciate everybodys' help I know the Unturned server is basically broken it's amazing anybody can get it to work.

**Comment by Smile42RU** [comment]
Same trouble on our servers. I think need up priority of this issue that fix will be create ASAP.
Thank you.

**Comment by fr34kyn01535** [comment]
Can i have more Information on os and mono Version? I could not replicate that issue yet

Am 11. Juni 2016 16:55:37 MESZ, schrieb Anton Piskunov <notifications@github.com>:

**Comment by fr34kyn01535** [comment]
Do you have a Rocket.API.dll in the download package and have you pasted it into Managed?

**Comment by fr34kyn01535** [comment]
What script do you use?

**Comment by Smile42RU** [comment]
@fr34kyn01535 

root@ubuntu:/game# uname -a
Linux ubuntu 3.19.0-61-generic #69~14.04.1-Ubuntu SMP Thu Jun 9 09:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

root@ubuntu:/game# mono --version
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          supported, not enabled.
	GC:            sgen

**Comment by Smile42RU** [comment]
@fr34kyn01535 Yep, i have Rocket.API.dll in Managed folder (file last edit: Jun 12 05:34).

**Comment by fr34kyn01535** [comment]
How are you invoking the game? How are you installing it..

**Comment by fr34kyn01535** [comment]
Try newest version, i had the namespace of a Rocket.API class set to Rocket.Core.Assets, this could have caused issues with unity / mono

**Comment by evanejk** [comment]
The file '/home/unturned/Scripts/unturned/Unturned_Headless_Data/mainData' is c$
[Position out of bounds!]

(Filename:  Line: 241)

The file '/home/unturned/Scripts/unturned/Unturned_Headless_Data/mainData' is c$
[Position out of bounds!]

(Filename:  Line: 241)

The file '/home/unturned/Scripts/unturned/Unturned_Headless_Data/mainData' is c$
[Position out of bounds!]

**Comment by evanejk** [comment]
It just says this over and over

The file '/home/unturned/Scripts/unturned/Unturned_Headless_Data/mainData' is corrupted! Remove it and launch unity again!
[Position out of bounds!]

(Filename:  Line: 241)

The file '/home/unturned/Scripts/unturned/Unturned_Headless_Data/mainData' is corrupted! Remove it and launch unity again!
[Position out of bounds!]

(Filename:  Line: 241)

The file '/home/unturned/Scripts/unturned/Unturned_Headless_Data/mainData' is corrupted! Remove it and launch unity again!
[Position out of bounds!]

(Filename:  Line: 241)

The file '/home/unturned/Scripts/unturned/Unturned_Headless_Data/mainData' is corrupted! Remove it and launch unity again!
[Position out of bounds!]

(Filename:  Line: 241)

The file '/home/unturned/Scripts/unturned/Unturned_Headless_Data/mainData' is corrupted! Remove it and launch unity again!
[Position out of bounds!]

(Filename:  Line: 241)

The file '/home/unturned/Scripts/unturned/Unturned_Headless_Data/mainData' is corrupted! Remove it and launch unity again!
[Position out of bounds!]

(Filename:  Line: 241)

The file '/home/unturned/Scripts/unturned/Unturned_Headless_Data/mainData' is corrupted! Remove it and launch unity again!
[Position out of bounds!]

(Filename:  Line: 241)

The file '/home/unturned/Scripts/unturned/Unturned_Headless_Data/mainData' is corrupted! Remove it and launch unity again!
[Position out of bounds!]

(Filename:  Line: 241)

**Comment by evanejk** [comment]
I tried removing mainData but then it doesn't run at all.

**Comment by evanejk** [comment]
this error too

System.SystemException: Error running gmcs: Cannot find the specified file
  at Mono.CSharp.CSharpCodeCompiler.CompileFromFileBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames) [0x00000] in <filename unknown>:0
  at Mono.CSharp.CSharpCodeCompiler.CompileAssemblyFromFileBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames) [0x00000] in <filename unknown>:0
  at Mono.CSharp.CSharpCodeCompiler.CompileAssemblyFromFile (System.CodeDom.Compiler.CompilerParameters options, System.String fileName) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializer.GenerateSerializers (System.Xml.Serialization.GenerationBatch batch, System.CodeDom.Compiler.CompilerParameters cp) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializer.RunSerializerGeneration (System.Object obj) [0x00000] in <filename unknown>:0

**Comment by evanejk** [comment]
The game says Loading... for a long time and then The server lost your connection.

**Comment by fr34kyn01535** [comment]
Ignore all of those, they are not important, its probably something else, maybe networking or similar.

**Comment by evanejk** [comment]
If it was networking it would say "Attempting connection... [Try #1:10]" but it does not say that it actually trys to connect and fails.

**Comment by evanejk** [comment]
Franky would you like to take a look at the server? I can pm you the shh login.

**Comment by Diablosito33** [comment]
Hello, hello.

I reinsatalled the game, due the same error mentioned by OP.

Then  I download new rocket (it was the fix right?)
and still this: 
Error while compiling generated serializer
/tmp/1f9363fc/6717f3ff.cs(27,36) : error CS0012: The type `Rocket.Core.Assets.IDefaultable' is defined in an assembly that is not referenced. Consider adding a reference to assembly `Rocket.API, Version=2.6.2.0, Culture=neutral, PublicKeyToken=null'
(0,0) : error : /home/verdandi/servidor/unturned/Unturned_Headless_Data/Managed/Rocket.Core.dll (Location of the symbol related to previous error)

**Comment by Diablosito33** [comment]
I download the solution but seems I dont have the right dependencies to build this supossed fix.

**Comment by Diablosito33** [comment]
Managed to make the server appear on MasterList, 
but it doesn't run rocket, i tried **uninstall mono-gmc** and still the same error.

I fixed a previous error installing mono-gmc, 
but now I can't fix thsi error of **"assembly that is not referenced"**

Any tips?

**Comment by evanejk** [comment]
Thanks Diablo I'll try this later when I get home. Maybe steamcmd will decide to start working properly.
