### ISSUE TITLE
LINUX Unturned Rocket Server can't connect and not on master list

### ISSUE THREAD

**Issue by evanejk** [RocketMod/Rocket#713]
When trying to join "the server lost your connection"
and it's not showing up on the server list.

I've updated the steam app

I did "apt-get install mono-gmcs" to fix a couple errors and I still get this
Error while compiling generated serializer
/tmp/aa7c714/4c669103.cs(27,36) : error CS0012: The type `Rocket.Core.Assets.IDefaultable' is defined in an assembly that is not referenced. Consider adding a reference to assembly `Rocket.API, Version=2.6.1.0, Culture=neutral, PublicKeyToken=null'
(0,0) : error : /root/UNTURNED/unturned/Unturned_Headless_Data/Managed/Rocket.Core.dll (Location of the symbol related to previous error)

**Comment by fr34kyn01535** [comment]
https://github.com/RocketMod/Rocket/issues/712
