### ISSUE TITLE
New Version of Rocket kicks lot of Plugins

### ISSUE THREAD

**Issue by Azmo84** [RocketMod/Rocket#722]
TPA for Rocket 
DeathMessages
WreckingBall

----> not working here :/

**Comment by fr34kyn01535** [comment]
All plugins need a rebuild cause of a change that fixed https://github.com/RocketMod/Rocket/issues/712

**Comment by Daniil1288** [comment]
welp, not installing the newest rocket since I'm on windows, then o_o
