### ISSUE TITLE
Loading stops on 25%

### ISSUE THREAD

**Issue by OctoNezd** [RocketMod/Rocket#724]
`Error while compiling generated serializer
/tmp/36000ddb/1cedf545.cs(27,36) : error CS0012: The type `Rocket.API.IDefaultable' is defined in an assembly that is not referenced. Consider adding a reference to assembly `Rocket.API, Version=2.6.3.0, Culture=neutral, PublicKeyToken=null'
(0,0) : error : /home/steam/unturned/Scripts/unturned/Unturned_Headless_Data/Managed/Rocket.Core.dll (Location of the symbol related to previous error)
Loading level: 8%
Loading level: 16%
Loading level: 25%
`
Running Ubuntu Linux 14.04

**Comment by Diablosito33** [comment]
#723  join us ;)

**Comment by fr34kyn01535** [comment]
`Error while compiling generated serializer /tmp/36000ddb/1cedf545.cs(27,36) : error CS0012: The typeRocket.API.IDefaultable' is defined in an assembly that is not referenced. Consider adding a reference to assembly` is not an issue. I guess your savedata is broken.
