### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DAYNBOOM** [RocketMod/Rocket#725]
![screenshot_3](https://cloud.githubusercontent.com/assets/19998359/16157273/872893e4-34c0-11e6-942d-624a33f0ba2f.png)

**Comment by Diablosito33** [comment]
Plugin error.
I guess you must try to backup that plugin and its configs, 
then re-install plugin from zero and check if it runs again normally,
then I guess you can re-upload the configs.

**Comment by cartman-2000** [comment]
This is similar but not entirely the same as the other report, this is an error to a specific plugin due to the update to Unturned, not Rocket. The field that this plugin is trying to access is private in the newest unturned, this plugin would have to be updated to use isSubmerged instead.

**Comment by falsechicken** [comment]
I think @cartman-2000 answer is sufficient and sounds correct. Closing issue.
