### ISSUE TITLE
Error in new update

### ISSUE THREAD

**Issue by vanya890** [RocketMod/Rocket#726]
![screenshot_1](https://cloud.githubusercontent.com/assets/19227465/16157351/d623cd06-34c0-11e6-89ae-5eec2c39298e.png)

**Comment by Diablosito33** [comment]
#725 it is just plugin error, read what I told on referenced issue.
dont forget - backup, always!

**Comment by cartman-2000** [comment]
The past few changes to rocket broke most of the plugins, you will have to go through and update most of them.
