### ISSUE TITLE
cannot download the stable version of rocket

### ISSUE THREAD

**Issue by noammiz007** [RocketMod/Rocket#729]
hello, i cant download the stable version of rocket. is saying me error so i cant run my server. even with beta. and i can download beta

**Comment by Diablosito33** [comment]
I'm not sure if you got an answer,
just want to tell that I couldn't download on MicrosoftEdge (windows 10)...
I can use download buttons normally with chrome (even on windows 10),
but I still can on MicrosoftEdge.
