### ISSUE TITLE
Download button Unturned not working.

### ISSUE THREAD

**Issue by Diablosito33** [RocketMod/Rocket#730]
Just want to tell that I couldn't download Rocket mod for Unturned.
Tthis: https://rocketmod.net/get-rocket
**on MicrosoftEdge (windows 10)...**

I can use download buttons normally with chrome (even on windows 10),
but I can't on MicrosoftEdge.

Like this: #729 

Sorry if wrong place to report,
but I am new with this stuff.

**Comment by fr34kyn01535** [comment]
I know, i already wasted hours fixing it on Internet Explorer, Microsoft should pay me if they expect me to make it work in their browser, it works on any other browser.
