### ISSUE TITLE
Error when players join/disconnect

### ISSUE THREAD

**Issue by persiafighter** [RocketMod/Rocket#733]
Version: 4.9.7.0
Build: Latest (#942)
Problem: Everytime a new player joins, the following error is dumped into the console:
![capture](https://cloud.githubusercontent.com/assets/17557714/16171221/dda9a272-3569-11e6-88f6-9c2288376146.PNG)
Could be an error from something else, but I am not sure. It started happening ever since the 4.9.7.0 version of rocket came out. (For me at least)

**Comment by sharkbound** [comment]
looks to me like you need to update rocket

**Comment by persiafighter** [comment]
@sharkbound The problem is that rocket ALREADY is updated (LATEST AVAILABLE BUILD: 942, BUILD USED IN SERVER: 942), which is WHY I have posted this ISSUE.

**Comment by sharkbound** [comment]
oh i see. well hopefully it will get fixed then

**Comment by sharkbound** [comment]
but sometimes reseting the placed stuff fixes this. well it did for me at one point a least

**Comment by cartman-2000** [comment]
It's most likely an outdated plugin that is causing that, the last few updates to rocket required that nearly all the plugins be recompiled against the newer rocket lib's.

**Comment by persiafighter** [comment]
@cartman-2000 Every single plugin that is currently used in the server is up to date in it's latest version. Any outdated plugins were completely removed from the server. However... I STILL get the error when a player joins. Also, ( @sharkbound ) the error is happening in an ARENA server, so removing placed stuff is impossible, because there is nothing that can be and will be placed. I will try a full re-install of the server now, and see if that fixes the problem, or if it's the API of Rocket that is bugged.

**Comment by falsechicken** [comment]
How do you know if the plugins you use are outdated? The developers need to update their plugins. So of they where not changed in the last few days then the devs need to do that.

**Comment by falsechicken** [comment]
Any plugins that have not been touched/updated on the site since like three daya ago are "outdated".

**Comment by falsechicken** [comment]
@persiafighter that error is happening because you have a plugin that is trying to load a type that no longer exists in the latest rocket. Aka an outdated plugin...
