### ISSUE TITLE
Rocket loaded, but no Plugins are working

### ISSUE THREAD

**Issue by TruMBMikMik** [RocketMod/Rocket#735]
Hello,

In the last patch of Unturned all Plugins i downloaded or created myself worked perfect, but after this patch yesterday no plugin is working anymore.

I hope you can help me :+1: 

-Mik-

**Comment by falsechicken** [comment]
All plug-ins need to be updated. The developers of the plug-ins need to do this.

**Comment by TruMBMikMik** [comment]
I made a plugin for my own server and i dont know how to update this plugin?
Do you have any suggestions for me?

**Comment by falsechicken** [comment]
Simply get the latest rocket files and rebuild. Nothing else should be needed.

**Comment by TruMBMikMik** [comment]
I tried this, but nothing happend :/

**Comment by falsechicken** [comment]
Did you replace your rocket libraries in your project with the latest ones? Then clean and rebuild the solution?

**Comment by TruMBMikMik** [comment]
Okay Thailand you for your fast Solution, i will Try this tomorrow :)

**Comment by TruMBMikMik** [comment]
Hello,
This plugin wont work, I already replaced the rocket libraries and cleaned and rebuild it, but nothing helped.
In the last patch last week in Unturned my plugin worked great but now it wont work anymore.
Please help me :/
![rocket error](https://cloud.githubusercontent.com/assets/20017147/16176439/b1843030-360f-11e6-860e-e19c2efdfd02.PNG)

**Comment by falsechicken** [comment]
Kits like fr34kyn01535's kits? I know those are updated. Are you sure the plugins are the latest versions? Idk about colortext.

**Comment by TruMBMikMik** [comment]
Yes this kit is the plugin created by fr34kyn01535 and colortext is my own plugin and i cant update this plugin

**Comment by TruMBMikMik** [comment]
Kits is working now but like i said i dont know how to update my plugin?
and all of your solutions wont work :/

**Comment by falsechicken** [comment]
I do not know why its not working. If your references are using the latest ones from the latest rocket zip file and you replace the ones your project is using it should work. It would be the same process fr34kyn01535 used to update his.

**Comment by TruMBMikMik** [comment]
which rocket zip file?

**Comment by falsechicken** [comment]
The one you get when you download rocket... you would have had to have done this to develop a plugin in the first place.

**Comment by TruMBMikMik** [comment]
I use visual studio 15 to develop a plugin and i downloaded this rocket.unturned file out of nUGet or something and last update this plugin worked, i dont know why it isnt working too

**Comment by falsechicken** [comment]
Oh! Sorry. I didn't know you where using NuGet. Fr34kyn01535 might not have updated the package... Ill try and get a hold of him and see if he did and let you know.

**Comment by TruMBMikMik** [comment]
okay thank you, but do are there some other chances to update my plugin?

**Comment by falsechicken** [comment]
Can you try telling NuGet to check for package updates? Try that first. If not then you can make a total copy of your solution folder, remove the NuGet packages, then add new references to the .dll files in the Rocket zip.

**Comment by TruMBMikMik** [comment]
How can i tell NuGet to check for updates?

Yes i could try this but which references should i add?

**Comment by falsechicken** [comment]
Idk how to do it with Visual Studio. I use MonoDevelop. You should be able to do it by right clicking on your solution in visual studio somewhere. And you would add all the .dll files from the rocket zip file. Using the assembly browser in the add references window.

**Comment by TruMBMikMik** [comment]
Okay i will try this, thank you for your solutions :3

**Comment by TruMBMikMik** [comment]
Ok i added Assembly csharp , Rocket. api, core, Unturned and now i got 50 error messages telling me that the Name Translate and UnityEngine does not exist in the current context

**Comment by falsechicken** [comment]
You also need to add the UnityEngine and AssemblyCSharp dlls from unturned.

**Comment by TruMBMikMik** [comment]
Omg, it worked Thank you very much, you helped me alot :+1: :)

**Comment by falsechicken** [comment]
No problem. Repeat that process, replacing the rocket dlls and unturned dlls every time there is a rocket and unturned update to keep your plugin up to date.

**Comment by TruMBMikMik** [comment]
Okay i will do that :)
