### ISSUE TITLE
Server crash after anycommand.

### ISSUE THREAD

**Issue by jeepingviini** [RocketMod/Rocket#736]
My unturned server crashed after anycommand. I remove all plugins didnt help. Is this known issue or is it just for me?

**Comment by fr34kyn01535** [comment]
Need more info like logs or stuff, does it work vanilla?

**Comment by jeepingviini** [comment]
yes seems to work fine on vanilla.

**Comment by fr34kyn01535** [comment]
Please, provider more logs, "the server crashes" is not a bugreport
