### ISSUE TITLE
Error that deletes permissions!

### ISSUE THREAD

**Issue by luiscorreia06** [RocketMod/Rocket#742]
Hey Guys! My server was running fine, but when i tryed to change permissions of TPA and i run my server, it appears this error and deletes (Wipes, reload back) my permissions file.
I don't know what it is but i let you see the error!
Thanks!

System.TypeInitializationException: An exception was thrown by the type initiali
zer for Mono.CSharp.CSharpCodeCompiler ---> System.IO.FileNotFoundException: Win
dows mono path not found: C:\Users\luis\mono\mono\mini\mono.exe
  at Mono.CSharp.CSharpCodeCompiler..cctor () [0x00000] in <filename unknown>:0

  --- End of inner exception stack trace ---
  at Microsoft.CSharp.CSharpCodeProvider.CreateCompiler () [0x00000] in <filenam
e unknown>:0
  at System.Xml.Serialization.XmlSerializer.GenerateSerializers (System.Xml.Seri
alization.GenerationBatch batch, System.CodeDom.Compiler.CompilerParameters cp)
[0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializer.RunSerializerGeneration (System.Obje
ct obj) [0x00000] in <filename unknown>:0

**Comment by luiscorreia06** [comment]
Pls help!

**Comment by luiscorreia06** [comment]
HEY GUYS, I FUGURED IT OUT!!!

I WAS MAKING THAT BAD, RECENTLY THE TPA AND ROCKET CHANGED, SO INSTEAD OF

<Command>tpa.send</Command>
<Command>tpa.accept</Command>

IS

<Permission Cooldown="0">tpa.send</Permission>
<Permission Cooldown="0">tpa.accept</Permission>

THIS ADDS A PERMISSION. NOT COMMAND. 
ROCKET AND TPA CHANGED THAT WAS THE PROBLEM, I'LL TRY TO POST A TUTORIAL ON YOUTUBE!

Btw, Thanks!
:D

**Comment by fr34kyn01535** [comment]
This is not an error and does not cause the issue you mention

**Comment by luiscorreia06** [comment]
Yeah, I already figured it out! http://pastebin.com/y4YQBj2E

Bit thanks anyway!

**Comment by luiscorreia06** [comment]
But*

**Comment by luiscorreia06** [comment]
In YouTube tutorials theyre wrong! I was following them and splashed to error (All of them)  Check my pastebin for more! :)

**Comment by luiscorreia06** [comment]
Wow you very nice...

**Comment by Daniil1288** [comment]
@luiscorreia06, yup, don't mind him, he likes to keep his "issues" count as little as possible

**Comment by fr34kyn01535** [comment]
@Daniil1288
Firstly this issue is not a rocket bug tho this is the wrong spot to get help. Additionally OP seems to have fixed the issue.

**Comment by luiscorreia06** [comment]
Did you see my pther comment? I already fixed him, http://pastebin.com/y4YQBj2E
Look there, i'll post a video on YouTube to other people can see how to do it now.

**Comment by Daniil1288** [comment]
@fr34kyn01535, well, he seemed to be pissed (at least to me) because you closed his issue, and I wanted to calm him down a bit :) don't like seeing random people sad
