### ISSUE TITLE
Unturned 3.16.6.0 and how rocket labeled it as 3.16.6.1

### ISSUE THREAD

**Issue by Jacobwitt** [RocketMod/Rocket#743]
When I updated my Unturned server to the latest version of rocket, nobody would connect.
Then I took a little look arround the logs and noticed one thing.
It labeled the Unturned version as **3.15.6.1** even though the latest release was _3.15.6.0!_
Now is that not an that an issue.
Chop chop Rocket Developers.
People are **PISSED** that they cant get on my server.
All it says when people try to connect is _"This server is running a different version of unturned"_.
https://gyazo.com/f6878ec9967773b5b9463bd419aadd5f

**Comment by Jacobwitt** [comment]
Resolved. nvm.

**Comment by Daniil1288** [comment]
"Now is that not an that an issue."
unique grammar, you have! :D

**Comment by Jacobwitt** [comment]
lol just seeing this now hehe

**Comment by Daniil1288** [comment]
lol when'd I write that
