### ISSUE TITLE
Commands are registered but ingame it says not found

### ISSUE THREAD

**Issue by Trojaner25** [RocketMod/Rocket#744]
Affected plugin: https://github.com/Trojaner25/Rocket-Safezone

As you can see here:
http://puu.sh/pFLQA/110422e1a3.png

The commands were succesfully registered.

But ingame, I get the "Command not found" message.

This happens on /spos1 and /spos2 but not on /coords for example

(Seems like the numbers are causing it)
Edit: yes, commands with numbers in them are causing this. E.g. /command1, /spos1, /spos2, etc...
I fixed it on my plugin by renaming the commands to something without numbers.

**Comment by fr34kyn01535** [comment]
Send me the contents of your commandmapping please

**Comment by Trojaner25** [comment]
The AGPLv3 is a compatible license to the GPLv2.

**Comment by fr34kyn01535** [comment]
Have you tried it with the normal getter syntax, it looks like you just changed the syntax when this broke..

**Comment by Trojaner25** [comment]
It didnt get broken with that commit, it was broken before too.

**Comment by Willie30F** [comment]
Its a bug with that plugin, i am using this one too, you have to use /rpos1 and /rpos2
For me this worked perfect :+1: sorry for my bad english

**Comment by Trojaner25** [comment]
dude I made that plugin. I know about that bug thats why I have reported this...

**Comment by fr34kyn01535** [comment]
Will be fixed in the rework
