### ISSUE TITLE
server console

### ISSUE THREAD

**Issue by SeNSeY23** [RocketMod/Rocket#745]
how to change the encoding of the console from cp866 to UTF-8??

**Comment by cartman-2000** [comment]
You can't do that successfully in windows as far as I know, I've tried to do this once before, and the server will just freeze when it displays a unicode symbol. The basic Windows cmd console doesn't really support unicode at all, powershell does to some degree, but that isn't used in the server when it runs.

**Comment by Daniil1288** [comment]
@cartman-2000 so could (in theory) nelson rewrite the server to support powershell?...

**Comment by fr34kyn01535** [comment]
No. I could change the output of the output stream of the application but you would have to write a wrapper script for powershell. This is a windows limitation so i won't change it.
