### ISSUE TITLE
Rocket permissions and commands will fail completly when the Permissions.xml cant be parsed

### ISSUE THREAD

**Issue by Trojaner25** [RocketMod/Rocket#748]
So someone asked me yesterday for help with his rocket server, because no command was working anymore. Doesn't matter which group, admin or not admin, vanilla or rocket command etc, just no output. I looked at the log file, and it was full with exceptions from the Rocket permissions namespace, because of a single XML parse exception at the Permissions.xml.

My suggestion is to backup the permissions file and regenerate it automatically when it fails to load, or show mulitple big red warnings that the permissions file is corrupted. Or maybe just load the default permissions and dont touch the file at all.

**Comment by fr34kyn01535** [comment]
All those actions make people wonder why they loose their permission, don't know if that's such a good idea.  If you read the error carefully you can figure what file is broken, and what line the xml is malformed.

**Comment by SolarSupremacy** [comment]
Personally, I believe this isn't an issue we should be too worried about because, as @fr34kyn01535 said above, it's an easy fix on our end and would likely take quite a bit of work to work-around.

**Comment by fr34kyn01535** [comment]
There is not mutch work to accomplish it, i am just worried that replacing it with the default file is not what people expect to happen. And just using the default config would be even more confusing.

**Comment by cartman-2000** [comment]
You could format a warning message for failed permissions lookups from a malformed permissions xml, and if you can catch the part of the original exception that details where the syntax error is in the xml you could also print that into the warning message.

You'd still need to restart the server after fixing the permissions file though.
