### ISSUE TITLE
Tons of Null Reference Exceptions

### ISSUE THREAD

**Issue by SolarSupremacy** [RocketMod/Rocket#749]
At random times, I'll get tons of console spam of Null Reference Exceptions. Here's one of my server logs that.. exploded.
[Rocket.1467036163.zip](https://github.com/RocketMod/Rocket/files/336190/Rocket.1467036163.zip)

**Comment by cartman-2000** [comment]
Have you tried to reset/deleting the player's character files? Those may have become corrupted in some way.

**Comment by SolarSupremacy** [comment]
I have not tried it, but at the moment I'm less worried about the server getting screwed up and instead designing a (hopefully) <$400 server PC because the computer the server was being hosted on? Lets just say it took me three days to successfully put Windows 10 on it because Vista was simply too old. You can safely assume the stats of the OTHER parts in that case as well.

**Comment by Daniil1288** [comment]
> took me three days to successfully put Windows 10
Shoulda installed win7... There was that one issue with the server's console on win10, but I forgot what it was. I think it was that clicking anywhere in the console will freeze the server, not too sure, though. On the bright side, you can do ctrl+v there now!

**Comment by cartman-2000** [comment]
That quick select feature can be disabled, so clicking in the console window doesn't freeze the server. Although select mode will freeze the server on pretty much any version of windows that I know of.

**Comment by fr34kyn01535** [comment]
@Daniil1288 there is NO issue with Windows 10.
OP: https://github.com/RocketMod/Rocket/wiki/Fixing-Issues
