### ISSUE TITLE
AsyncTCPSocket Created/Destroyed

### ISSUE THREAD

**Issue by SolarSupremacy** [RocketMod/Rocket#750]
I've put so many hours into researching this one...

I don't know if it is something you can fix/improve on your end, but if it is, please do. it plagues almost every server as far as I can tell and it kicks people at random. Sometimes it even drags the whole server down with it.

**Comment by fr34kyn01535** [comment]
Its an unturned bug and probably happening because heavy load on the server

**Comment by Daniil1288** [comment]
I heard somewhere that that is just debug info when the server is under heavy load... Not sure why Nelson left it there.
