### ISSUE TITLE
Server crashing, "You are missing a custom vehicle asset that this server is using."

### ISSUE THREAD

**Issue by SolarSupremacy** [RocketMod/Rocket#751]
No idea what causes this crash, had to setup batch files to restart when this happens. Everyone gets kicked with the error message:

"You are missing a custom vehicle asset that this server is using."

I thought it might have been due to the addition of tanks, but I'm not sure.

Also, side note, as you see I've been posting a bunch of error logs? If you want to contact me for help in testing, reproducing these errors, or getting more information about them from my end, you can contact me via my Steam: "SolarSupremacy"

**Comment by Trojaner25** [comment]
Are you using any workshop items?

I guess you installed a workshop vehicle which has been deleted

**Comment by SolarSupremacy** [comment]
No workshop content, I'm against that stuff. I've heard the issue has been happening to other people on other servers as well, so I'm not sure.

When the error happens, it's not just me to disconnects. It happens when the entire servers crashes and boots everyone off.

**Comment by fr34kyn01535** [comment]
You are missing a custom vehicle asset that this server is using.

**Comment by KubGamingYT** [comment]
RocketMod has an issue with it most likely. I can't join a server with rocket mod on it.
