### ISSUE TITLE
UnturnedPlayer.CSteamID can sometimes throw a NullReferenceException

### ISSUE THREAD

**Issue by Trojaner25** [RocketMod/Rocket#754]
As you can see here: https://github.com/Trojaner25/Rocket-Safezone/issues/20 , a NullReferenceException is thrown in some cases.

> NullReferenceException: Object reference not set to an instance of an object - Rocket.Unturned.Player.UnturnedPlayer.get_CSteamID ()
##

**Comment by fr34kyn01535** [comment]
Is Player.player null in those cases?

**Comment by Trojaner25** [comment]
This happens when a player disconnects.

**Comment by Trojaner25** [comment]
Yes, Player.player seems to be null.
This is really really annoying now.

**Comment by Trojaner25** [comment]
ok, I found the issue.
I used UnturnedPlayer.FromCSteamID(id) where the id was wrong and not online.
New suggestion: throw an exception on UnturnedPlayer.FromCSteamID(id) when the id is not online..

**Comment by fr34kyn01535** [comment]
Being null seems to be pretty clear in this situation
