### ISSUE TITLE
The unkillable zombie of weapons

### ISSUE THREAD

**Issue by xionserver** [RocketMod/Rocket#755]
Do not kill zombies with weapons. 
Put a clean game through script update.sh on Linux 
Config.json-where you set up the zombie is not touched.

Kill zombies hand, explosions, vehicles, but weapons, whether melee or ranged, not killed.

The video attached.
<video>https://youtu.be/U6tCa-mq9uI</video>
Please tell me how to fix it.

**Comment by fr34kyn01535** [comment]
https://github.com/RocketMod/Rocket/wiki/Fixing-Issues
