### ISSUE TITLE
Communication between server and players stops and players are disonnecting

### ISSUE THREAD

**Issue by BeRtRoLlT** [RocketMod/Rocket#759]
If you scroll up in the console and you keep scrolled up all players will lose the connection, when you stop holding scrolled up the connection is back. But  if you hold scrolled up for a to long time all players will disconnect. I don't know if this is a rocket or unturned bug, but i will test it soon.

**Comment by BeRtRoLlT** [comment]
Ok, i tested and i only have this issue when rocket mod is installed and active

**Comment by cartman-2000** [comment]
This is standard behaviour for the console in windows, it does it in other games that use a console, also putting the window into select mode will also freeze the server. It freezes as it's not able to output to the console at that point in time.

**Comment by BeRtRoLlT** [comment]
Okay but why does it only happen when rocket is installed?

**Comment by cellinho** [comment]
Yup its not rocket issue, +1 to @cartman-2000 

I think opening the unturned.log its better.
