### ISSUE TITLE
Permission system improvement

### ISSUE THREAD

**Issue by BeRtRoLlT** [RocketMod/Rocket#760]
I would like if there is a way to make a group has a faster cooldown for a command as the parent group.

For example: Group Default can use /day all 700 seconds and group VIP which has  Default as parent group should be able to use /day faster like all 300 seconds.

I think there is no way to do this at the moment, if there is please correct me

**Comment by Aludre** [comment]
Same problem with me on my 2 servers.....and it had not been done now...
Gonna make the deafault use/v with 7200s cooltime while the vips can ues it with 3600s cooltime
that makes me mad...
So this is a BUG or someone had solve that?

**Comment by DronXa** [comment]
Maybe add priority number for every group as an option <Priority>1</Priority>,  this would make stuff like cooldown much more customizable.

**Comment by DronXa** [comment]
This priority feature would prioritize Cooldown, prefixes, and chat color. Which gives more control of what color users should have based of priority numbers

**Comment by BeRtRoLlT** [comment]
Im currently working on a Plugin which brings a new permission system based on weights.

**Comment by persiafighter** [comment]
This has already been added - group priorities.

**Comment by BeRtRoLlT** [comment]
Well check the date of the thread. It wasn't added back then.

**Comment by persiafighter** [comment]
Yeah... but it's added now... so shouldn't this be closed?

**Comment by BeRtRoLlT** [comment]
Well yes but i didn't even know its still open.
