### ISSUE TITLE
RCON issue

### ISSUE THREAD

**Issue by root1k** [RocketMod/Rocket#761]
I set up rcon enabled in Rocket.confing on true.But In console i do not see anything about RCON. It is normal? I need RCON to connect to my server with site. When i test RCON on site, in console i see: Client has disconnected(IP XX.XX.XX.XX:XXXX(ip of site)). Command from site does not perform. Please help me, i need to connect site with server,
Sorry for my English.

**Comment by cartman-2000** [comment]
RCON in rocket uses telnet, you will need to use something that supports that to use RCON(like putty on windows, or the telnet command in mac/linux)
