### ISSUE TITLE
Error while compiling generated serializer (The type `Rocket.API.IDefaultable' is defined in an assembly that is not referenced.)

### ISSUE THREAD

**Issue by LiquidProcessor** [RocketMod/Rocket#763]
Hi, im running on a DigitalOcean Ubuntu server with ALL ports open (open ports dont seem to be an issue here). I recently installed a VANILLA Unturned server and the latest version of Rocket with all the dependencies. I am getting this error every time I start up the server:

```
Error while compiling generated serializer
/tmp/40b1cff6/5b118417.cs(27,36) : error CS0012: The type `Rocket.API.IDefaultable' is defined in an assembly that is not referenced. Consider adding a reference to assembly `Rocket.API, Version=2.6.3.0, Culture=neutral, PublicKeyToken=null'
(0,0) : error : /unturned/server/Unturned_Headless_Data/Managed/Rocket.Core.dll (Location of the symbol related to previous error)
```

**No one can directly connect to the server, and the server does NOT show up in the master server list**

I've seen a few other issues with this exact same error, and they also have the same problems as I do. But all the issues seemed to have been vaguely closed with absolutely no solution, or just closed because its "not a Rocket error".

**Comment by cellinho** [comment]
Hello, and I think it is a rocket error!
But that thing you said 

> No one can directly connect to the server, and the server does NOT show up in the master server list

This is not happening to me.

I just leave it here

`Error while compiling generated serializer
/tmp/server/513c1c66/6f30d166.cs(27,36) : error CS0012: The type `Rocket.API.IDefaultable' is defined in an assembly that is not referenced. Consider adding a reference to assembly `Rocket.API, Version=2.6.3.0, Culture=neutral, PublicKeyToken=null'
(0,0) : error : /home/server/unturned_server/vanilla_server/Unturned_Headless_Data/Managed/Rocket.Core.dll (Location of the symbol related to previous error)`

I had this but everything still working. Thanks.

**Comment by fr34kyn01535** [comment]
its not an error.
