### ISSUE TITLE
Rocket wont update Unturned (Stuck at 3.15.8.0)

### ISSUE THREAD

**Issue by Frensiow** [RocketMod/Rocket#766]
Hi, since the new **3.15.8.1** update, even if i update my game and even if i recreate the server with new files, Rocket allways launch _''Rocket Unturned **v4.9.7.0** for Unturned **v3.15.8.0**''_. But i copied my game folder, that open Unturned **3.15.8.2**, on my desktop to create a whole new server with fresh new files and it still opens **3.15.8.0**. Even if i delete all the files in my _''C:\Program Files (x86)\Steam\steamapps\common\Unturned''_ and reinstall the whole game back then use that folder for the server it still doesn't work! I was able to use my server before the **3.15.8.0** update, and the server updated itself to **3.15.8.0** so i don't know what to do at all! Am i the only one having this problem? Is Rocket having a problem or am i? ahah
Thanks in advance!

**Comment by cellinho** [comment]
Hmm... Make sure you updated the hole stuff.
Rocketmod has updated.

**Comment by Frensiow** [comment]
i allready did! Anything else? :/
