### ISSUE TITLE
RocketObservatory banned all players from my server ?

### ISSUE THREAD

**Issue by OldCash4u** [RocketMod/Rocket#768]
plase helppp myy !!! 

System >> [RockeMod Observatory] Player G15 is banned:
System >> [RockeMod Observatory] Player NixonVac is banned:
System >> [RockeMod Observatory] Player Gustavo is banned:
System >> [RockeMod Observatory] Player PikaDasGalaxia is banned:

in rocket 960 windows

**Comment by cokll** [comment]
Me tooo

**Comment by fr34kyn01535** [comment]
Fixed
