### ISSUE TITLE
Can not add reference to another plugin

### ISSUE THREAD

**Issue by Trojaner25** [RocketMod/Rocket#774]
I have 2 plugins (Rocket-Regiones and GunLicenses).
I want to add a reference from GunLicenses to Rocket-Regiones.
The plugin on the server server and the lib of GunLicenses are the exact same version, both plugins are installed properly on the server etc.
But when I start the Server, I get this error:
> Couldn't find dependency: Rocket-Regions, Version:1.0.6.0, Culture=neutral, PublicKeyToken=null

GunLicenses also depends on UConomy, but for some reason it is working fine...

Error when accessing at runtime:
> [7/15/2016 4:54:48 PM] [Error] An error occured while executing license []: System.IO.FileNotFoundException: Could not load file or assembly 'Rocket-Regions, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'Rocket-Regions, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null'
  at Rocket.Core.Commands.RocketCommandManager+RegisteredRocketCommand.Execute (IRocketPlayer caller, System.String[] command) [0x00000] in <filename unknown>:0 
  at Rocket.Core.Commands.RocketCommandManager.Execute (IRocketPlayer player, System.String command) [0x00000] in <filename unknown>:0 

Again, Rocket-Regions is installed and fully working on the server. I just can't reference it...

**Comment by fr34kyn01535** [comment]
1. this is probably not a bug,...
Could you send me the link to the repos, i'll have a look at it...

**Comment by Trojaner25** [comment]
https://github.com/Trojaner25/Rocket-Regions and https://github.com/Trojaner25/GunLicenses

**Comment by Trojaner25** [comment]
Any updates?
