### ISSUE TITLE
Chat Error

### ISSUE THREAD

**Issue by jorea143** [RocketMod/Rocket#776]
I am getting this error after updating Unturned with patch released on 7/15/2016

http://pastebin.com/raw/A75fBHUh

FYI--I am using the generated/default permission file upon installing latest rocket. This is to make sure that there are no user errors on editing the permission file.

**Comment by jorea143** [comment]
When I removed Uessentials plugin. The error went away.

**Comment by Diablosito33** [comment]
Seems they wont update Essesntials this month.
I dont know how to COMPILE by myself, I dont know which programm/version to use.

Damn!

**Comment by LiquidProcessor** [comment]
getting the same error. none of the overridden commands work either. they NEED to update uessentials.
