### ISSUE TITLE
need help with issue

### ISSUE THREAD

**Issue by stev0rawr** [RocketMod/Rocket#778]
Edit: uessentials is the problem, I disabled it and now I don't get any errors. I think that the new unturned update broke uessentials, and will have to wait for uessentials to update.

![untitled](https://cloud.githubusercontent.com/assets/20494696/16897138/2c0f47ce-4b5d-11e6-8ea6-98640651c0b7.png)
Hay guys, 
I am new at this so be gentile. I try to shutdown server using uso's shutdown button and I get this error message. I got to the file and I can find nothing wrong...I haven't done any file editing, everything is default settings. I have looked around at other people who have had similar problems and have found no solutions, I have uninstalled/reinstalled that didn't help.

**Comment by Trojaner25** [comment]
Yes, this is caused by uEssentials which is broken because of a Unturned Update.

(A field which it was accessing is not available anymore)
