### ISSUE TITLE
Invalid or outdated plugin assembly. [Read/Please help]

### ISSUE THREAD

**Issue by KennethTop** [RocketMod/Rocket#779]
Hi Rocket.
I just made my own plugin, and everytime i try run it.
I get<color="Red"> Invalid or outdated plugin assembly: MyFirstPlugin.</color>

Here is my code.
[http://pastebin.com/ZAGmUtmu]

**Comment by fr34kyn01535** [comment]
You need a plugin class

**Comment by KennethTop** [comment]
How do i so made a custom commands class.
Can you show me a example?.

**Comment by cellinho** [comment]
check out the others plugin source codes.
