### ISSUE TITLE
/tphere Bug

### ISSUE THREAD

**Issue by mandm635** [RocketMod/Rocket#781]
When teleporting a player with the /tphere command, if that player is in a vehicle, things go weird for that player. A potential fix for this might be checking if they are in a vehicle before teleporting them, and either displaying a message saying that the player cannot be teleported at this time, or forcing the player to leave the vehicle, and then teleport them.

**Comment by cartman-2000** [comment]
This was an amusing bug back at the time that it would also teleport the player model out of the car too, you could get the players in the car to float above it for instance.

**Comment by Kr4ken-9** [comment]
This has been fixed @fr34kyn01535
