### ISSUE TITLE
Web Permissions

### ISSUE THREAD

**Issue by tricklike** [RocketMod/Rocket#789]
```
[7/30/2016 8:46:44 PM] [Info] Updating WebXMLFileAsset RocketPermissions from http://site-deleted
[7/30/2016 8:46:44 PM] [Error] ArgumentNullException: Argument cannot be null.
Parameter name: s - System.IO.StringReader..ctor (System.String s)
(wrapper remoting-invoke-with-check) System.IO.StringReader:.ctor (string)
Rocket.Core.Assets.WebXMLFileAsset`1+<Load>c__AnonStorey1+<Load>c__AnonStorey0[Rocket.API.Serialisation.RocketPermissions].<>m__0 ()
Rocket.Core.Utils.TaskDispatcher.FixedUpdate ()
```

This site got internal error (out of memory).
After this rocket doesn't download permission again until server restart.

**Comment by fr34kyn01535** [comment]
Why did you set the url to http://site-deleted? It does not exist...

**Comment by tricklike** [comment]
I just want to hide my site.

In configuration file the site is correct and it works 90% of time.
Why 90%? Because sometimes web server is running out of memory.

I just want to report, rocket doesn't trying to download again permission after error.
