### ISSUE TITLE
#972  the new update of rocket is bugged #972 

### ISSUE THREAD

**Issue by robotins212** [RocketMod/Rocket#804]
the build is not working and noone can join the server  after its installed

**Comment by robotins212** [comment]
i mean after isntalling the new rocket the server verison is "rocket for unturned unturned"
not "rocket for unturned 3.15.13.0" 
and i know that u need to put all files in unturned data/managed folder

**Comment by Vinx115** [comment]
yea same for me too when i installed the new version of unturned rocket doesnt work anymore and they didnt update it yet i thought that 1 hour after a new update comes out for unturned rocket updates too

**Comment by LuxarPL** [comment]
Same here
