### ISSUE TITLE
Rocket Permissions Broken?   (Unturned Server)

### ISSUE THREAD

**Issue by Endrail** [RocketMod/Rocket#805]
**I have a problem with my unturned server permission file. The default group is "default" and for some reason the kits permissions I added to it doesn't work. Here is my file:**

http://pastebin.com/MERQWNKr

**Please help.**

**Comment by robotins212** [comment]
kit.survival

**Comment by Endrail** [comment]
I turned the permission into kit.survival but it still doesn't work.
