### ISSUE TITLE
Pls help me!

### ISSUE THREAD

**Issue by BBDbrandon** [RocketMod/Rocket#806]
Ok so this morning me and my friend played on my server and random people joined and stuff and this afternoon i tried to launch the server and it didn't work it said this 
![image](https://cloud.githubusercontent.com/assets/21047051/17682224/27fbab46-6318-11e6-98a8-9f5251e1b964.png) so yea no idea pls help i also tried a fresh install no luck and i tried again made a vanilla server it had no errors and when i installed the rocket files then it gave me the same error pls help(also when i install mods it crashes) oh btw this is first time this happened and i barley know nothing about xml stuff so yea :D also i cant join and no one else so pls help me

**Comment by fr34kyn01535** [comment]
Its not a bug, you can ignore it.

**Comment by BBDbrandon** [comment]
but zaupshop says the same thing aswell

**Comment by BBDbrandon** [comment]
thanks for telling me i was worried there for a second

**Comment by BBDbrandon** [comment]
wait do i have to bind my ip because if if do that it crashes

**Comment by BBDbrandon** [comment]
people cant join my server doesnt show
