### ISSUE TITLE
cheats

### ISSUE THREAD

**Issue by vtnarg** [RocketMod/Rocket#808]
OK so i recently had to have my server reinstalled and since then  haven't been able to do any commands i am admin but for some reason i cant do any commands 

(my permissions file script thing)

![ggg](https://cloud.githubusercontent.com/assets/21051234/17688104/74613b8a-6341-11e6-9681-393f374c970b.PNG)

that is not the entire thing because this is where the problem is i don't know whats wrong with it because i suck with this stuff so please halp meh (the blue lines are my steam 64 id)

**Comment by fr34kyn01535** [comment]
This is not a bug.
