### ISSUE TITLE
[LINUX] Bugs while walking below trees

### ISSUE THREAD

**Issue by Mewys** [RocketMod/Rocket#811]
When I try to walk below trees I get teleported back a few inches so I cant cut them.
I am running ubunto 14.04 and reinstalled it a few times. I tried Debian too but got the same bug.
Btw. when I start the server there is an error message: Error running gmcs: cannot find specified file, followed by a few mono error messages but I don't really think that that's the reason for the bugs.
Am I doing something wrong or is this a problem of the Rocket Mod atm?

Error:

> System.SystemException: Error running gmcs: Cannot find the specified file
>   at Mono.CSharp.CSharpCodeCompiler.CompileFromFileBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames) [0x00000] in <filename unknown>:0 
>   at Mono.CSharp.CSharpCodeCompiler.CompileAssemblyFromFileBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames) [0x00000] in <filename unknown>:0 
>   at Mono.CSharp.CSharpCodeCompiler.CompileAssemblyFromFile (System.CodeDom.Compiler.CompilerParameters options, System.String fileName) [0x00000] in <filename unknown>:0 
>   at System.Xml.Serialization.XmlSerializer.GenerateSerializers (System.Xml.Serialization.GenerationBatch batch, System.CodeDom.Compiler.CompilerParameters cp) [0x00000] in <filename unknown>:0 
>   at System.Xml.Serialization.XmlSerializer.RunSerializerGeneration (System.Object obj) [0x00000] in <filename unknown>:0 
##

**Comment by Mewys** [comment]
I found another guy with exactly the same error and even with a video:

https://rocketmod.net/viewtopic.php?t=2060

**Comment by rwalkos** [comment]
I just did a fresh install today on Debian 8 and tested it out on PEI, I did not run into that problem. I did not test every tree out there but did run into about 20 trees with low hanging branches to test.

**Comment by celilnho** [comment]
i don't know if it will fix but try installing mono-gmcs

**Comment by Mewys** [comment]
@rwalkos did you install Rocket with this guide? https://github.com/RocketMod/Rocket/wiki/Installing-Rocket-on-Linux

@celilnho i have already installed mono-xbuild, mono-mcs and mono-devel and ubuntu says that they replace mono-gmcs

**Comment by Mewys** [comment]
I tried to reinstall all packages and recogniced that the package libmono2.0cil can't be installed because there is no installation candidate. I tried apt-get Update and Upgrade but found no solution so far.

**Comment by rwalkos** [comment]
Freash Debian install needs dependancies.

```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install screen htop unzip
sudo apt-get install lib32stdc++6
sudo apt-get install libmono2.0-cil mono-runtime
sudo reboot
```

Part 2:
```
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install libc6:i386 libgl1-mesa-glx:i386 libxcursor1:i386 libxrandr2:i386
```

**Comment by Mewys** [comment]
I followed all these steps but get the same error while installing libmono2.0-cil

**Comment by fr34kyn01535** [comment]
Scroll down on https://github.com/RocketMod/Rocket.Unturned/tree/master/Rocket.Unturned/Scripts/Linux and see if the given solution helps you
