### ISSUE TITLE
[Error]Linux

### ISSUE THREAD

**Issue by Failcrafter1998** [RocketMod/Rocket#814]
I get this Error on Startup, and i can't walk under Trees.

Error while compiling generated serializer
/tmp/74ac7f9f/8483e39.cs(27,36) : error CS0012: The type `Rocket.API.IDefaultable' is defined in an assembly that is not referenced. Consider adding a reference to assembly `Rocket.API, Version=2.6.4.0, Culture=neutral, PublicKeyToken=null'
(0,0) : error : /home/unturned/unturned/Unturned_Headless_Data/Managed/Rocket.Core.dll (Location of the symbol related to previous error)

Running The Server on Debian 8

**Comment by fr34kyn01535** [comment]
This is not a bug.
