### ISSUE TITLE
How to make 2 servers?

### ISSUE THREAD

**Issue by Doten** [RocketMod/Rocket#820]
Initialize engine version: 5.2.5f1 (ad2d0368e248)
Forcing GfxDevice: Null
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
Begin MonoManager ReloadAssembly
Platform assembly: C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\UnityEngine.dll (this message is harmless)
Loading C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\UnityEngine.dll into Unity Child Domain
Platform assembly: C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\Assembly-CSharp-firstpass.dll (this message is harmless)
Loading C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\Assembly-CSharp-firstpass.dll into Unity Child Domain
Platform assembly: C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\Assembly-CSharp.dll (this message is harmless)
Loading C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\Assembly-CSharp.dll into Unity Child Domain
Platform assembly: C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\Assembly-UnityScript-firstpass.dll (this message is harmless)
Loading C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\Assembly-UnityScript-firstpass.dll into Unity Child Domain
Platform assembly: C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\UnityEngine.UI.dll (this message is harmless)
Loading C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\UnityEngine.UI.dll into Unity Child Domain
Platform assembly: C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\UnityEngine.Networking.dll (this message is harmless)
Loading C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\UnityEngine.Networking.dll into Unity Child Domain
Platform assembly: C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\UnityEngine.Analytics.dll (this message is harmless)
Loading C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\UnityEngine.Analytics.dll into Unity Child Domain
Platform assembly: C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\Pathfinding.ClipperLib.dll (this message is harmless)
Loading C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\Pathfinding.ClipperLib.dll into Unity Child Domain
Platform assembly: C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\Pathfinding.Ionic.Zip.Reduced.dll (this message is harmless)
Loading C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\Pathfinding.Ionic.Zip.Reduced.dll into Unity Child Domain
Platform assembly: C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\Pathfinding.JsonFx.dll (this message is harmless)
Loading C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\Pathfinding.JsonFx.dll into Unity Child Domain
Platform assembly: C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\Pathfinding.Poly2Tri.dll (this message is harmless)
Loading C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\Pathfinding.Poly2Tri.dll into Unity Child Domain
Platform assembly: C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\Newtonsoft.Json.dll (this message is harmless)
Loading C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\Newtonsoft.Json.dll into Unity Child Domain
Platform assembly: C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\UnityEngine.CrashLog.dll (this message is harmless)
Loading C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\UnityEngine.CrashLog.dll into Unity Child Domain
Platform assembly: C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\System.Core.dll (this message is harmless)
- Completed reload, in  0.650 seconds
Platform assembly: C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\System.dll (this message is harmless)
Platform assembly: C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\System.Xml.dll (this message is harmless)
The file 'C:/Users/Wisser/Desktop/Server/ru_server2/Unturned_Data/mainData' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 241)

The file 'C:/Users/Wisser/Desktop/Server/ru_server2/Unturned_Data/mainData' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 241)

The file 'C:/Users/Wisser/Desktop/Server/ru_server2/Unturned_Data/mainData' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 241)

The file 'C:/Users/Wisser/Desktop/Server/ru_server2/Unturned_Data/mainData' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 241)

The file 'C:/Users/Wisser/Desktop/Server/ru_server2/Unturned_Data/mainData' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 241)

The file 'C:/Users/Wisser/Desktop/Server/ru_server2/Unturned_Data/mainData' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 241)

The file 'C:/Users/Wisser/Desktop/Server/ru_server2/Unturned_Data/mainData' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 241)

The file 'C:/Users/Wisser/Desktop/Server/ru_server2/Unturned_Data/mainData' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 241)

The file 'C:/Users/Wisser/Desktop/Server/ru_server2/Unturned_Data/mainData' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 241)

The file 'C:/Users/Wisser/Desktop/Server/ru_server2/Unturned_Data/mainData' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 241)

The file 'C:/Users/Wisser/Desktop/Server/ru_server2/Unturned_Data/mainData' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 241)

The file 'C:/Users/Wisser/Desktop/Server/ru_server2/Unturned_Data/mainData' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 241)

The file 'C:/Users/Wisser/Desktop/Server/ru_server2/Unturned_Data/mainData' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 241)

The file 'C:/Users/Wisser/Desktop/Server/ru_server2/Unturned_Data/mainData' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 235)

The file 'C:/Users/Wisser/Desktop/Server/ru_server2/Unturned_Data/mainData' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 241)

Platform assembly: C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\System.Data.dll (this message is harmless)
3.16.1.1
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Platform assembly: C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\Rocket.Unturned.dll (this message is harmless)
Platform assembly: C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\Rocket.Core.dll (this message is harmless)
Platform assembly: C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\Rocket.API.dll (this message is harmless)
Unloading 4 Unused Serialized files (Serialized files now loaded: 0)

Unloading 2218 unused Assets to reduce memory usage. Loaded Objects now: 44767.
Total: 25.009600 ms (FindLiveObjects: 2.070200 ms CreateObjectMapping: 6.094726 ms MarkObjects: 16.310652 ms  DeleteObjects: 0.521440 ms)

Quit due to provider exception: GameServer API initialization failed!
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Platform assembly: C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Managed\System.Configuration.dll (this message is harmless)
Fallback handler could not load library C:/Users/Wisser/Desktop/Server/ru_server2/Unturned_Data/Mono/libc
Fallback handler could not load library C:/Users/Wisser/Desktop/Server/ru_server2/Unturned_Data/Mono/.\libc
Fallback handler could not load library C:/Users/Wisser/Desktop/Server/ru_server2/Unturned_Data/Mono/libc
Crash!!!
SymInit: Symbol-SearchPath: '.;C:\Users\Wisser\Desktop\Server\ru_server\Servers\RuServ2\Rocket;C:\Users\Wisser\Desktop\Server\ru_server2;C:\WINDOWS;C:\WINDOWS\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'Wisser'
OS-Version: 10.0.10586 () 0x300-0x1
C:\Users\Wisser\Desktop\Server\ru_server2\Unturned.exe:Unturned.exe (00007FF680E50000), size: 20312064 (result: 0), SymType: '-exported-', PDB: 'C:\Users\Wisser\Desktop\Server\ru_server2\Unturned.exe', fileVersion: 5.2.5.11523
C:\WINDOWS\SYSTEM32\ntdll.dll:ntdll.dll (00007FFDF2450000), size: 1839104 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\ntdll.dll', fileVersion: 10.0.10586.306
C:\WINDOWS\system32\KERNEL32.DLL:KERNEL32.DLL (00007FFDF0610000), size: 708608 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\KERNEL32.DLL', fileVersion: 10.0.10586.0
C:\WINDOWS\system32\KERNELBASE.dll:KERNELBASE.dll (00007FFDEF010000), size: 1998848 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\KERNELBASE.dll', fileVersion: 10.0.10586.494
C:\WINDOWS\system32\WS2_32.dll:WS2_32.dll (00007FFDF1F40000), size: 438272 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\WS2_32.dll', fileVersion: 10.0.10586.420
C:\WINDOWS\system32\sechost.dll:sechost.dll (00007FFDF20D0000), size: 372736 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\sechost.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\system32\RPCRT4.dll:RPCRT4.dll (00007FFDF1FB0000), size: 1163264 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\RPCRT4.dll', fileVersion: 10.0.10586.306
C:\WINDOWS\system32\USER32.dll:USER32.dll (00007FFDF0020000), size: 1400832 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\USER32.dll', fileVersion: 10.0.10586.306
C:\WINDOWS\system32\GDI32.dll:GDI32.dll (00007FFDF01E0000), size: 1597440 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\GDI32.dll', fileVersion: 10.0.10586.420
C:\WINDOWS\SYSTEM32\HID.DLL:HID.DLL (00007FFDEDA60000), size: 49152 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\HID.DLL', fileVersion: 10.0.10586.0
C:\WINDOWS\system32\ole32.dll:ole32.dll (00007FFDF1DF0000), size: 1323008 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\ole32.dll', fileVersion: 10.0.10586.545
C:\WINDOWS\system32\combase.dll:combase.dll (00007FFDF21D0000), size: 2609152 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\combase.dll', fileVersion: 10.0.10586.103
C:\WINDOWS\system32\msvcrt.dll:msvcrt.dll (00007FFDF2130000), size: 643072 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\msvcrt.dll', fileVersion: 7.0.10586.0
C:\WINDOWS\system32\bcryptPrimitives.dll:bcryptPrimitives.dll (00007FFDEEB60000), size: 434176 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\bcryptPrimitives.dll', fileVersion: 10.0.10586.420
C:\WINDOWS\system32\SHLWAPI.dll:SHLWAPI.dll (00007FFDF0180000), size: 335872 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\SHLWAPI.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\system32\ADVAPI32.dll:ADVAPI32.dll (00007FFDF06D0000), size: 684032 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\ADVAPI32.dll', fileVersion: 10.0.10586.63
C:\WINDOWS\system32\SHELL32.dll:SHELL32.dll (00007FFDF0890000), size: 22396928 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\SHELL32.dll', fileVersion: 10.0.10586.545
C:\WINDOWS\system32\cfgmgr32.dll:cfgmgr32.dll (00007FFDEEE80000), size: 274432 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\cfgmgr32.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\system32\windows.storage.dll:windows.storage.dll (00007FFDEF200000), size: 6574080 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\windows.storage.dll', fileVersion: 10.0.10586.494
C:\WINDOWS\SYSTEM32\VERSION.dll:VERSION.dll (00007FFDEAB40000), size: 40960 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\VERSION.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\system32\kernel.appcore.dll:kernel.appcore.dll (00007FFDEEA90000), size: 61440 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\kernel.appcore.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\system32\shcore.dll:shcore.dll (00007FFDEEDC0000), size: 741376 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\shcore.dll', fileVersion: 10.0.10586.494
C:\WINDOWS\system32\powrprof.dll:powrprof.dll (00007FFDEEAB0000), size: 307200 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\powrprof.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\system32\profapi.dll:profapi.dll (00007FFDEEA70000), size: 81920 (result: 0), SymType: '-nosymbols-', PDB: 'C:\WINDOWS\system32\profapi.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\system32\OLEAUT32.dll:OLEAUT32.dll (00007FFDEF850000), size: 790528 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\OLEAUT32.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\system32\IMM32.dll:IMM32.dll (00007FFDF0370000), size: 241664 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\IMM32.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\OPENGL32.dll:OPENGL32.dll (00007FFDE11E0000), size: 1216512 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\OPENGL32.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\WINMM.dll:WINMM.dll (00007FFDED1F0000), size: 143360 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\WINMM.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\MSACM32.dll:MSACM32.dll (00007FFDE7D00000), size: 114688 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\MSACM32.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\DNSAPI.dll:DNSAPI.dll (00007FFDED3F0000), size: 696320 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\DNSAPI.dll', fileVersion: 10.0.10586.212
C:\WINDOWS\system32\NSI.dll:NSI.dll (00007FFDF06C0000), size: 32768 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\NSI.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL:IPHLPAPI.DLL (00007FFDE93C0000), size: 229376 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\WINHTTP.dll:WINHTTP.dll (00007FFDE7D80000), size: 819200 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\WINHTTP.dll', fileVersion: 10.0.10586.420
C:\WINDOWS\SYSTEM32\GLU32.dll:GLU32.dll (00007FFDE8120000), size: 188416 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\GLU32.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\DDRAW.dll:DDRAW.dll (00007FFDDD390000), size: 1024000 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\DDRAW.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\WINMMBASE.dll:WINMMBASE.dll (00007FFDED080000), size: 180224 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\WINMMBASE.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\DCIMAN32.dll:DCIMAN32.dll (00007FFDEC0B0000), size: 32768 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\DCIMAN32.dll', fileVersion: 10.0.10586.3
C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Mono\mono.dll:mono.dll (00007FFDD59E0000), size: 2990080 (result: 0), SymType: '-exported-', PDB: 'C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Mono\mono.dll', fileVersion: 1.0.0.1
C:\WINDOWS\system32\PSAPI.DLL:PSAPI.DLL (00007FFDEFEB0000), size: 32768 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\PSAPI.DLL', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\MSWSOCK.dll:MSWSOCK.dll (00007FFDEE3A0000), size: 376832 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\MSWSOCK.dll', fileVersion: 10.0.10586.420
C:\WINDOWS\system32\uxtheme.dll:uxtheme.dll (00007FFDED4D0000), size: 614400 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\uxtheme.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\system32\MSCTF.dll:MSCTF.dll (00007FFDEFEC0000), size: 1417216 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\MSCTF.dll', fileVersion: 10.0.10586.71
C:\WINDOWS\system32\dwmapi.dll:dwmapi.dll (00007FFDECC30000), size: 139264 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\dwmapi.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL:MMDevAPI.DLL (00007FFDE9920000), size: 458752 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\MMDevAPI.DLL', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\DEVOBJ.dll:DEVOBJ.dll (00007FFDED4A0000), size: 159744 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\DEVOBJ.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\PROPSYS.dll:PROPSYS.dll (00007FFDEBEC0000), size: 1597440 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\PROPSYS.dll', fileVersion: 7.0.10586.494
C:\WINDOWS\SYSTEM32\wdmaud.drv:wdmaud.drv (00007FFDE4750000), size: 270336 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\wdmaud.drv', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\ksuser.dll:ksuser.dll (00007FFDDCFF0000), size: 32768 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\ksuser.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\AVRT.dll:AVRT.dll (00007FFDEC110000), size: 45056 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\AVRT.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL:AUDIOSES.DLL (00007FFDED250000), size: 557056 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\AUDIOSES.DLL', fileVersion: 10.0.10586.122
C:\WINDOWS\SYSTEM32\wintypes.dll:wintypes.dll (00007FFDE9060000), size: 1269760 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\wintypes.dll', fileVersion: 10.0.10586.103
C:\WINDOWS\SYSTEM32\msacm32.drv:msacm32.drv (00007FFDE8440000), size: 49152 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\msacm32.drv', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\midimap.dll:midimap.dll (00007FFDE8320000), size: 40960 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\midimap.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\dsound.dll:dsound.dll (00007FFDDAD20000), size: 638976 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\dsound.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\system32\clbcatq.dll:clbcatq.dll (00007FFDF0560000), size: 684032 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\clbcatq.dll', fileVersion: 2001.12.10941.16384
C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Plugins\CSteamworks.dll:CSteamworks.dll (00007FFDE8470000), size: 167936 (result: 0), SymType: '-exported-', PDB: 'C:\Users\Wisser\Desktop\Server\ru_server2\Unturned_Data\Plugins\CSteamworks.dll', fileVersion: 1.24.0.0
C:\Users\Wisser\Desktop\Server\ru_server2\steam_api64.dll:steam_api64.dll (0000000069E20000), size: 225280 (result: 0), SymType: '-exported-', PDB: 'C:\Users\Wisser\Desktop\Server\ru_server2\steam_api64.dll', fileVersion: 2.89.45.4
C:\Program Files (x86)\Steam\steamclient64.dll:steamclient64.dll (000000006A0E0000), size: 12947456 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files (x86)\Steam\steamclient64.dll', fileVersion: 3.58.42.68
C:\WINDOWS\system32\CRYPT32.dll:CRYPT32.dll (00007FFDEEBF0000), size: 1867776 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\CRYPT32.dll', fileVersion: 10.0.10586.494
C:\WINDOWS\system32\MSASN1.dll:MSASN1.dll (00007FFDEEAA0000), size: 65536 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\MSASN1.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\system32\imagehlp.dll:imagehlp.dll (00007FFDEF9F0000), size: 114688 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\imagehlp.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\system32\SETUPAPI.dll:SETUPAPI.dll (00007FFDEFA80000), size: 4362240 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\SETUPAPI.dll', fileVersion: 10.0.10586.420
C:\Program Files (x86)\Steam\tier0_s64.dll:tier0_s64.dll (0000000069EF0000), size: 1982464 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files (x86)\Steam\tier0_s64.dll', fileVersion: 3.58.42.68
C:\Program Files (x86)\Steam\vstdlib_s64.dll:vstdlib_s64.dll (0000000069E80000), size: 442368 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files (x86)\Steam\vstdlib_s64.dll', fileVersion: 3.58.42.68
C:\WINDOWS\SYSTEM32\Secur32.dll:Secur32.dll (00007FFDE74D0000), size: 49152 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\Secur32.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\SSPICLI.DLL:SSPICLI.DLL (00007FFDEE750000), size: 184320 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\SSPICLI.DLL', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL:CRYPTBASE.DLL (00007FFDEE570000), size: 45056 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL:dhcpcsvc.DLL (00007FFDE9230000), size: 106496 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL', fileVersion: 10.0.10586.420
C:\Program Files (x86)\Steam\crashhandler64.dll:crashhandler64.dll (00007FFDE14C0000), size: 2027520 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files (x86)\Steam\crashhandler64.dll', fileVersion: 3.58.42.68
C:\WINDOWS\SYSTEM32\WININET.dll:WININET.dll (00007FFDE0B30000), size: 3059712 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\WININET.dll', fileVersion: 11.0.10586.545
C:\WINDOWS\SYSTEM32\Wlanapi.dll:Wlanapi.dll (00007FFDE5D20000), size: 397312 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\Wlanapi.dll', fileVersion: 10.0.10586.306
C:\WINDOWS\system32\wbem\wbemprox.dll:wbemprox.dll (00007FFDE4480000), size: 69632 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\wbem\wbemprox.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\wbemcomn.dll:wbemcomn.dll (00007FFDE71E0000), size: 520192 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\wbemcomn.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\bcrypt.dll:bcrypt.dll (00007FFDEE8E0000), size: 167936 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\bcrypt.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL:dhcpcsvc6.DLL (00007FFDE9300000), size: 90112 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL', fileVersion: 10.0.10586.420
C:\WINDOWS\system32\wbem\wbemsvc.dll:wbemsvc.dll (00007FFDE3250000), size: 81920 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\wbem\wbemsvc.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\system32\wbem\fastprox.dll:fastprox.dll (00007FFDE40C0000), size: 1007616 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\wbem\fastprox.dll', fileVersion: 10.0.10586.0
C:\WINDOWS\SYSTEM32\dbghelp.dll:dbghelp.dll (00007FFDE72D0000), size: 1622016 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\dbghelp.dll', fileVersion: 10.0.10586.0

========== OUTPUTING STACK TRACE ==================

0x000000000B750058 (Mono JIT Code) (wrapper managed-to-native) Steamworks.NativeMethods:ISteamGameServer_SetKeyValue (Steamworks.InteropHelp/UTF8StringHandle,Steamworks.InteropHelp/UTF8StringHandle)
RtlLookupFunctionEntry returned NULL function. Aborting stack walk.
========== END OF STACKTRACE ===========

**** Crash! ****

**Comment by Doten** [comment]
(It's second server, first server works ok)

**Comment by fr34kyn01535** [comment]
This is not a bug. (Guessing by the "Who" and the question mark in the title)
