### ISSUE TITLE
Question about coding a plugin

### ISSUE THREAD

**Issue by BeRtRoLlT** [RocketMod/Rocket#822]
I don't know if im right here, but ill ask here now.

Im working on a rocket plugin and anything works so far.
But i also want the plugin to shutdown the server. 
I dont know how to do that and if the plugin can just call /shutdown or if i need to implement the function by another way.

It would be great if someone can help me, thanks
BeRtRoLlT

**Comment by fr34kyn01535** [comment]
This is not a bug
