### ISSUE TITLE
error when starting up server

### ISSUE THREAD

**Issue by MrAdamson45** [RocketMod/Rocket#823]
when i start my server with rocket 4.9.8.2 this message pops up

![image](https://cloud.githubusercontent.com/assets/22105236/18398844/6768664a-76c6-11e6-9e61-a0d365387a4d.png)

**Comment by MrAdamson45** [comment]
BTW i cant shut down either

**Comment by MrSpooks** [comment]
Think this is to do with the Unity version nelson did, Rocket mod needs updating I'm having the same issue.

**Comment by Chaemelion** [comment]
I'm no expert, but it seems to me some function calls in Assembly-CSharp.dll are different in the new version of Unity. The update broke my server, and many more I'm assuming.

**Comment by MrSpooks** [comment]
Indeed ^^ The only way round this (unfortunately) is to re-update the server and run without RocketMod until it is updated.

**Comment by cartman-2000** [comment]
It would appear that some of your dll files might be out of date, as the version string it's supposed so show is 3.16.3.1, not 3.16.2.1. I'm running the rocket update for 3.16.3.1 on my server without any issues on my end, and it shows the correct version string.

**Comment by MrSpooks** [comment]
Yes BUT after you update your server (As of last night) the unity version got updated, So it needs updating in the Assembly before we can use it again.

**Comment by MrAdamson45** [comment]
k guys. thanks for all the help. ill try cartman-2000's first and if that doesn't work for me, i'll do as MrSpooks says.

**Comment by MrAdamson45** [comment]
updated it today and doesnt work again

**Comment by MrAdamson45** [comment]
fixed. didnt know that you had to make a new server from a new copied folder
