### ISSUE TITLE
Rocket.Core >> Could not load plugin assembly: .........

### ISSUE THREAD

**Issue by xavixer** [RocketMod/Rocket#826]
![failed](https://cloud.githubusercontent.com/assets/20692486/18586200/ade2a9e4-7c45-11e6-95eb-9f5ea153bdef.PNG)

please help me...
Im using Ubuntu 12.04 32bit

**Comment by fr34kyn01535** [comment]
Have you tried redownloading the plugin? Could you paste the log on pastebin please?
