### ISSUE TITLE
Players disconnect soon after connecting Rocket Linux build 687

### ISSUE THREAD

**Issue by unturnedplayer** [RocketMod/Rocket#827]
With Unturned 3.16.4 and Rocket Linux build 687, after a player connects they soon disconnect after several seconds but the client's screen still shows the loading screen.  No errors appear in the console upon starting the server nor upon players connecting to the server.

**Comment by SmallSansSerif** [comment]
Same for me. Players just see loading screen and hear in-game sounds but never get past join screen. No errors post in console.

**Comment by SmallSansSerif** [comment]
Just noticed that Linux build is not up to latest but Windows is. 3.16.4.0 Maybe it's just an oversight?

<img width="589" alt="screen shot 2016-09-16 at 7 43 28 pm" src="https://cloud.githubusercontent.com/assets/4984139/18604064/e38604f6-7c45-11e6-9095-16c4b79f4288.png">

**Comment by KEJustusKE** [comment]
Same problem for me. I tried it with the newest build 688 but it don´t work too. ;(

**Comment by hrdejong** [comment]
Same here, punching even produces sound and after a while the player dehydrates. 688 not working.

**Comment by rube200** [comment]
I also currently have this problem but could find something in logs.txt and LogsPrev.txt

Logs.txt :

3.16.4.1

A script behaviour (probably SDG.Unturned.HumanClothes?) has a different serialization layout when loading. (Read 76 bytes but expected 80 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?

...

A script behaviour (probably SDG.Unturned.HumanClothes?) has a different serialization layout when loading. (Read 76 bytes but expected 80 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?



But I know that this error is only happening in linux

**Comment by hrdejong** [comment]
For me it's working with the new release of Rocketmod.

**Comment by rube200** [comment]
now is already working
what I did was manually update but as it is I had to install again (apt-get install ...) and (apt-get update), (apt-get upgrade)

**Comment by fr34kyn01535** [comment]
Seems fixed in latest version
