### ISSUE TITLE
TypeLoadException Assembly-CSharp

### ISSUE THREAD

**Issue by xxXTheAlexXxx** [RocketMod/Rocket#829]
Everything worked fine, but week latter i updated unturned and reinstalled rocket. now when i launch server it writes
TypeLoadException: Could not load type 'UnityEngine.SceneManagement.SceneManager' from assembly 'Assembly-CSharp' . - UnityEngine.MonoBehaviour:StartCoroutine(String)
SDG.Unturned.Assets:refresh()
SDG.Unturned.Assets:start()

**Comment by fr34kyn01535** [comment]
Try reinstalling
