### ISSUE TITLE
Steam Group Permissions and Whitelists

### ISSUE THREAD

**Issue by jjkrause** [RocketMod/Rocket#834]
**Current scenario:**  There are servers on which they have two opposing groups of players, basically "good guys vs bad guys".  Be it cops vs robbers, or two opposing military groups, players decide which team they play for by joining steam groups.  At the moment, there is no way of automatically assigning different permissions to different steam groups, and nothing prevents any users of joining the server even if they are not a member of the steam groups.  

**What would be extremely useful for these types of servers would be:**
- Being able to add a steam group to Rocket's permission file to specify which permissions teams have.
- Add steam groups to Rocket's whitelist, so nobody can join unless they are a member of one of the two steam groups.

Also on my wishlist, removing inheritance of the default group by default...  The inheritance should only take effect if the default group is specified as a ParentGroup.

The result would be being able to allow different kits for different teams.
Thanks!
Kraken

**Comment by fr34kyn01535** [comment]
This can be done by a plugin
