### ISSUE TITLE
Plugins did work, but now no longer work?!?!?

### ISSUE THREAD

**Issue by Zeznax** [RocketMod/Rocket#838]
I had a server and decided I would add plugins. So I added plugins and everything was great. Then I was setting up kits from the kits plugin and it did not work. I was very frustrated and then I noticed my other plugins did not work either. TPA and Join/Leave Messages stopped working. Whenever I try /tpa or /kits it says Command Not Found. I tried reinstalling the plugins. I deleted them and their folders and put the .dll files back (new ones). They did not reinstall or create new folders and in the server console, they did not load?

**Comment by fr34kyn01535** [comment]
https://github.com/RocketMod/Rocket/wiki/Fixing-Issues
