### ISSUE TITLE
Invalid IL code error when loading the server.

### ISSUE THREAD

**Issue by cartman-2000** [RocketMod/Rocket#841]
You get this trace spamming in the console when loading the server on 3.17.1.0. It doesn't seem to affect the stability of the server, or how it works though.

```
[10/7/2016 9:50:01 AM] [Error] InvalidProgramException: Invalid IL code in SDG.Unturned.EffectAsset:.ctor (SDG.Unturned.Bundle,SDG.Unturned.Data,SDG.Unturned.Local,uint16): IL_0245: call      0x0a0001df

 - SDG.Unturned.Assets.loadFile (ScannedFileInfo file)
UnityEngine.Debug:LogException(Exception)
SDG.Unturned.Assets:loadFile(ScannedFileInfo)
SDG.Unturned.<init>c__Iterator0:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```
##

**Comment by ZSHADOWWOLF** [comment]
Where is fix this problem? I cant Run my servers,beacuse this bug (players can't see my server)

**Comment by fr34kyn01535** [comment]
Temporary fix because cynicalsinner does not believe me its not causing any issues. Will fix when i have time.

**Comment by cartman-2000** [comment]
I'm not sure about Linux, but the bug didn't block the server from loading up for me.  If players aren't able to see your server, it may be another issue not related to this bug.
