### ISSUE TITLE
Server does not start

### ISSUE THREAD

**Issue by Akanixon** [RocketMod/Rocket#845]
Every time i start the server i get this and nothing happens for hours, what have i done wrong?
![unturned](https://cloud.githubusercontent.com/assets/22319382/19613942/767f6188-97f0-11e6-9a79-c98a31851d9e.PNG)
##

**Comment by gadoneitor15** [comment]
hey dud can you help me whit the installation of unturned server on linux

**Comment by fr34kyn01535** [comment]
#858
