### ISSUE TITLE
No blue text?

### ISSUE THREAD

**Issue by DarknessWithinx** [RocketMod/Rocket#846]
I have viewed more than 3 guides on how to use Rocket plugins, but have been stumped on one part, which I have no idea how to fix. I did everything in most guides tell you, move these rocket files into Unturned_Data, and then start up your server and see blue text at the top that says something about Rocket. **BUT**, I have yet to see this "blue text" If you could offer me some help I would greatly appreciate it.

**Comment by fr34kyn01535** [comment]
The installation scheme has changed, please consult https://rocketmod.net/viewtopic.php?f=44&t=2961
