### ISSUE TITLE
Unturned mono runtime error

### ISSUE THREAD

**Issue by gegtor** [RocketMod/Rocket#847]
Soo i did everything that is shown here: https://unturned.wiki/info/tutorials/tutorial-dedicated-server/

But can't install libmono2.0-cil it says
![1](http://i.imgur.com/hsK8eJl.png)

Without it it says 
![1](http://i.imgur.com/SROkwi2.png)

Any help? :D

**Comment by fr34kyn01535** [comment]
Its not a big issue :D

**Comment by Bramdalf** [comment]
Do we need to downgrade to mono 3.12.x in order for it to run? Im running an ubuntu server 17.10, and as you may know if you try to do it yourself, downgrading mono is not easy.
