### ISSUE TITLE
Server wont start

### ISSUE THREAD

**Issue by edelin3** [RocketMod/Rocket#852]
start.sh: 33: start.sh: Syntax error: "(" unexpected

Im guessing a same and simple issue?

**Comment by computerboydude** [comment]
I guess, that you are starting your server from a start.sh file right ? 

If so there is a misplaced or unexpected ( in the code of the file.
It may be on line 33 I don't know I'm not some sort of wizard with this stuff

Have you tried running you unturned server via the shortcut method
And are you running the server with like a shutdown script or something along the lines of that?

**Comment by utkabobr** [comment]
computerboydude, you seriously? **IT IS A LINUX BASH FILE**, You can't start the linux server from the shortcut! You must use the RocketLauncher.exe(via Wine + Mono), for this you have the start.sh, that edelin3 maybe wrong edit or this is outdated version, anyway the linux server is having much bugs at this time, becouse i recommend you to setup a VM for this things
