### ISSUE TITLE
could not load rocketbridge?

### ISSUE THREAD

**Issue by adamsulaeman** [RocketMod/Rocket#855]
This happens since the update uso but failed and there is a warning could not load bridege rocket. I can not god, vanish, all its plugins I please help me

**Comment by Daniil1288** [comment]
update all yo plugins man

**Comment by sharkbound** [comment]
Seems USO has not updated to use the new way of isntalling rocketmod, i may be wrong though, i dont use USO myself

**Comment by adamsulaeman** [comment]
how??
