### ISSUE TITLE
Tons Of error in rocket plug in 

### ISSUE THREAD

**Issue by thelaws98** [RocketMod/Rocket#857]
[http://imgur.com/53U8gRu](url)

got tons of these error when starting the server with rocket plug in....
without plug in it work just fine :3

**Comment by unturnedplayer** [comment]
I'm not sure what your error is considering the link doesn't work but I get constant errors in the console as well.

The constant error that comes up during loading workshop items and even after loading the level 100%, the error that constantly appears in the console is:
MissingFieldException: Field 'SDG.Unturned.Provider.Players' not found.

**Comment by thelaws98** [comment]
`<blockquote class="imgur-embed-pub" lang="en" data-id="yRiNttB"><a href="//imgur.com/yRiNttB"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>`

**Comment by thelaws98** [comment]
![ca](https://cloud.githubusercontent.com/assets/23275994/20035193/05b1bb32-a415-11e6-8769-446d98edb76b.jpg)

**Comment by adamsulaeman** [comment]
the same since update

**Comment by fr34kyn01535** [comment]
#858
