### ISSUE TITLE
FileNotFoundException: Could not load file or assembly 'Rocket.Unturned

### ISSUE THREAD

**Issue by Matthew98405** [RocketMod/Rocket#858]
After installing the server and workshop content (on Ubuntu 16.10), installing rocketmod, then starting the server, the console gets FLOODED with errors reading

FileNotFoundException: Could not load file or assembly 'Rocket.Unturned, Version=4.9.8.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

I'm starting this using start.sh in unturned/Scripts

**Comment by Matthew98405** [comment]
It appears deleting the rocket folder and renaming the server fixed, yes, both were necessary, still an issue

**Comment by Daniil1288** [comment]
I had this error, it was caused by a plugin that wasn't working properly because it wasn't updated. I (kinda) fixed the plugin and now the error isn't present.

**Comment by gadoneitor15** [comment]
pls help installing a unturnerd server on linux plsss

**Comment by fr34kyn01535** [comment]
So is this problem still occuring? Make sure to use the new way of installing RocketMod (https://rocketmod.net/viewtopic.php?f=44&t=2961)
