### ISSUE TITLE
Command simply not  functioning

### ISSUE THREAD

**Issue by Luciano82002** [RocketMod/Rocket#859]
I updated my unturned server to the 11/4/16 update, after i did that i restarted my server and no commands were working,it didnt even show "Command not found". I typed /i 4 and it did nothing at all
I even uninstalled rocket and re-installed it and still nothing, I need help!!!!!!

**Comment by Aceheliflyer** [comment]
`/admin` and `/unadmin` is not working for me. As you said, nothing comes up at all, not even an error message. I've checked the Commands.xml and it shows that `admin` and `unadmin` is disabled. I've tried enabling it but doesn't work. You could try going in and checking to see if `/i` is enabled for you. If disabled, try enabling it. This may or may not work for you.
