### ISSUE TITLE
Rocket Permissione File

### ISSUE THREAD

**Issue by ShadowDoesYT** [RocketMod/Rocket#860]
So when I started up my server I see this https://gyazo.com/873e8d2ac17c5ec2ff67e73fe9fbd5c4
at the end it says Line 440, Position 11 but when I go there nothing is wrong not even a small word being miss spelled nothing is wrong and my friend is having the same problem with his server but at a different location does anyone know how to fix this! and due to this error no one on my server can type in chat or use commands not even an admin or basic rocket commands like /shutdown or /rocket reload

**Comment by fr34kyn01535** [comment]
You are missing a >, the error says it... https://www.xmlvalidation.com/

**Comment by ShadowDoesYT** [comment]
that's not what I'm missing because its already there and still nothing works

**Comment by Aceheliflyer** [comment]
You must be missing it somewhere else in the file.
