### ISSUE TITLE
Rocket 4.9.3.0 script and load errors

### ISSUE THREAD

**Issue by greencopper** [RocketMod/Rocket#863]
I have just downloaded 4.9.3.0.

The path for steamcmd in both start.sh and update.sh no longer matches where the files are located.

```
STEAMCMD_HOME="../../steamcmd"
```

Then further down:

```
STEAMCMD_API=$STEAMCMD_HOME/linux32/steamclient.so
```
However, linux32 is getting unzipped directly into the "Scripts" folder. And there is no longer any "steamcmd" directory.

Also it should not try to go back twice ie "../../", but just once. Once the folders has been fixed.

Anyway.. I have fiddled with the paths manually, but the Rocket mod crashes without errors:

```
Found shared workshop assets: 0
Found server workshop assets: 0
Found map assets: 0
Cleaning up...
Linking blueprints...
Linking spawns...
Loading miscellaneous...
```
And crash.. no messages, nothing.

Kind regards

**Comment by snowball7275** [comment]
It could be an issue with battleye. Try disabling it. That worked for me. This is still an issue though.

**Comment by Matthew98405** [comment]
> It could be an issue with battleye. Try disabling it. That worked for me. This is still an issue though.
How does one disable Battleye?

**Comment by Daniil1288** [comment]
@Matthew98405 open config.json; change 
`    "BattlEye_Secure": false`
(the 9th line)
