### ISSUE TITLE
Help with installation on VPS

### ISSUE THREAD

**Issue by typicalcoder** [RocketMod/Rocket#878]
This is the result of instruction screen:
![1](https://cloud.githubusercontent.com/assets/24605601/21260427/e677faa0-c396-11e6-9171-484a29a204b8.png)
Instruction:
https://github.com/RocketMod/Rocket.Unturned/blob/master/Rocket.Unturned/Scripts/Linux/README

As a result, when you run the error takes on the screenshot above. What to do?
Thanks in advance for your help!

UPD 1: 
After some manipulations with the movement of files
![2](https://cloud.githubusercontent.com/assets/24605601/21274911/88cb0dda-c3db-11e6-9fd1-f71cc061bc7b.png)
and to this end action

UPD 2:
In a detailed analysis at what stage the error occurs - it turned out that the error occurs at the time of launch RocketLauncher.EXE via MONO. The app just won't start without displaying any errors to the terminal

**Comment by fr34kyn01535** [comment]
"Need help" is not an issue

**Comment by typicalcoder** [comment]
![3](https://cloud.githubusercontent.com/assets/24605601/21284016/be5d5a54-c41f-11e6-882d-dff81b7acc11.png)

**Comment by fr34kyn01535** [comment]
For bugs this is true but it generally 'works'  on the proposed platforms.' Won't start without any errors on my vps OS 1.0 ' is not a valid bug report. I am no wizard.

**Comment by typicalcoder** [comment]
What OS you have? I understand that it works. But I pose a specific problem that I faced and try to provide as much information on this problem, what would people in the know, if you see where I could be wrong correct me. I tried to install the server on Ubuntu 12/14/16 (x86_64) and Debian 7 (x86_64). Here and there the problem persists

**Comment by fr34kyn01535** [comment]
I host 8 servers inside lxc containers on ubuntu 16 lts right now, if there was a general problem with rocket on Linux not starting I would have come across that already, I don't run any windows servers.

**Comment by typicalcoder** [comment]
Well. Thank you all the same. I have used this utility https://rocketmod.net/viewtopic.php?f=39&t=140 and everything seems to work. Now I will check
