### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by typicalcoder** [RocketMod/Rocket#881]
Hi. In the game client: loading screen hangs, the cursor hangs at center of the screen - the game starts but the game space is not displayed. When you press "Esc" the cursor can be moved to the cancel button and exit to the main menu of the game (during the release flashes the gaming space). on the server in the logs after each connection of a new player:

> [12/18/2016 5:15:26 PM] [Error] ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection. - System.Buffer.BlockCopy (System.Array src, Int32 srcOffset, System.Array dst, Int32 dstOffset, Int32 count)
> SDG.Unturned.Block.writeUInt64 (UInt64 value)
> SDG.Unturned.Block.writeSteamID (CSteamID steamID)
> SDG.Unturned.Block.write (System.Object objects)
> SDG.Unturned.Block.write (System.Object[] objects)
> SDG.Unturned.SteamPacker.write (System.Object[] objects)
> SDG.Unturned.SteamChannel.write (System.Object[] objects)
> SDG.Unturned.VehicleManager.sendVehicle (SDG.Unturned.InteractableVehicle vehicle)
> SDG.Unturned.VehicleManager.askVehicles (CSteamID steamID)
> System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
> Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
> System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
> System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
> SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
> SDG.Unturned.Provider.receiveServer (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel)
> SDG.Unturned.Provider.listenServer (Int32 channel)
> SDG.Unturned.Provider.listen ()
> SDG.Unturned.Provider.Update ()

And everyone connecting such a problem. All the maps is repeated. With any configuration servers. How to fix it?

Current plugins: Rocket->uEssentials;Uconomy;ZaupShop

**Comment by cartman-2000** [comment]
You may have some corrupted vehicle(and possibly vehicle element) save data on your server, you could try to do a vehicle reset on the server. This can be done in the wrecking ball plugin by doing /w v 10000, this would destroy/reset all the vehicles on the server.

**Comment by typicalcoder** [comment]
But it appears after you install and play a maximum of 5 minutes. While nothing in particular happens
