### ISSUE TITLE
AutomaticShutdown function seems not to be working.

### ISSUE THREAD

**Issue by Lion4K** [RocketMod/Rocket#883]
Even set it at a real low value just for testing purposes and still nothing.

`<AutomaticShutdown Enabled="true" Interval="60" />`

**Comment by fr34kyn01535** [comment]
Its not a feature anymore (Regenerate and you will figure its not being created anymore)

**Comment by Lion4K** [comment]
oh bummer, i must caught the last version featuring it.

Will be relased or revived some alternative to this? i.e. Autoshutdown2

**Comment by fr34kyn01535** [comment]
I fixed https://dev.rocketmod.net/plugins/autoshutdown2/, that should work

**Comment by Lion4K** [comment]
Awesome, happy new year!!
