### ISSUE TITLE
AutomaticShutdown

### ISSUE THREAD

**Issue by JustOneMoreBlock** [RocketMod/Rocket#889]
Hello,

It's come to our attention that `AutomaticShutdown` appears to be not functioning at all, and after a little bit of testing it's not doing any shutdown's at all since the new module system has been in place.

Log:
http://pastebin.com/raw/L4Bqr85v

Config:
http://pastebin.com/raw/ReF2d1Ei

Based on my config you can tell, I've changed it to reboot every 60 seconds, and the Permissions config updates every 30 seconds. This was updated 16 Times x 30 seconds = 8 Minutes when it should have been shut down within the first 60 seconds.

Can anyone else confirm this issue? I've reset all configs, and I'm using the latest version of RocketMod.

Kind Regards,
Cory

**Comment by JustOneMoreBlock** [comment]
Reset all config files, and changed the `Rocket.config.xml` file.

```
  <AutomaticShutdown Enabled="true" Interval="10" />
```

It says it's going to `shut down` in 10 Seconds. However, the time says 8:33:30 PM UTC. The time is correct based on time zones; this isn't an issue.

http://i.imgur.com/Xs6zlXJ.png

This doesn't save and shut down properly.

Using latest rocket.

Please fix this.

**Comment by JustOneMoreBlock** [comment]
Would like an update on this and this causes more issues than you think.

Specifically, if a server doesn't save/shutdown correctly, then users will be unable to join that server because of an improper save/shutdown. Then I have to go in manually fix this issue.

**Comment by JustOneMoreBlock** [comment]
This is still an issue, hardly any players can join because of an improper shutdown.

**Comment by JustOneMoreBlock** [comment]
Do you need more information?

Please fix

**Comment by fr34kyn01535** [comment]
This feature has been removed, there are plugins that do that.
