### ISSUE TITLE
Error Loading rocket

### ISSUE THREAD

**Issue by GaleguinhoCakeHud** [RocketMod/Rocket#891]
NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.Provider.openGameServer ()
SDG.Unturned.Provider.host ()
SDG.Unturned.Assets+<init>c__Iterator0.MoveNext ()
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress)

NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.Provider.listenClient (Int32 channel)
SDG.Unturned.Provider.listen ()
SDG.Unturned.Provider.Update ()

This happens after loading miscellaneous. I really dont know what to do. I updated my server multiple times with unturned's files and rocket's files. (Unturned version 3.17.12.1. Rocket's build 1143). This happen if I dont put any workshop map. Example: Map RP GTF (doesn't work if i put it). Map PEI (Work)

**Comment by cartman-2000** [comment]
Does the server startup on the map when you run it without rocket?

**Comment by GaleguinhoCakeHud** [comment]
I already solve it, apparently the rocket is not loading with the "broken" map in workshop. I have no ideia why this happen. I never have seen this before...

**Comment by cartman-2000** [comment]
It is possible for workshop issues to halt the server from loading, there isn't really any error handling for this in unturned, so it can be somewhat cryptic as to what the issue is.
