### ISSUE TITLE
Plugins loading twice in newer rocket updates.

### ISSUE THREAD

**Issue by cartman-2000** [RocketMod/Rocket#893]
The plugins on the server will load twice when you startup the server, which may mess up some of the plugins.

Edit: Apparently it's the commit that allows plugins to be loaded from sub directories that causes that. As I'm running the servers on windows, so I can't replace plugin dll's without shutting down the server first, but they can be moved, so I end up moving the old dll to a sub directory to replace it(To spend as little time as possible to have the server down when updating plugins.). I wonder if you can make it so that it prioritizes plugins in the top level plugin directory first, then ignores plugins in the sub directories if they have the same plugin name as the ones that were previously loaded.

**Comment by JustOneMoreBlock** [comment]
or just remove it as I see no need for subdirectory plugins.
