### ISSUE TITLE
- Feature Request: Prefix/Suffix

### ISSUE THREAD

**Issue by JustOneMoreBlock** [RocketMod/Rocket#894]
Hello,

I'm requesting for a feature that has been brought to my attention, and I'm not sure if one the options are possible.

- A command to remove the "Prefix and Suffix" from a name.
Scenario: A staff rank is in the game and is in vanish. However, the rank can still be seen on the player's list, and catching anyone is harder when using ranks.

- Add into the vanish command to either do the scenario above or remove the rank and staff member from the player list.

**Comment by fr34kyn01535** [comment]
Since prefixes are pretty static right now that wont happen ...
