### ISSUE TITLE
steamcmd can't install unturned

### ISSUE THREAD

**Issue by gegtor** [RocketMod/Rocket#895]
I'm trying to install unturned on my VPS using this guide https://github.com/RocketMod/Rocket.Unturned/blob/master/Rocket.Unturned/Scripts/Linux/README

And everything is going well but steamcmd app_update freezes it looks like this http://imgur.com/a/DqDEQ

What i tried
 -Starting from scratch many times (reinstalling ubuntu, steamcmd etc)
 -Looking for answer on google (you are my last resort)
 -Trying different steam accounts

My VPS specs:
OS: Ubuntu 14.04 server 64bit
CPU: 1 vCore 3,1 ghz
RAM: 4 GB
SSD: 25 GB
Network: 100mb/s up & down

**Comment by mrzack506** [comment]
I use Windows 10,

what I tried;
- Made a new folder called "unturned server number two"
- Extracted the rocket zip
- Ran "start.bat" (as myfirstrocketserver.bat doesn't install it)
- Waited for SteamCMD to finish.
- Once it finished, I checked if unturned was in the folder(surprise! It wasn't!)
- I tried running "update.bat" after on a new folder.
same thing!!!
I already have 1 server running in the unturned game directory, but I want two, so I want to install it in an external folder.

**Comment by cartman-2000** [comment]
You should leave the SteamCMD client to do its thing in the initial install of the server. It will take a while to install as there's some 50k+ files in the Unturned server and the SteamCMD app is extremely inefficient at writing out many small files. In some cases it can take over an hour to install the server, even on a SSD drive. I believe that the SteamCMD client updates the files pretty much one at a time(with a queue depth of 1.) waiting for the other files to flush out of the cache first, this is pretty much the worst case scenario for SSD write performance.

As for running multiple servers, you can do that off the same server base if you want the base bundle configs to be the same for both server's, all you would need to do is make a startup script that starts the server with a different instance id than the first server. You would be able to set up the configs for the second server after trying to run it once on the new instance id. However if you run two or more servers on the same base install then all of those servers will need to be shutdown for you to be able to update the server base.

**Comment by mrzack506** [comment]
@cartman-2000 Would i edit something in the shortcut? like adding "-instance" or something like that?

**Comment by cartman-2000** [comment]
you'd put this in the startup command.
+internetserver/instance_name

**Comment by TheSkyes** [comment]
hi i have sort of the same problem i made the folder i put the steamCMD in the folder and i installed it but if i do:
force_install_dir .\unturned\app_update 304930

it does nothing it just goes to a new line and i can type again pls some one help and why is this now the only way to make a unturned server

TheSkyes

**Comment by papershredder432** [comment]
> hi i have sort of the same problem i made the folder i put the steamCMD in the folder and i installed it but if i do:
> force_install_dir .\unturned\app_update 304930
> 
> it does nothing it just goes to a new line and i can type again pls some one help and why is this now the only way to make a unturned server
> 
> TheSkyes

Use this batch instead.
steamcmd +login anonymous +force_install_dir INSTALL_DIRECTORY +app_update 1110390 validate +quit

And good job reviving an over 2 year, 9 month old post.

**Comment by TheSkyes** [comment]
thx XD this was the only sort of thing that i could find on google XD

**Comment by gegtor** [comment]
@TheSkyes Check out my scripts

https://github.com/gegtor/Unturned-64Bit-Server-Scripts

**Comment by TheSkyes** [comment]
can i install this?

**Comment by gegtor** [comment]
They work great try them

**Comment by TheSkyes** [comment]
just extract them to somewehere and install or something
