### ISSUE TITLE
Hello, how to compile?

### ISSUE THREAD

**Issue by Sergeant13377** [RocketMod/Rocket#898]
i wan't rewrite your code, and compile him, but i have an error.
Серьезность	Код	Описание	Путь	Файл	Строка	Проект	Состояние подавления
Ошибка		выход из команды "..\..\nuget\nuget.exe pack Rocket.Unturned.nuspec -Version 4.9.3.0" с кодом 1.	C:\Users\Sergey\Desktop\Rocket.Unturned-master\Rocket.Unturned	C:\Users\Sergey\Desktop\Rocket.Unturned-master\Rocket.Unturned\Rocket.Unturned.csproj	182	Rocket.Unturned	
help pls.

**Comment by fr34kyn01535** [comment]
I would assume nuget is not where it should be, how about download the full repo?
