### ISSUE TITLE
Error on linux

### ISSUE THREAD

**Issue by eutherin** [RocketMod/Rocket#899]
Trying to get a server running on linux, but it seems to error out whenever I do:
"4. Start the server, pick any single word as unique instance name
    screen -S <instance name>
    cd ~/Scripts
    ./start.sh <instance name>"
http://pastebin.com/kAjM7v7B

Am I missing something somehwere? I tried installing mono complete using apt get but it doesn't seem to have resolved the problem.

**Comment by fr34kyn01535** [comment]
Sorry rocket does not run on kernels.

**Comment by eutherin** [comment]
Is it specifically ubuntu it doesnt run on, or am I missing something else?

You still have links for it on your website...
https://rocketmod.net/get-rocket#

here's the linux directions you gave the 11th of nov
https://github.com/RocketMod/Rocket.Unturned/blob/master/Rocket.Unturned/Scripts/Linux/README

**Comment by fr34kyn01535** [comment]
I tried those scripts today and everything works fine. I am sorry, what I originally ment was that I can't help you with 'doesn't run on Linux'. It does. Check out discord or our forum to get support.
