### ISSUE TITLE
Update RocketMod Unturned to 3.18.0.0 Hawaii update

### ISSUE THREAD

**Issue by SmallSansSerif** [RocketMod/Rocket#901]
Please update to new version when possible.

**Comment by Koennn** [comment]
Right now, when loading up Hawaii on the server everything seems to run fine, but on the client we're getting the message 'This server is using a modified version of the map', but we're not... Please update asap, thanks!

**Comment by Lenti99** [comment]
I get the same output 'This server is using a modified version of the map' However I've seen some servers having plugins and the hawaii map works perfect. So it's kinda weird

**Comment by Koennn** [comment]
Yes, after some testing it seems to work fine on a Windows server, but on a Linux (Ubuntu 14.04) it seems to give the 'This server is using a modified version of the map' error.

**Comment by Lenti99** [comment]
Same here, i run the server on Ubuntu 14.04 and it gives that error. Weird.

**Comment by unturnedplayer** [comment]
Same error here.  I also see the following error in the console: "Failed to generate an item with ID 0 from type 25!"

**Comment by Koennn** [comment]
Yes, having that too, please fix soon, my players are waiting.

**Comment by jatapa2** [comment]
is this fixed yet?

**Comment by jatapa2** [comment]
god dam it just fix it cant be so hard

**Comment by jatapa2** [comment]
new build but stull broken

**Comment by Lenti99** [comment]
Lol, this is funny. I thought rocket is suppost to be a good launcher thingy. Seems like they are lazy

**Comment by jatapa2** [comment]
yeap

**Comment by SmallSansSerif** [comment]
@jatapa2 @Lenti99 attacking the devs or insulting them personally doesn't seem to help us get a fix any faster.

**Comment by jatapa2** [comment]
ik that xD

**Comment by jatapa2** [comment]
just saying that it cant be so hard when they have done this for a long time now

**Comment by Lenti99** [comment]
@SmallSansSerif It wasn't a insult. It was an honest opinion about rocket.

**Comment by jatapa2** [comment]
Would be nice to get fix today

**Comment by jatapa2** [comment]
Please

**Comment by fr34kyn01535** [comment]
This is an Unturned issue, so this bug tracker is not the right to report this.
I've investigated this issue with Nelson, seems to be related to the creators of Hawaii wildly using upper and lowercase, not having in their mind that Linux is case sensitive and windows isn't. Its high prio for Nelson, we will probably see a fix soon...

**Comment by darkphan** [comment]
I have found a fix/workaround for this. You simply need to set an environment variable before launching rocket, in my case in bash I did:

export MONO_IOMAP=all

Then ran ./start.sh test

And users are able to connect to my linux based server running the hawaii map

**Comment by fr34kyn01535** [comment]
Not really a fix but nice workaround!

**Comment by SmallSansSerif** [comment]
Amazing. I can confirm it works in my case. 

http://www.mono-project.com/docs/advanced/iomap/
