### ISSUE TITLE
Error while compiling generated serializer

### ISSUE THREAD

**Issue by encloinc** [RocketMod/Rocket#906]
Error while compiling generated serializer
/tmp/7e5a5440/6c789d.cs(27,36) : error CS0012: The type Rocket.API.IDefaultable' is defined in an assembly that is not referenced. Consider adding a reference to assemblyRocket.API, Version=2.6.4.0, Culture=neutral, PublicKeyToken=null'
(0,0) : error : /root/Modules/Rocket.Unturned/Rocket.Core.dll (Location of the symbol related to previous error)
'

Weve tried skipping the error, the server just abruptly stops. We are using ubuntu 14.04.

**Comment by MooShoe** [comment]
Same. The devs really need to get around this.

**Comment by pepperkick** [comment]
Same issue here as well, using Debian 8.7

**Comment by fr34kyn01535** [comment]
The server crash is NOT cause of that error. I am getting this on any machines running rocket..

**Comment by dhm-msd** [comment]
Same issue here, on ubuntu 1204

**Comment by Trojaner25** [comment]
This bug does not affect the server in any way.
