### ISSUE TITLE
Bugs on Ubuntu

### ISSUE THREAD

**Issue by mssc89** [RocketMod/Rocket#908]
Hi there!
Like a month ago, i was hosting a server, everything was working like a charm. But today, i have TRIED to install server on my Ubuntu 16.04 machine according to https://unturned.wiki/info/tutorials/tutorial-dedicated-server/ . Server starts up, shows on server list, but its very buggy. At first, bullets cant kill zombies, only drive-by or explosion can kill them. Additionally, character is sometimes flickering when sprinting or jumping, when im in the water or using an umbrella, it gets even worse. Im flickering even more and i cant even move. Sometimes i manage to move like 2 metres, but then i stop. I even manage to stay in the air in a place. I have like 90ping, debug shows: Updates per second: 120%
Ticks per second: 100%. I tried installing ubuntu 14, the same, back to 16 and then using mono-complete in place of mono-reference-assemblies-2.0, mono-devel and libmono-cil-dev. Still the same. Any fix? ANY?

**Comment by TheGraff** [comment]
Hi, we have the same problem, we do not know how to solve it, we tried everything, the problem either in the client or in the rocket, even ideas on the package, we think that there may be a problem in mono, but we do not know how to put the version older. If you learn something, tell us, or if we find out we will let you know.

**Comment by withkeygames** [comment]
I have the same problem....i try all and try differents instructions but nothin help...

**Comment by Trojaner25** [comment]
Is this reproduceable without rocket?

**Comment by fr34kyn01535** [comment]
We have a guide on this website that works. We can't support other guides.
