### ISSUE TITLE
Plugins aren't working at all

### ISSUE THREAD

**Issue by Kolop98** [RocketMod/Rocket#911]
New to rocket mod so forgive me, I put the .dll files into the plugins folder, started the server then shut it down, and the folders for the plugins don't generate and the commands related to the plugins I tried to use won't work

**Comment by Tortellio** [comment]
what are the plugins

**Comment by Trojaner25** [comment]
Have you installed Rocket at all?

**Comment by Kolop98** [comment]
I have the module filed installed, and the server says it's running rocket when I launc hand the default rocket commands work. The plugins are Sayas and AdvancedChatControl. Neither of them work

**Comment by Kolop98** [comment]
Fixed it on my own, all good
