### ISSUE TITLE
Random Errors?

### ISSUE THREAD

**Issue by Chickenw** [RocketMod/Rocket#914]
Not sure whats causing these errors. But the pop up a lot recently.
[3/28/2017 4:32:31 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.UseableBarricade.equip ()
SDG.Unturned.PlayerEquipment.tellEquip (CSteamID steamID, Byte page, Byte x, Byte y, UInt16 id, Byte newQuality, System.Byte[] newState)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.SteamChannel.send (ESteamCall mode, ESteamPacket type, Int32 size, System.Byte[] packet)
SDG.Unturned.SteamChannel.send (System.String name, ESteamCall mode, ESteamPacket type, System.Object[] arguments)
SDG.Unturned.PlayerEquipment.tryEquip (Byte page, Byte x, Byte y, System.Byte[] hash)
SDG.Unturned.PlayerEquipment.askEquip (CSteamID steamID, Byte page, Byte x, Byte y, System.Byte[] hash)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.Provider.receiveServer (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel)
SDG.Unturned.Provider.listenServer (Int32 channel)
SDG.Unturned.Provider.listen ()
SDG.Unturned.Provider.Update ()
 
[3/28/2017 4:32:35 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.UseableBarricade.equip ()
SDG.Unturned.PlayerEquipment.tellEquip (CSteamID steamID, Byte page, Byte x, Byte y, UInt16 id, Byte newQuality, System.Byte[] newState)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.SteamChannel.send (ESteamCall mode, ESteamPacket type, Int32 size, System.Byte[] packet)
SDG.Unturned.SteamChannel.send (System.String name, ESteamCall mode, ESteamPacket type, System.Object[] arguments)
SDG.Unturned.PlayerEquipment.tryEquip (Byte page, Byte x, Byte y, System.Byte[] hash)
SDG.Unturned.PlayerEquipment.askEquip (CSteamID steamID, Byte page, Byte x, Byte y, System.Byte[] hash)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.Provider.receiveServer (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel)
SDG.Unturned.Provider.listenServer (Int32 channel)
SDG.Unturned.Provider.listen ()
SDG.Unturned.Provider.Update ()

[3/28/2017 4:32:39 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.UseableBarricade.equip ()
SDG.Unturned.PlayerEquipment.tellEquip (CSteamID steamID, Byte page, Byte x, Byte y, UInt16 id, Byte newQuality, System.Byte[] newState)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.SteamChannel.send (ESteamCall mode, ESteamPacket type, Int32 size, System.Byte[] packet)
SDG.Unturned.SteamChannel.send (System.String name, ESteamCall mode, ESteamPacket type, System.Object[] arguments)
SDG.Unturned.PlayerEquipment.tryEquip (Byte page, Byte x, Byte y, System.Byte[] hash)
SDG.Unturned.PlayerEquipment.askEquip (CSteamID steamID, Byte page, Byte x, Byte y, System.Byte[] hash)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.Provider.receiveServer (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel)
SDG.Unturned.Provider.listenServer (Int32 channel)
SDG.Unturned.Provider.listen ()
SDG.Unturned.Provider.Update ()
 

[3/28/2017 4:32:47 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.UseableBarricade.equip ()
SDG.Unturned.PlayerEquipment.tellEquip (CSteamID steamID, Byte page, Byte x, Byte y, UInt16 id, Byte newQuality, System.Byte[] newState)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.SteamChannel.send (ESteamCall mode, ESteamPacket type, Int32 size, System.Byte[] packet)
SDG.Unturned.SteamChannel.send (System.String name, ESteamCall mode, ESteamPacket type, System.Object[] arguments)
SDG.Unturned.PlayerEquipment.tryEquip (Byte page, Byte x, Byte y, System.Byte[] hash)
SDG.Unturned.PlayerEquipment.askEquip (CSteamID steamID, Byte page, Byte x, Byte y, System.Byte[] hash)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.Provider.receiveServer (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel)
SDG.Unturned.Provider.listenServer (Int32 channel)
SDG.Unturned.Provider.listen ()
SDG.Unturned.Provider.Update ()

[3/28/2017 4:32:50 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.UseableBarricade.equip ()
SDG.Unturned.PlayerEquipment.tellEquip (CSteamID steamID, Byte page, Byte x, Byte y, UInt16 id, Byte newQuality, System.Byte[] newState)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.SteamChannel.send (ESteamCall mode, ESteamPacket type, Int32 size, System.Byte[] packet)
SDG.Unturned.SteamChannel.send (System.String name, ESteamCall mode, ESteamPacket type, System.Object[] arguments)
SDG.Unturned.PlayerEquipment.tryEquip (Byte page, Byte x, Byte y, System.Byte[] hash)
SDG.Unturned.PlayerEquipment.askEquip (CSteamID steamID, Byte page, Byte x, Byte y, System.Byte[] hash)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.Provider.receiveServer (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel)
SDG.Unturned.Provider.listenServer (Int32 channel)
SDG.Unturned.Provider.listen ()
SDG.Unturned.Provider.Update ()

**Comment by Trojaner25** [comment]
All errors are caused by Unturned, this is not a rocket bug
