### ISSUE TITLE
Can't publish

### ISSUE THREAD

**Issue by crackhourrocket** [RocketMod/Rocket#915]
Sorry if this is the wrong place to post this, but I see no other way to reach the rocket mod team:

I've tried several times to register at dev.rocketmod.net/plugins to register and I never get my activation email with password. I've checked my junk mail folder and there is nothing. I tested sending emails to my email account and it works fine. In addition i tried signing up to post on the rocket mod forums and even that keeps saying I will get an activation email but it never comes. 

I want to publish my plugin so I can use it on my hosted server. The host company won't allow it unless it's published.

Thanks for any help.

**Comment by fr34kyn01535** [comment]
Please contuct us in the discord to sort this out.

**Comment by crackhourrocket** [comment]
Well I can't post on discord to you either because it says I need to verify my email to post and I can't verify my email unless I get an email which i never do.
