### ISSUE TITLE
IRocketPermissionProvider lacks information about the default group

### ISSUE THREAD

**Issue by persiafighter** [RocketMod/Rocket#916]
As the title says, IRocketPermissionProvider lacks that information.
Edit: Also, the constructor for `new RocketPermissionsGroup()` could have Prefix and Suffix as well.

**Comment by Trojaner25** [comment]
RocketPermissionsGroup should not contain Prefix or Suffix. Its a provider implementation detail which should not be forced on all providers

**Comment by fr34kyn01535** [comment]
#1007
