### ISSUE TITLE
Encryption failure when using HTTPS for webperms or web configs

### ISSUE THREAD

**Issue by westonhowe98** [RocketMod/Rocket#917]
This issue is caused by mono not trusting any certificates by default. However, since only the owner of a server is able to set the URL for permissions and configs it should never be a security issue. I actually got it working on a local copy of rocket: https://pastebin.com/u84Vy7Je that's the only class I changed.

**Comment by fr34kyn01535** [comment]
That will disable certificate checking completely. You might also just add the root ca to the trusted ca's of the os.
