### ISSUE TITLE
massive dc while certain players joining the server

### ISSUE THREAD

**Issue by citrusky** [RocketMod/Rocket#919]
Dear developers:
I've created a group called "mod" in Permissions.config.xml and added my admins in it.
But recently something weird happened.

Whenever one of my admins join the server.
Lots of players will dc right away without a notice.

I've checked the console many times and there were no error at all.
Just showing an admin connected to the server, and lots of players disconnected. That's all.

Do you guys ever got this kind of report before?
Thanks for your time and help.
We enjoy Rocket a lot!

    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Prefix />
      <Suffix />
      <Color>white</Color>
      <Members />
      <Permissions>
        <Permission Cooldown="0">home</Permission>
        <Permission Cooldown="0">kits</Permission>
        <Permission Cooldown="0">kit.new</Permission>
        <Permission Cooldown="0">kit.sup</Permission>
        <Permission Cooldown="0">kit.base</Permission>
        <Permission Cooldown="0">kit.car</Permission>
        <Permission Cooldown="0">kit.sky</Permission>
        <Permission Cooldown="0">kit.sea</Permission>
        <Permission Cooldown="0">tpa</Permission>
        <Permission Cooldown="0">tpa.a</Permission>
        <Permission Cooldown="0">tpa.accept</Permission>
        <Permission Cooldown="0">tpa.send</Permission>
        <Permission Cooldown="0">rules</Permission>
        <Permission Cooldown="0">discord</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>mod</Id>
      <DisplayName>Mod</DisplayName>
      <Prefix />
      <Suffix />
      <Color>#3EEAF9</Color>
      <Members>
        <Member>76561198133312365</Member>
        <Member>76561198032306050</Member>
      </Members>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">tp</Permission>
        <Permission Cooldown="0">tphere</Permission>
        <Permission Cooldown="0">v</Permission>
        <Permission Cooldown="0">kit.flag</Permission>
        <Permission Cooldown="0">kit.wp</Permission>
        <Permission Cooldown="0">kit.party</Permission>
        <Permission Cooldown="0">spy</Permission>
        <Permission Cooldown="0">mute</Permission>
        <Permission Cooldown="0">unmute</Permission>
        <Permission Cooldown="0">jail</Permission>
        <Permission Cooldown="0">heal</Permission>
        <Permission Cooldown="0">wreck.*</Permission>
        <Permission Cooldown="0">w.*</Permission>
        <Permission Cooldown="0">checkowner</Permission>
        <Permission Cooldown="0">god</Permission>
        <Permission Cooldown="0">tpto</Permission>
        <Permission Cooldown="0">afk.prevent</Permission>
        <Permission Cooldown="0">kick</Permission>
      </Permissions>
    </Group>

**Comment by Trojaner25** [comment]
I don't  think this is rocket related...

**Comment by citrusky** [comment]
@Trojaner25 Thanks for the comment. I'll check my plugins one by one.

**Comment by cartman-2000** [comment]
If you have some plugins that use a MySQL database, you should make sure that the plugins are using a database server that is hosted on the machine that the game server is running on(to have the lowest latency to the database server as possible.), as most plugin database access would halt the main thread when it's waiting for a reply to a database query. A laggy database connection is one of the issues that could cause issues for a server if there are multiple plugins that need to access a database when someone connects to the server.

One other possible issue is that you have the server timeout value set to something that is too small, and whatever latency spike that may happen as someone connects is booting other players off of the server.

**Comment by citrusky** [comment]
@cartman-2000 
I didn't have any plugin with MySQL.
And I also set no timeout for players on my servers.

I do have some script to check a player's buildable elements when they join the server.
Somehow this issue got fixed after I stop scanning a certain group.
And it's weird that only 1 of my servers had this problem.

Thanks for your reply and help. : )

**Comment by cartman-2000** [comment]
The scanning of elements on the server can be slow depending on how the scanning was coded, if it took too much time to scan elements(If there was "a lot" of elements.), it could dc players, as most plugin operations are still single threaded(it would block the main server thread while it's running.). Element scanning is an iterative process that can iterate up to or over 15-30k times(depending on the number of elements on the server.), if it had to scan through all the elements on the server, so it would be important that the element scanning process be as efficient as possible.
