### ISSUE TITLE
Every time i Teleport my game freezes and the server looses my connection

### ISSUE THREAD

**Issue by dunbullyme7** [RocketMod/Rocket#920]
Everytime i tp/warp in my server my game freezes i checked the logs and this was spamming 

ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
System.Collections.Generic.List`1[SDG.Unturned.ZombieCloth].get_Item (Int32 index)
SDG.Unturned.ZombieClothing.apply (UnityEngine.Transform zombie, UnityEngine.SkinnedMeshRenderer renderer_0, UnityEngine.SkinnedMeshRenderer renderer_1, Byte type, Byte shirt, Byte pants, Byte hat, Byte gear, UnityEngine.Transform& attachmentModel_0, UnityEngine.Transform& attachmentModel_1)
SDG.Unturned.Zombie.apply ()
SDG.Unturned.Zombie.start ()
SDG.Unturned.Zombie.init ()
SDG.Unturned.ZombieManager.addZombie (Byte bound, Byte type, Byte speciality, Byte shirt, Byte pants, Byte hat, Byte gear, Byte move, Byte idle, Vector3 position, Single angle, Boolean isDead)
SDG.Unturned.ZombieManager.tellZombies (CSteamID steamID)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.Provider.receiveClient (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel)
SDG.Unturned.Provider.listenClient (Int32 channel)
SDG.Unturned.Provider.listen ()
SDG.Unturned.Provider.Update ()

[18:24:34 - 20/04/2017] Steam: onInventoryResultReady: Drop 0

This is the Game logs not the server if anyone is confused

and there was absolutely nothing in the server logs they just leave due to game freezing

**Comment by Trojaner25** [comment]
Unturned issue
