### ISSUE TITLE
OnJoinRequested called on disconnect

### ISSUE THREAD

**Issue by Trojaner25** [RocketMod/Rocket#922]
For some reasons OnJoinRequested is called when a player leaves a server. Confirmed by @Freenex1911 and me.
Might be an Unturned / Steamworks bug.

Needs investigation and maybe a hacky bugfix (e.g. check if player is still online before calling the event)

**Comment by xdlewisdx** [comment]
So is this confirmed to be a Unturned bug? if someone could have a look into it and confirm 100% its Unturned will hand it off to Nelson

**Comment by Trojaner25** [comment]
Issue has been moved to Unturned issue tracker.

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/75
