### ISSUE TITLE
Need some help with a rocket error

### ISSUE THREAD

**Issue by kakanunes** [RocketMod/Rocket#923]
I got this error while opening up my Rocket server:
[Exception] Rocket.Unturned >> Exception in <initialize>m__1: System.Exception: Failed to deserialize XMLFileAsset: Rocket.Unturned.config.xml ---> System.FormatException: Input string was not in the correct format

I know the error is in the rocket.unturned.config.xml but i dont know what is wrong!

MY Rocket.unturned.config.xml configuration:
[log.txt](https://github.com/RocketMod/Rocket/files/966827/log.txt)

**Comment by Trojaner25** [comment]
Your Rocket.Unturned.config.xml is malformed. Delete it or use an xml validator to find the error

**Comment by kakanunes** [comment]
It says "No errors were found"(xml validation)
