### ISSUE TITLE
Multiple servers on 1 host - linux

### ISSUE THREAD

**Issue by gegtor** [RocketMod/Rocket#926]
Hi guys i really like how your Linux scripts work :D good job!

I have really powerful server with Ubuntu 16.04 and im wondering if it's possible to create more than 1 server per host on the same IP just with different port

Currently when I'm trying to launch 2 servers at once second fails to boot

**Comment by Trojaner25** [comment]
Please fill the template when creating a new issue.

**Comment by RechtVH** [comment]
You can and it sounds like you have not changed the port of the second server.  I have a good host machine and run 6 servers off it fine, in the Servers folder Command.dat file change the port per server and you should be fine, remember to use screen per instance.

Good luck and have fun

Recht van Huyssteen

**Comment by gegtor** [comment]
Thanks Reckt :D 

Issue was already resolved #927
