### ISSUE TITLE
2 or more servers on the same host - Linux

### ISSUE THREAD

**Issue by gegtor** [RocketMod/Rocket#927]
**What problem did you noticed?**
I can't launch 2 servers simultaneously

**What is the expected result?**
2 or more working servers on the same IP with different port

**What is the current result?**
Second server fails to boot
Probably some Mono issue

**How to reproduce the issue?**
1.Create Linux server using guide on wiki
2Create second server using new user account
3.Launch first server
4.Try to launch second server

Operating System and Version: Ubuntu 16.04

Unturned Version: 3.18.12.0

Rocketmod Version: 4.9.3.0

**Comment by Trojaner25** [comment]
Please upload your output_log.txt and your Rocket.log, so we can try to find the issue.

**Comment by gegtor** [comment]
I'm soo sorry that issue was probably resolved 

Last time i tried to do that it didn't worked

Now when i did it to reproduce issue and give you logs it worked fine :D

**Comment by Trojaner25** [comment]
Ok. If it happens again feel free to reopen

**Comment by gegtor** [comment]
Okay :D 

Thanks
