### ISSUE TITLE
Unturned rocket server, all plugins suddenly don't work

### ISSUE THREAD

**Issue by Toady8** [RocketMod/Rocket#930]
Hi, this is my first time using this website, so sorry if i do something wrong. I am running an unturned server with rocket and also with alot of plugins like kits, tpa and alot more. Everything worked well for a while now. Yesterday i installed a plugin that allows you to restart the server by just typing restart in server console. I typed restart and the server just crashed and then something popped up and it didn't respond and so i just closed everything. I turned my server back on and all of a sudden, every single rocket plugin didn't work. There was errors everywhere in the console. Only two plugins worked: it was the SimpleDeathMessages plugin and the Join/Leave messages plugin. Every other plugin had an error that started with : 

NullReferenceException: Object reference not set to an instance of an object - Rocket.core.commands.RocketCommandManager.Register
and so on about priority and failing to load or something. Thats the same with every plugin except for SimpleDeathmessages. I have no idea what to do. I googled it, no result. I reinstalled rocket and then reinstalled every single plugin, doesn't work. Players can join my server. Another thing is that i cannot shutdown the server with typing 'shutdown', i can't manually save, basically i can't do anything with the server console, I can't teleport people or kill people or use the say "text" command or anything. If somebody could help me it would be greatly appreciated.

**Comment by Trojaner25** [comment]
Delete Commands.config.xml
