### ISSUE TITLE
Can't Connect to Server, Server not Writing Rocket.log

### ISSUE THREAD

**Issue by MustyC** [RocketMod/Rocket#931]
It is currently 9:07 PM. I've restarted my Unturned server, hosted on Ubuntu Linux 16.04, at least at least two dozen times today. It starts, reading 
Steam: UP TO DATE

WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319

Followed by nothing. I'm fairly certain it's supposed to begin an output of loading the assets. I've looked in 
/Rocket/Logs time and time again, and the only Rocket.log file was written at 5:22 PM, almost 4 hours ago. I'd be more than happy to provide files, but I'm not sure what would really be useful beside the Rocket.log, which unfortunately doesn't exist.

**Comment by RechtVH** [comment]
I also use Ubuntu and had the same issue a few times, i found that if you re-download the rocket mod files and replace the modules folder again, and the exe the seems most times to sort that out, else backup the server files and reinstall from scratch, i have had to do that a few times.  Hope you come right and good luck.

**Comment by Trojaner25** [comment]
Please post content of output log

**Comment by Trojaner25** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Overriding commands](https://trello.com/c/Y4xA4Mys/1-overriding-commands)
