### ISSUE TITLE
Make Rocket.Unturned only work with the Unturned it was compiled with

### ISSUE THREAD

**Issue by fr34kyn01535** [RocketMod/Rocket#938]
This is for enforcing Rocket.Unturned to be up to date

**Comment by system86** [comment]
Fuck no.
People update on their own time, not adding to the already 30 minute update time for my server.

**Comment by Trojaner25** [comment]
Rocket has a script for updating it automatically

**Comment by fr34kyn01535** [comment]
I really don't see a reason for this. We should focus on other ways of getting people to a newer version.
