### ISSUE TITLE
Missing 'Rocket' File

### ISSUE THREAD

**Issue by ghost** [RocketMod/Rocket#942]
Windows 7 - 7Zip File

Unturned Version: 3.19.0.0

Rocketmod Version: 4.9.3.0

   To be fair, I'm not very knowledgeable of Rocket. However, while I was following the wiki it came to my attention that there was no file named 'rocket' when I downloaded the latest version with 7Zip. 

        I.e: Servers\<Instance>\**Rocket**\Plugins 

   The only files I download are 'Modules' and 'scripts' none of which lead to a 'Plugins' folder. Maybe I'm just an idiot here, but I really have no idea. If someone could open my eyes, I'd be very grateful. Thanks!

**Comment by persiafighter** [comment]
The install instructions in the wiki mention nothing of the plugins folder. The wiki states:

> Download & Install
> 
> Download the latest Rocket from here and unzip it into the Unturned folder. Start the Unturned 3 server because Rocket will create files and directories that you'll need.

What you were most likely looking at was the plugin install section of the wiki, which states:

> Installation of additional Plugins
> 
> You can get additional plugins here. Place the plugins and any libraries into the folder
> 
> Servers\\\<Instance>\Rocket\Plugins
> Note: A Plugin creates a directory containing configuration file(s) when Rocket loads the plugin.
> Note: Rocket can load plugins without restarting the server. Simply type rocket load <Plugin> in the CLI.
