### ISSUE TITLE
Staff commands not working.

### ISSUE THREAD

**Issue by Mittenz4** [RocketMod/Rocket#945]
My friend and I have reinstalled rocket more then 7 times trying to fix the issue of us suddenly losing our admin privileges even though the game still counts us as staff. Help.

**Comment by gingayt** [comment]
Im having the same issue

**Comment by system86** [comment]
![errors](https://user-images.githubusercontent.com/26826363/27532907-5f19ee56-5a27-11e7-9357-a5cd1e1b6396.PNG)
are you getting this error?

**Comment by gingayt** [comment]
Yes. That is it

**Comment by xdlewisdx** [comment]
Your permission file is stuffed up... Please upload it to https://pastebin.com

**Comment by Trojaner25** [comment]
Your permissions file is broken. Please delete or fix it (use a XML validator to check whats wrong)
Not a Rocket issue.
