### ISSUE TITLE
Commands Do Absoultey Nothing

### ISSUE THREAD

**Issue by gingayt** [RocketMod/Rocket#947]
After changing the map of my server to washington and adding permisions and changing so zombies dont spawn on the map. When i type commands on the server i get zero feedback. Nothing. It dosent say command not found. It says nothing. All i see is a bunch of red messages on the concole i dont quite understand... Someone please help

**Comment by xdlewisdx** [comment]
RocketMod is probably not installed.

**Comment by Trojaner25** [comment]
Missing issue template, create new issue and fill it out
