### ISSUE TITLE
KICKED FROM MY SERVER BECAUSE of UNOFFICIAL MODELS CAUSE BY ROCKET

### ISSUE THREAD

**Issue by fadedfragger** [RocketMod/Rocket#949]
**I get kicked from my server after while saying "kicked because of unofficial models?**

**When i install rocket , i have to replace the modules folder, and i think that folder is needed to run the rocket server, but "rocket.unturned" which is on the modules folder makes me getting kicked, yes and I tried to remove the rocket.unturned and removing i stop getting kicked but that way i cant own a rocket server?**

**Comment by persiafighter** [comment]
You can own a rocket server... the only thing you have to do is make a copy of the local game data and then install rocket & host from that separate copy...
