### ISSUE TITLE
Unknown errno: Bad address

### ISSUE THREAD

**Issue by greencopper** [RocketMod/Rocket#950]
This is with the Linux version 4.9.3.0 build 919.

The first time the `start.sh` script is run everything works fine. The second time the script is run, after being shutdown, the following error appears and the server cannot run:

```
Unknown errno: Bad address

Unknown errno: Bad address

Unknown errno: Bad address
```

Doing a stacktrace:

```
Stacktrace:


Native stacktrace:

        mono(+0xc486c) [0x801b586c]
        mono(+0x112758) [0x80203758]
        mono(+0x2cb83) [0x8011db83]
        linux-gate.so.1(__kernel_rt_sigreturn+0) [0xb76fed10]
        mono(+0x23a5c8) [0x8032b5c8]
        mono(+0x22855c) [0x8031955c]
        mono(+0x2299b9) [0x8031a9b9]
        mono(+0x229e0b) [0x8031ae0b]
        mono(+0x22c962) [0x8031d962]
        mono(+0x22cd65) [0x8031dd65]
        mono(mono_gc_collect+0x18) [0x803000d8]
        mono(mono_domain_finalize+0x7e) [0x802ca8fe]
        mono(+0x29c63) [0x8011ac63]
        mono(mono_main+0x129e) [0x801864ce]
        mono(+0x275e6) [0x801185e6]
        /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf6) [0xb74c8276]
        mono(+0x279d7) [0x801189d7]

Debug info from gdb:

[New LWP 7395]
[New LWP 7396]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
0xb76fecf9 in __kernel_vsyscall ()
  Id   Target Id         Frame 
* 1    Thread 0xb74aec00 (LWP 7394) "Main" 0xb76fecf9 in __kernel_vsyscall ()
  2    Thread 0xb6bffb40 (LWP 7395) "SGen worker" 0xb76fecf9 in __kernel_vsyscall ()
  3    Thread 0xb721fb40 (LWP 7396) "Finalizer" 0xb76fecf9 in __kernel_vsyscall ()

Thread 3 (Thread 0xb721fb40 (LWP 7396)):
#0  0xb76fecf9 in __kernel_vsyscall ()
#1  0xb74dc100 in __GI___sigsuspend (set=0x80503960) at ../sysdeps/unix/sysv/linux/sigsuspend.c:30
#2  0x802fa4e3 in ?? ()
#3  <signal handler called>
#4  0xb76fecf7 in __kernel_vsyscall ()
#5  0xb766f39b in pthread_join (threadid=3071388480, thread_return=0x0) at pthread_join.c:90
#6  0x802a98ae in ?? ()
#7  0x802ca117 in ?? ()
#8  0x802a7394 in ?? ()
#9  0x803699e7 in ?? ()
#10 0xb766e27a in start_thread (arg=0xb721fb40) at pthread_create.c:333
#11 0xb7597b56 in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:110

Thread 2 (Thread 0xb6bffb40 (LWP 7395)):
#0  0xb76fecf9 in __kernel_vsyscall ()
#1  0xb7673b9b in pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/i386/pthread_cond_wait.S:187
#2  0x80337aad in ?? ()
#3  0xb766e27a in start_thread (arg=0xb6bffb40) at pthread_create.c:333
#4  0xb7597b56 in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:110

Thread 1 (Thread 0xb74aec00 (LWP 7394)):
#0  0xb76fecf9 in __kernel_vsyscall ()
#1  0xb7677e0f in waitpid () at ../sysdeps/unix/syscall-template.S:84
#2  0x801b5939 in ?? ()
#3  0x80203758 in ?? ()
#4  0x8011db83 in ?? ()
#5  <signal handler called>   
#6  0x8032b5c8 in ?? ()
#7  0x8031955c in ?? ()
#8  0x8031a9b9 in ?? ()
#9  0x8031ae0b in ?? ()
#10 0x8031d962 in ?? ()
#11 0x8031dd65 in ?? ()
#12 0x803000d8 in mono_gc_collect ()
#13 0x802ca8fe in mono_domain_finalize ()
#14 0x8011ac63 in ?? ()
#15 0x801864ce in mono_main ()
#16 0x801185e6 in ?? ()
#17 0xb74c8276 in __libc_start_main (main=0x801184e0, argc=2, argv=0xbff21e44, init=0x8037b150 <__libc_csu_init>, fini=0x8037b1b0 <__libc_csu_fini>, rtld_fini=0xb7710080 <_dl_fini>, stack_end=0xbff21e3c) at ../csu/libc-start.c:291
#18 0x801189d7 in _start ()   

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

./start.sh: linje 42:  7394 Afbrudt (SIGABRT)       mono RocketLauncher.exe $INSTANCE_NAME
```

**Comment by Trojaner25** [comment]
Please fill in the template which is shown when creating new issues

**Comment by greencopper** [comment]
No plugins are being used. The Linux distribution is Debian Stretch, but if you cared to look at the report, you would see that all you need is supplied in the trace!

**Comment by Trojaner25** [comment]
No, not all I needed is provided with the report.
First of all, it is a native stack trace, which means its not RocketLaunchers fault, it is happening on monos native code.
I can not get any useful information from that stacktrace except what I wrote above.

I do not know what mono version you are using, what Unturned version you are using, what Linux distro and version you are using and if you have installed all required libraries.

Just copying and pasting the error does not help at all

**Comment by greencopper** [comment]
I fail to see how answering any of the following questions, which is from your template, will help solve the questions you ask:

```
**What problem did you noticed?**
**What is the expected result?**
**What is the current result?**
**How to reproduce the issue?**
```

> I do not know what mono version you are using, what Unturned version you are using, what plugins you are using, what Linux distro and version you are using and if you have installed all required libraries. There are no ways to reproduce this without any information.

I already provided you with that information, maybe you should have waited a little while with closing the bug report.

Regarding the version of Mono, then this isn't asked in your template, but it's obvious from looking at the packages from Debian Stretch:

https://packages.debian.org/search?keywords=mono&searchon=names&suite=stable&section=all

You just disregarded and closed the bug report even though further helpful information could be provided. You should change your template to actually contain the questions you need answered then.

Keep it closed, we won't be using RocketMod.

**Comment by Trojaner25** [comment]
> Regarding the version of Mono, then this isn't asked in your template, but it's obvious from looking at the packages from Debian Stretch:

> https://packages.debian.org/search?keywords=mono&searchon=names&suite=stable&section=all

This is the most ridiculous thing I have ever read about packages on a linux distro.
You know, you can upgrade the distro, you can downgrade the distro, you can upgrade mono, you can downgrade mono? Did you know that there can be different versions of the distro with different mono versions? Debian Strech is a major version which has many different minor versions...

> Keep it closed, we won't be using RocketMod.
Good luck with your server.
