### ISSUE TITLE
Getting kicked beacoufe of Unofficial models 

### ISSUE THREAD

**Issue by SnowyFalin** [RocketMod/Rocket#951]
**What problem did you noticed?**

**What is the expected result?**

**What is the current result?**

**How to reproduce the issue?**

Operating System and Version:

Unturned Version:

Rocketmod Version:

**Comment by SnowyFalin** [comment]
I installed rockedmod and plugins without a porblem but when i join server after 30 sec or so i kickes me out. But my friends dont have that problem. Also i have the serveer in a copy of local game files.

Windows 10
Unturned 3.20.0.1
RockedMod 4.8.3.0

**Comment by persiafighter** [comment]
Do not install rocket in your game directory. Simply clone your game directory elsewhere in your computer, install rocket to the clone and host from the clone. Don't forget your game directory should not have any external modules (only Unturned and Framework are official modules)
