### ISSUE TITLE
Error that prevents me from using prefixes and suffixes!

### ISSUE THREAD

**Issue by HoneySlime** [RocketMod/Rocket#952]
When ever I start up my server, I get this error, which prevents me from having prefixes and suffixes on the player names.

Here is the Error:

Failed adding prefix/suffix to player 76561198147994904: System.NullReferenceException: Object reference not set to an instance of an object
  at Rocket.Core.Permissions.RocketPermissionsManager.GetGroups (IRocketPlayer player, Boolean includeParentGroups) [0x00000] in <filename unknown>:0
  at Essentials.Core.Permission.EssentialsPermissionsProvider.GetGroups (IRocketPlayer player, Boolean includeParentGroups) [0x00000] in <filename unknown>:0
  at Rocket.Unturned.Permissions.UnturnedPermissions.CheckValid (ValidateAuthTicketResponse_t r) [0x00000] in <filename unknown>:0

I know it has something to do with the permissions, but I can seem to find anything.

Here is my Permissions file:

<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Civilian</DisplayName>
      <Prefix>[Civilian]<Prefix/>
      <Suffix />
      <Color>white</Color>
      <Members />
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">avi.economy.balance</Permission>
        <Permission Cooldown="0">avi.economy.pay</Permission>
        <Permission Cooldown="0">avi.economy.tr</Permission>
        <Permission Cooldown="0">avi.economy.tr</Permission>
        <Permission Cooldown="0">avi.economy.exchange</Permission>
        <Permission Cooldown="0">avi.licenses</Permission>
        <Permission Cooldown="0">avi.licenses</Permission>
        <Permission Cooldown="0">avi.licenses.check.other</Permission>
        <Permission Cooldown="0">avi.licenses</Permission>
        <Permission Cooldown="0">avi.shop.buy</Permission>
        <Permission Cooldown="0">avi.shop.cost</Permission>
        <Permission Cooldown="0">avi.shop.sell</Permission>
        <Permission Cooldown="0">jobs</Permission>
        <Permission Cooldown="0">joinjob</Permission>
        <Permission Cooldown="0">leavejob</Permission>
        <Permission Cooldown="0">kit</Permission>
        <Permission Cooldown="0">kits</Permission>
        <Permission Cooldown="0">kit.Civilian</Permission>
      </Permissions>
    </Group>
	<Group>
      <Id>Chef</Id>
      <DisplayName>Chef</DisplayName>
      <Prefix>[Chef]<Prefix/>
      <Suffix />
      <Color>red</Color>
      <Members><Members/>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">avi.economy.balance</Permission>
        <Permission Cooldown="0">avi.economy.pay</Permission>
        <Permission Cooldown="0">avi.economy.tr</Permission>
        <Permission Cooldown="0">avi.economy.tr</Permission>
        <Permission Cooldown="0">avi.economy.exchange</Permission>
        <Permission Cooldown="0">avi.licenses</Permission>
        <Permission Cooldown="0">avi.licenses</Permission>
        <Permission Cooldown="0">avi.licenses.check.other</Permission>
        <Permission Cooldown="0">avi.licenses</Permission>
        <Permission Cooldown="0">avi.shop.buy</Permission>
        <Permission Cooldown="0">avi.shop.cost</Permission>
        <Permission Cooldown="0">avi.shop.sell</Permission>
        <Permission Cooldown="0">jobs</Permission>
        <Permission Cooldown="0">joinjob</Permission>
        <Permission Cooldown="0">leavejob</Permission>
        <Permission Cooldown="0">kit</Permission>
        <Permission Cooldown="0">kits</Permission>
        <Permission Cooldown="0">kit.Chef</Permission>
      </Permissions>
    </Group>
	<Group>
      <Id>Lumberjack</Id>
      <DisplayName>Lumberjack</DisplayName>
      <Prefix>[Lumberjack]<Prefix/>
      <Suffix />
      <Color>brown</Color>
      <Members><Members/>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">avi.economy.balance</Permission>
        <Permission Cooldown="0">avi.economy.pay</Permission>
        <Permission Cooldown="0">avi.economy.tr</Permission>
        <Permission Cooldown="0">avi.economy.tr</Permission>
        <Permission Cooldown="0">avi.economy.exchange</Permission>
        <Permission Cooldown="0">avi.licenses</Permission>
        <Permission Cooldown="0">avi.licenses</Permission>
        <Permission Cooldown="0">avi.licenses.check.other</Permission>
        <Permission Cooldown="0">avi.licenses</Permission>
        <Permission Cooldown="0">avi.shop.buy</Permission>
        <Permission Cooldown="0">avi.shop.cost</Permission>
        <Permission Cooldown="0">avi.shop.sell</Permission>
        <Permission Cooldown="0">jobs</Permission>
        <Permission Cooldown="0">joinjob</Permission>
        <Permission Cooldown="0">leavejob</Permission>
        <Permission Cooldown="0">kit</Permission>
        <Permission Cooldown="0">kits</Permission>
        <Permission Cooldown="0">kit.Lumberjack</Permission>
      </Permissions>
    </Group>
	<Group>
      <Id>SecGuard</Id>
      <DisplayName>Security Guard</DisplayName>
      <Prefix>[Security Guard]<Prefix/>
      <Suffix />
      <Color>blue</Color>
      <Members><Members/>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">avi.economy.balance</Permission>
        <Permission Cooldown="0">avi.economy.pay</Permission>
        <Permission Cooldown="0">avi.economy.tr</Permission>
        <Permission Cooldown="0">avi.economy.tr</Permission>
        <Permission Cooldown="0">avi.economy.exchange</Permission>
        <Permission Cooldown="0">avi.licenses</Permission>
        <Permission Cooldown="0">avi.licenses</Permission>
        <Permission Cooldown="0">avi.licenses.check.other</Permission>
        <Permission Cooldown="0">avi.licenses</Permission>
        <Permission Cooldown="0">avi.shop.buy</Permission>
        <Permission Cooldown="0">avi.shop.cost</Permission>
        <Permission Cooldown="0">avi.shop.sell</Permission>
        <Permission Cooldown="0">jobs</Permission>
        <Permission Cooldown="0">joinjob</Permission>
        <Permission Cooldown="0">leavejob</Permission>
        <Permission Cooldown="0">kit</Permission>
        <Permission Cooldown="0">kits</Permission>
        <Permission Cooldown="0">kit.Security Guard</Permission>
      </Permissions>
    </Group>
	<Group>
      <Id>Police</Id>
      <DisplayName>Police</DisplayName>
      <Prefix>[Police]<Prefix/>
      <Suffix />
      <Color>blue</Color>
      <Members><Members/>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">avi.economy.balance</Permission>
        <Permission Cooldown="0">avi.economy.pay</Permission>
        <Permission Cooldown="0">avi.economy.tr</Permission>
        <Permission Cooldown="0">avi.economy.tr</Permission>
        <Permission Cooldown="0">avi.economy.exchange</Permission>
        <Permission Cooldown="0">avi.licenses</Permission>
        <Permission Cooldown="0">avi.licenses</Permission>
        <Permission Cooldown="0">avi.licenses.check.other</Permission>
        <Permission Cooldown="0">avi.licenses</Permission>
        <Permission Cooldown="0">avi.shop.buy</Permission>
        <Permission Cooldown="0">avi.shop.cost</Permission>
        <Permission Cooldown="0">avi.shop.sell</Permission>
        <Permission Cooldown="0">jobs</Permission>
        <Permission Cooldown="0">joinjob</Permission>
        <Permission Cooldown="0">leavejob</Permission>
        <Permission Cooldown="0">kit</Permission>
        <Permission Cooldown="0">kits</Permission>
        <Permission Cooldown="0">kit.Police</Permission>
      </Permissions>
    </Group>
	<Group>
      <Id>Farmer</Id>
      <DisplayName>Farmer</DisplayName>
      <Prefix>[Farmer]<Prefix/>
      <Suffix />
      <Color>green</Color>
      <Members><Members/>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">avi.economy.balance</Permission>
        <Permission Cooldown="0">avi.economy.pay</Permission>
        <Permission Cooldown="0">avi.economy.tr</Permission>
        <Permission Cooldown="0">avi.economy.tr</Permission>
        <Permission Cooldown="0">avi.economy.exchange</Permission>
        <Permission Cooldown="0">avi.licenses</Permission>
        <Permission Cooldown="0">avi.licenses</Permission>
        <Permission Cooldown="0">avi.licenses.check.other</Permission>
        <Permission Cooldown="0">avi.licenses</Permission>
        <Permission Cooldown="0">avi.shop.buy</Permission>
        <Permission Cooldown="0">avi.shop.cost</Permission>
        <Permission Cooldown="0">avi.shop.sell</Permission>
        <Permission Cooldown="0">jobs</Permission>
        <Permission Cooldown="0">joinjob</Permission>
        <Permission Cooldown="0">leavejob</Permission>
        <Permission Cooldown="0">kit</Permission>
        <Permission Cooldown="0">kits</Permission>
        <Permission Cooldown="0">kit.Farmer</Permission>
      </Permissions>
    </Group>
	<Group>
      <Id>Pilot</Id>
      <DisplayName>Pilot</DisplayName>
      <Prefix>[Pilot]<Prefix/>
      <Suffix />
      <Color>blue</Color>
      <Members><Members/>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">avi.economy.balance</Permission>
        <Permission Cooldown="0">avi.economy.pay</Permission>
        <Permission Cooldown="0">avi.economy.tr</Permission>
        <Permission Cooldown="0">avi.economy.tr</Permission>
        <Permission Cooldown="0">avi.economy.exchange</Permission>
        <Permission Cooldown="0">avi.licenses</Permission>
        <Permission Cooldown="0">avi.licenses</Permission>
        <Permission Cooldown="0">avi.licenses.check.other</Permission>
        <Permission Cooldown="0">avi.licenses</Permission>
        <Permission Cooldown="0">avi.shop.buy</Permission>
        <Permission Cooldown="0">avi.shop.cost</Permission>
        <Permission Cooldown="0">avi.shop.sell</Permission>
        <Permission Cooldown="0">jobs</Permission>
        <Permission Cooldown="0">joinjob</Permission>
        <Permission Cooldown="0">leavejob</Permission>
        <Permission Cooldown="0">kit</Permission>
        <Permission Cooldown="0">kits</Permission>
        <Permission Cooldown="0">kit.Pilot</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>vip</Id>
      <DisplayName>VIP</DisplayName>
      <Prefix />
      <Suffix />
      <Color>FF9900</Color>
      <Members>
        <Member>76561198016438091</Member>
      </Members>
      <ParentGroup>default</ParentGroup>
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">effect</Permission>
        <Permission Cooldown="120">heal</Permission>
        <Permission Cooldown="30">v</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>

Thank you!

**Comment by Trojaner25** [comment]
Please reopen the issue and fill the template.
Without that information I'm unable to help you.

**Comment by HoneySlime** [comment]
ok thanks, I solved it on my own! yay

**Comment by Trojaner25** [comment]
Oh, ok 👍
