### ISSUE TITLE
Battleye offical modules not installed issue

### ISSUE THREAD

**Issue by TahoeTheSoldier** [RocketMod/Rocket#957]
**What problem did you noticed?**
Whenever I loaded in my server, even with no plugins, it would let me in for about two minutes until kicking me off the server saying that battleye official modules were not installed. I tried reinstalling battleye and even Unturned, but neither of them worked.
**What is the expected result?**
TO let me play on my server without kicking me off.
**What is the current result?**
Kicks me off the server after playing for about two minutes saying that battleye official modules were not installed.
**How to reproduce the issue?**
Install Rocketmod the usual way, and then play on your server on the computer it is loaded on.

Operating System and Version:

Unturned Version:
 3.20.3.0
Rocketmod Version:
4.9.3.0

**Comment by TahoeTheSoldier** [comment]
I meant battleye unofficial modules

**Comment by persiafighter** [comment]
Don't install rocket in the game data that you play with. Create a separate copy and install it there, but also run the server from that directory.
