### ISSUE TITLE
Console commands do nothing as well as /help

### ISSUE THREAD

**Issue by FaZeFantasy** [RocketMod/Rocket#958]
**What problem did you noticed?**
When I do console commands (from a server host) it does absolutely nothing. Also when I do /help it does absolutely nothing either no message in the console nothing. Same with console commands nothing happens. Nothing gets sent to the console log, to anything, when I perform /help, or a command in console. And yes I did contact my server host.

**What is the expected result?**
When I perform /help in game, it would show help information (I'm assuming it's available commands because it's usually like that for games like this)
When I do /admin name, admin name, /broadcast Why?, broadcast Why? (I do not know if it's with a slash or not so I do both to find out but nothing happens) nothing is done, IE when i do /admin name or admin name it doesnt admin them. If I do /broadcast Why? broadcast Why? it does nothing and does not even give a message in the console saying an error when I perform it. Not even an indication that I had even performed it.

**What is the current result?**
Nothing happens when executing /help in game or any command, IE /admin name, admin name, /broadcast Why?, broadcast Why?, in console.

**How to reproduce the issue?**
Have no idea.

Operating System and Version:
I think the OS is Linux no idea though as it's hosted off of ABCgameservers

Unturned Version:
3.20.3.0

Rocketmod Version:
4.9.3.0

This might be confusing to some but idk if it will be sorry in advanced if it is.

Here's the log:
https://gist.github.com/FaZeFantasy/cb5fcb0d2679fef819afd452e82832c9

**Comment by FaZeFantasy** [comment]
Edit:

> I think the OS is Linux no idea though as it's hosted off of ABCgameservers

**Comment by Trojaner25** [comment]
How do you access console?

**Comment by FaZeFantasy** [comment]
What do you mean console output like when i do a command does it say anything? In game if i do a command it does show up. But /help doesnt.

I access the console through my hosters control panel.

**Comment by Trojaner25** [comment]
Im sorry but this likely an issue with your hoster, not with Rocket. If it can be proved that this is Rockets fault, I will reopen this.
