### ISSUE TITLE
Server won't start stops at mono version info

### ISSUE THREAD

**Issue by gegtor** [RocketMod/Rocket#959]
**What problem did you noticed?**
My fresh server won't start up 
It stops at this then exits
`WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319`

**How to reproduce the issue?**
Install server using guide on Rocket's wiki

Operating System and Version:
Ubuntu server 16.04 

Unturned Version: 3.20.3.0

Rocketmod Version: Latest

**Comment by Trojaner25** [comment]
How do you start the server?

**Comment by gegtor** [comment]
`sudo ./start.sh SV1`

I know i don't have to use sudo normaly but in this case it's a must and i run unturned server using sudo in the past and they ran just fine

**Comment by gegtor** [comment]
Simple
`mono RocketLauncher.exe <instance name>`

Don't works too

**Comment by Trojaner25** [comment]
Can you upload your Rocket.log and your output_log.txt? (use github gist please)

**Comment by gegtor** [comment]
There is no Rocket.log or output_log.txt

It works okay without rocket

And `Servers` directory is missing

**Comment by Trojaner25** [comment]
How do you start when no Rocket is installed?
What happens if you start it the same way with Rocket installed and without RocketLauncher?

**Comment by falsechicken** [comment]
How do you launch the server without rocket?

**Comment by gegtor** [comment]
This is ultra weird now

I have multiple OVH VPS's and unturned with rocket works fine on all of them 

It happens only on this one even after several OS re-installs

I bought new vps and it works fine there

**Comment by unturnedplayer** [comment]
I've seen that mono warning before.  You have to downgrade mono to the 3.x version and then it works (it worked for me).  I think the latest version (according to my Ubuntu server) is 3.2.8.
