### ISSUE TITLE
Big Errors.

### ISSUE THREAD

**Issue by muzaffer22** [RocketMod/Rocket#960]
**DontDestroyOnLoad only work for root GameObjects or components on root GameObjects.
 
(Filename:  Line: 448)**

**Not happen.**

**It's open.**

**I uploaded new map on my server. Did this the map.?**

Operating System and Version:

Unturned Version: 3.20.3.0

Rocketmod Version: 4.9.3.0

**Comment by Trojaner25** [comment]
Please upload full error log

**Comment by muzaffer22** [comment]
I'm getting two errors.

DontDestroyOnLoad only work for root GameObjects or components on root GameObjects.

(Filename: Line: 448)

BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Synergy Roleplay V1/Spawns/Barricades/1409/Root/Skeleton/Spine/Skull"

(Filename: Line: 0)

**Comment by muzaffer22** [comment]
Second: NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.UseableBarricade.equip () SDG.Unturned.PlayerEquipment.tellEquip (CSteamID steamID, Byte page, Byte x, Byte y, UInt16 id, Byte newQuality, System.Byte[] newState) System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation. System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size) SDG.Unturned.SteamChannel.send (ESteamCall mode, ESteamPacket type, Int32 size, System.Byte[] packet) SDG.Unturned.SteamChannel.send (System.String name, ESteamCall mode, ESteamPacket type, System.Object[] arguments) SDG.Unturned.PlayerEquipment.tryEquip (Byte page, Byte x, Byte y, System.Byte[] hash) SDG.Unturned.PlayerEquipment.askEquip (CSteamID steamID, Byte page, Byte x, Byte y, System.Byte[] hash) System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation. System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size) SDG.Unturned.Provider.receiveServer (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel) SDG.Unturned.Provider.listenServer (Int32 channel) SDG.Unturned.Provider.listen () SDG.Unturned.Provider.Update ()
NullReferenceException: Object reference not set to an instance of an object at SDG.Unturned.UseableBarricade.equip () [0x00000] in :0 at SDG.Unturned.PlayerEquipment.tellEquip (CSteamID steamID, Byte page, Byte x, Byte y, UInt16 id, Byte newQuality, System.Byte[] newState) [0x00000] in :0 at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&) at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in :0 Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation. at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in :0 at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in :0 at SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size) [0x00000] in :0 at SDG.Unturned.SteamChannel.send (ESteamCall mode, ESteamPacket type, Int32 size, System.Byte[] packet) [0x00000] in :0 at SDG.Unturned.SteamChannel.send (System.String name, ESteamCall mode, ESteamPacket type, System.Object[] arguments) [0x00000] in :0 at SDG.Unturned.PlayerEquipment.tryEquip (Byte page, Byte x, Byte y, System.Byte[] hash) [0x00000] in :0 at SDG.Unturned.PlayerEquipment.askEquip (CSteamID steamID, Byte page, Byte x, Byte y, System.Byte[] hash) [0x00000] in :0 at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&) at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in :0 Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation. at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in :0 at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in :0 at SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size) [0x00000] in :0 at SDG.Unturned.Provider.receiveServer (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel) [0x00000] in :0 at SDG.Unturned.Provider.listenServer (Int32 channel) [0x00000] in :0 at SDG.Unturned.Provider.listen () [0x00000] in :0 at SDG.Unturned.Provider.Update () [0x00000] in :0
(Filename: Line: -1)

**Comment by Trojaner25** [comment]
Not a rocket bug. It's anot Unturned bug
