### ISSUE TITLE
Filezilla Critical Error for Scripts\Linux\RocketLauncher.exe

### ISSUE THREAD

**Issue by muzaffer22** [RocketMod/Rocket#961]
**What problem did you noticed?**

**What is the expected result?**
Scripts\Linux\RocketLauncher.exe Filezilla critical error.

**What is the current result?**
Filezilla critical error.

**How to reproduce the issue?**
I don't know

Operating System and Version:

Unturned Version: Last

Rocketmod Version: Last

**Comment by Trojaner25** [comment]
Not enough information

**Comment by muzaffer22** [comment]
Command:	STOR RocketLauncher.exe
Answer:	550 RocketLauncher.exe: Operation not permitted
Error:	Critical file transfer error

**Comment by Trojaner25** [comment]
Your hoster blocks uploading of .exe files. Contact your hoster.
