### ISSUE TITLE
My server rocketplugin dont work after i change some coding in permission file

### ISSUE THREAD

**Issue by Flukerking** [RocketMod/Rocket#962]
My rocket plugin doesnt work after I add two more group in permission file. I tried to reinstall rocketmod including all plugin and still the plugin doesnt work at all. And I cant access my console via PuTTY after adding the two groups it said:Network error:Connection refused everytime i tried to join after the change in permission.xml

The expected result is 2more group were added so 2 more job will be added to my rpserver.

My server plugin still doesnt work even though i tried reinstall them

I dont think i know how to reproduce this.

Operating System and Version:

Unturned Version: 3.20.3.0

Rocketmod Version: latest version.
[Rocket (3).zip](https://github.com/RocketMod/Rocket/files/1236078/Rocket.3.zip)

**Comment by Trojaner25** [comment]
Upload permissions file
