### ISSUE TITLE
Building disappear

### ISSUE THREAD

**Issue by zch12138** [RocketMod/Rocket#963]
Hi,I am using mono3.12.1,the latest version of rocketmod and I don't meet this bug before.

A player suddenly lost all his building except for floor and wall.
Just disappear,But there will be something blocking you when you trying to cross the door frame or window frame.
It just like the all thing still there but you can't see it
Just one player meet this BUG.The others building is fine.

**Comment by Trojaner25** [comment]
Likely unturned bug, also missing issue template.
