### ISSUE TITLE
Rocket | Modified code error

### ISSUE THREAD

**Issue by Maxx136** [RocketMod/Rocket#964]
**What problem did you noticed?** Me and a friend are hosting a server on gameservers, i installed rocket mod and now i wanted to install like "rocket" to install plugins and access /v /i and stuff, u prob know what i mean. Now when i join the server theres not terrain for like 3 minutes and kicks me with the reason "This server is using modified code"

**What is the expected result?** Just join the server and can access "Rocket commands"

**What is the current result?** I join the server and no terrain loads and after about 3 secs it kicks me with the reason "This server is using modified code" 

**How to reproduce the issue?** I dont know i tried uninstalling rocket disabling rocket mod to vanilla and do it like that.

Operating System and Version:

Unturned Version: 3.20.3.0

Rocketmod Version: 4.9.3.0

Extra information: I cant access the console cause of GameServers doesnt have that option. Im using the 
 Russia map

**Comment by KlaasM** [comment]
This problem is probably not related to Rocket as you said you've tried vanilla and it still didn't work.

**Comment by Maxx136** [comment]
Well, as soon as i uploaded rocket it didnt work and gave that error, I fixxed it now tho
