### ISSUE TITLE
XML Error And Command Error

### ISSUE THREAD

**Issue by FaZeFantasy** [RocketMod/Rocket#966]
What problem did you noticed?
I get an XML error for the permissions file and cant find out why even with xml validator. And I also get an error when doing any commands.

What is the expected result?
To be able to do commands and not have a permissions file error

What is the current result?
Can't do any commands and has a permissions file error

How to reproduce the issue?
Have no clue

Operating System and Version:
Windows

Unturned Version:
Latest

Rocketmod Version:
Can't check (Can't do the command for it)

Rocket Log
[https://gist.github.com/FaZeFantasy/320b3ea4948025cd439dff17fac56e9b](url)
Permissions config
[https://gist.github.com/FaZeFantasy/49372c2d73f37d819aab384cef9c6870](url)

**Comment by Trojaner25** [comment]
line 646; you are missing a </Group>

/closed: Not a bug
