### ISSUE TITLE
Rocket servers get stuck loading the server

### ISSUE THREAD

**Issue by unturnedplayer** [RocketMod/Rocket#968]
Everytime I try to start a Windows and Linux server (two servers), the loading screen gets stuck after the "Found server assets: 0" screen and shows the following error:

DirectoryNotFoundException: Directory '/unturned/Bundles/Workshop/Maps' not found. - System.IO.Directory.GetFileSystemEntries (System.String path, System.String searchPattern, FileAttributes mask, FileAttributes attrs)
System.IO.Directory.GetDirectories (System.String path, System.String searchPattern)
System.IO.Directory.GetDirectories (System.String path)
SDG.Unturned.ReadWrite.getFolders (System.String path, Boolean usePath)
SDG.Unturned.ReadWrite.getFolders (System.String path)
SDG.Unturned.Level.getLevels (ESingleplayerMapCategory categoryFilter)
SDG.Unturned.Assets+<init>c__Iterator0.MoveNext ()
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress)

Note: for Windows, the directory path in the error shows: c:\unturned/Bundles/Workshop/Maps
The error appears **_before_** any plugins are loaded.

Operating System and Version:
Ubuntu Server 14.04 LTS
Windows 7 Pro

Unturned Version:
3.20.4.0

Rocketmod Version:
Windows: 1272
Linux: 935

**Comment by Trojaner25** [comment]
Unturned bug (are you sure the give directory exists? Create it and maybe it will work again)

**Comment by unturnedplayer** [comment]
I didn't add/delete/change any directories and both servers were working fine before updating Unturned.  I've already submitted a bug report for Unturned itself as it gives a different error when attempting to run a vanilla server.

**Comment by unturnedplayer** [comment]
Forgot to mention above that when I don't use Rocket (i.e. vanilla server), I get a different error but at least the server loads.  In other words, the server will get past the "Found server assets: 0" message.
