### ISSUE TITLE
An Con-Fig Error That Is Not There

### ISSUE THREAD

**Issue by AveryMR** [RocketMod/Rocket#969]
Hi, 

I've Gotten an Con-Fig Error  (thats what that is) -->

Rocket.CoreException in Rocket.Core: System.Exception: Failed to deserialize XMLFileAsset: Permissions.config.xml ---> System.Xml.XmlException: Expected >, but found s [115]  Line 196, position 20.
  at Mono.Xml2.XmlTextReader.ExpectAfterWhitespace (Char c) [0x00000] in <filename unknown>:0
  at Mono.Xml2.XmlTextReader.ReadEndTag () [0x00000] in <filename unknown>:0
  at Mono.Xml2.XmlTextReader.ReadContent () [0x00000] in <filename unknown>:0
  at Mono.Xml2.XmlTextReader.ReadContent () [0x00000] in <filename unknown>:0
  at Mono.Xml2.XmlTextReader.Read () [0x00000] in <filename unknown>:0
  at System.Xml.XmlTextReader.Read () [0x00000] in <filename unknown>:0
  at System.Xml.XmlDocument.ReadNodeCore (System.Xml.XmlReader reader) [0x00000] in <filename unknown>:0
  at System.Xml.XmlDocument.ReadNodeCore (System.Xml.XmlReader reader) [0x00000] in <filename unknown>:0
  at System.Xml.XmlDocument.ReadNodeCore (System.Xml.XmlReader reader) [0x00000] in <filename unknown>:0
at System.Xml.XmlDocument.ReadNodeCore (System.Xml.XmlReader reader) [0x00000] in <filename unknown>:0
  at System.Xml.XmlDocument.ReadNodeCore (System.Xml.XmlReader reader) [0x00000] in <filename unknown>:0
  at System.Xml.XmlDocument.ReadNode (System.Xml.XmlReader reader) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReader.ReadXmlNode (Boolean wrapped) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReader.UnknownNode (System.Object o, System.String qnames) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReader.UnknownNode (System.Object o) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReaderInterpreter.ProcessUnknownElement (System.Object target) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadMembers (System.Xml.Serialization.ClassMap map, System.Object ob, Boolean isValueList, Boolean readByOrder) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadClassInstanceMembers (System.Xml.Serialization.XmlTypeMapping typeMap, System.Object ob) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadClassInstance (System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, Boolean checkType) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadObject (System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable,
Boolean checkType) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadRoot (System.Xml.Serialization.XmlTypeMapping rootMap) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadRoot () [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.Serialization.XmlSerializationReader reader) [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
  at Rocket.Core.Assets.XMLFileAsset1[Rocket.API.Serialisation.RocketPermissions].Load (Rocket.API.AssetLoaded1 callback) [0x00000] in <filename unknown>:0
  at Rocket.Core.Assets.XMLFileAsset`1[Rocket.API.Serialisation.RocketPermissions]..ctor (System.String file, System.Type[] extraTypes, Rocket.API.Serialisation.RocketPermissions defaultInstance) [0x00000] in <filename unknown>:0
  at Rocket.Core.Permissions.RocketPermissionsManager.Start () [0x00000] in <filename unknown>:0

But found s [115]  Line 196, position 20. But nothing Is there. So Im Woundering If im missing something, here is the document 

<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <DefaultGroup>Citizen</DefaultGroup>
  <Groups>
    <Group>
      <Id>Citizen</Id>
      <DisplayName>Citizen</DisplayName>
      <Prefix>[Citizen]</Prefix>
      <Suffix />
      <Color>white</Color>
      <Members />
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">tpa</Permission>
        <Permission Cooldown="0">tpa.send</Permission>
        <Permission Cooldown="0">tpa.accept</Permission>
        <Permission Cooldown="0">tpa.decline</Permission>
        <Permission Cooldown="0">tpa.a</Permission>
        <Permission Cooldown="0">home</Permission>
        <Permission Cooldown="0">pay</Permission>
        <Permission Cooldown="0">balance</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>Police</Id>
      <DisplayName>Police</DisplayName>
      <Prefix>[Police]</Prefix>
      <Suffix />
      <Color>#00FEDF</Color>
      <Members>
        <Member>76561198395344348</Member>
        <Member>76561198262774645</Member>
        <Member>76561198391806126</Member>
        <Member>76561198197335101</Member>
      </Members>
      <ParentGroup>Citizen</ParentGroup>
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">effect</Permission>
        <Permission Cooldown="0">jail</Permission>
        <Permission Cooldown="0">tpa.send</Permission>
        <Permission Cooldown="0">tpa.accept</Permission>
        <Permission Cooldown="0">tpa.deny</Permission>
        <Permission Cooldown="0">tpa.cancel</Permission>
        <Permission Cooldown="0">tpa</Permission>
        <Permission Cooldown="0">home</Permission>
        <Permission Cooldown="0">pay</Permission>
        <Permission Cooldown="0">balance</Permission>
        <Permission Cooldown="0">jail.immune</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>Moderator</Id>
      <DisplayName>Moderator</DisplayName>
      <Prefix>[Moderator]</Prefix>
      <Suffix />
      <Color>#0000FE</Color>
      <Members>
        <Member>76561198262774645</Member>
        <Member>76561198135274325</Member>
        <Member>76561198341003605</Member>
        <Member>76561198391806126</Member>
      </Members>
      <ParentGroup>Citizen</ParentGroup>
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">effect</Permission>
        <Permission Cooldown="0">v</Permission>
        <Permission Cooldown="0">tpa.send</Permission>
        <Permission Cooldown="0">tpa.accept</Permission>
        <Permission Cooldown="0">tpa.deny</Permission>
        <Permission Cooldown="0">tpa.cancel</Permission>
        <Permission Cooldown="0">tpa</Permission>
        <Permission Cooldown="0">home</Permission>
        <Permission Cooldown="0">tp</Permission>
        <Permission Cooldown="0">tphere</Permission>
        <Permission Cooldown="0">kick</Permission>
        <Permission Cooldown="0">pay</Permission>
        <Permission Cooldown="0">balance</Permission>
        <Permission Cooldown="0">spy</Permission>
        <Permission Cooldown="0">weather</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>Admin</Id>
      <DisplayName>Admin</DisplayName>
      <Prefix>[Admin]</Prefix>
      <Suffix />
      <Color>#0000FE</Color>
      <Members />
      <ParentGroup>Citizen</ParentGroup>
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">effect</Permission>
        <Permission Cooldown="0">v</Permission>
        <Permission Cooldown="0">give</Permission>
        <Permission Cooldown="0">tpa.send</Permission>
        <Permission Cooldown="0">tpa.accept</Permission>
        <Permission Cooldown="0">tpa.deny</Permission>
        <Permission Cooldown="0">tpa.cancel</Permission>
        <Permission Cooldown="0">tpa</Permission>
        <Permission Cooldown="0">home</Permission>
        <Permission Cooldown="0">time</Permission>
        <Permission Cooldown="0">day</Permission>
        <Permission Cooldown="0">night</Permission>
        <Permission Cooldown="0">tp</Permission>
        <Permission Cooldown="0">tphere</Permission>
        <Permission Cooldown="0">teleport</Permission>
        <Permission Cooldown="0">i</Permission>
        <Permission Cooldown="0">vehicle</Permission>
        <Permission Cooldown="0">kick</Permission>
        <Permission Cooldown="0">pay</Permission>
        <Permission Cooldown="0">balance</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>HeadAdmin</Id>
      <DisplayName>Head Admin</DisplayName>
      <Prefix>[Head Admin]</Prefix>
      <Suffix />
      <Color>#0000FE</Color>
      <Members>
      </Members>
      <ParentGroup>Citizen</ParentGroup>
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">effect</Permission>
        <Permission Cooldown="0">v</Permission>
        <Permission Cooldown="0">give</Permission>
        <Permission Cooldown="0">tpa.send</Permission>
        <Permission Cooldown="0">tpa.accept</Permission>
        <Permission Cooldown="0">tpa.deny</Permission>
        <Permission Cooldown="0">tpa.cancel</Permission>
        <Permission Cooldown="0">tpa</Permission>
        <Permission Cooldown="0">home</Permission>
        <Permission Cooldown="0">time</Permission>
        <Permission Cooldown="0">day</Permission>
        <Permission Cooldown="0">night</Permission>
        <Permission Cooldown="0">tp</Permission>
        <Permission Cooldown="0">tphere</Permission>
        <Permission Cooldown="0">teleport</Permission>
        <Permission Cooldown="0">i</Permission>
        <Permission Cooldown="0">vehicle</Permission>
        <Permission Cooldown="0">experience</Permission>
        <Permission Cooldown="0">kick</Permission>
        <Permission Cooldown="0">pay</Permission>
        <Permission Cooldown="0">balance</Permission>
        <Permission Cooldown="0">kill</Permission>
        <Permission Cooldown="0">spy</Permission>
        <Permission Cooldown="0">heal</Permission>
        <Permission Cooldown="0">v</Permission>
        <Permission Cooldown="0">give</Permission>
        <Permission Cooldown="0">weather</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>Community-Manger</Id>
      <DisplayName>Community Manger</DisplayName>
      <Prefix>[Community Manger]</Prefix>
      <Suffix />
      <Color>#FE0000</Color>
      <Members>
      </Members>
      <ParentGroup>Citizen</ParentGroup>
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">effect</Permission>
        <Permission Cooldown="0">tpa</Permission>
        <Permission Cooldown="0">tpa.send</Permission>
        <Permission Cooldown="0">tpa.accept</Permission>
        <Permission Cooldown="0">tpa.decline</Permission>
        <Permission Cooldown="0">tpa.a</Permission>
        <Permission Cooldown="0">home</Permission>
        <Permission Cooldown="0">pay</Permission>
        <Permission Cooldown="0">balance</Permission>
        <Permission Cooldown="0">time</Permission>
        <Permission Cooldown="0">day</Permission>
        <Permission Cooldown="0">night</Permission>
        <Permission Cooldown="0">tp</Permission>
        <Permission Cooldown="0">tphere</Permission>
        <Permission Cooldown="0">teleport</Permission>
        <Permission Cooldown="0">heal</Permission>
        <Permission Cooldown="0">give</Permission>
        <Permission Cooldown="0">vehicle</Permission>
        <Permission Cooldown="0">i</Permission>
        <Permission Cooldown="0">v</Permission>
        <Permission Cooldown="0">ban</Permission>
        <Permission Cooldown="0">unban</Permission>
        <Permission Cooldown="0">experience/Permission>
        <Permission Cooldown="0">kick</Permission>
        <Permission Cooldown="0">spy</Permission>
        <Permission Cooldown="0">weather</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>ServerCo-Owner</Id>
      <DisplayName>Server Co-Owner</DisplayName>
      <Prefix>[Server Co-Owner]</Prefix>
      <Suffix />
      <Color>#FE0000</Color>
      <Members>
        <Member>76561198165660505</Member>
      </Members>
      <ParentGroup>Citizen</ParentGroup>
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">effect</Permission>
        <Permission Cooldown="0">heal</Permission>
        <Permission Cooldown="0">v</Permission>
        <Permission Cooldown="0">vanish</Permission>
        <Permission Cooldown="0">give</Permission>
        <Permission Cooldown="0">jail</Permission>
        <Permission Cooldown="0">god</Permission>
        <Permission Cooldown="0">tpa.send</Permission>
        <Permission Cooldown="0">tpa.accept</Permission>
        <Permission Cooldown="0">tpa.deny</Permission>
        <Permission Cooldown="0">tpa.cancel</Permission>
        <Permission Cooldown="0">tpa</Permission>
        <Permission Cooldown="0">home</Permission>
        <Permission Cooldown="0">teleport</Permission>
        <Permission Cooldown="0">tp</Permission>
        <Permission Cooldown="0">tphere</Permission>
        <Permission Cooldown="0">weather</Permission>
        <Permission Cooldown="0">ban</Permission>
        <Permission Cooldown="0">unban</Permission>
        <Permission Cooldown="0">kick</Permission>
        <Permission Cooldown="0">kill</Permission>
        <Permission Cooldown="0">slay</Permission>
        <Permission Cooldown="0">spy</Permission>
        <Permission Cooldown="0">vehicle</Permission>
        <Permission Cooldown="0">i</Permission>
        <Permission Cooldown="0">experience</Permission>
        <Permission Cooldown="0">reputation</Permission>
        <Permission Cooldown="0">time</Permission>
        <Permission Cooldown="0">day</Permission>
        <Permission Cooldown="0">night</Permission>
        <Permission Cooldown="0">pay</Permission>
        <Permission Cooldown="0">balance</Permission>
        <Permission Cooldown="0">save</Permission>
        <Permission Cooldown="0">say</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>founder</Id>
      <DisplayName>founder</DisplayName>
      <Prefix>[Founder]</Prefix>
      <Suffix />
      <Color>#FE0000</Color>
      <Members>
        <Member>76561198130744847</Member>
      </Members>
      <ParentGroup>Citizen</ParentGroup>
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">effect</Permission>
        <Permission Cooldown="0">heal</Permission>
        <Permission Cooldown="0">v</Permission>
        <Permission Cooldown="0">vanish</Permission>
        <Permission Cooldown="0">give</Permission>
        <Permission Cooldown="0">jail</Permission>
        <Permission Cooldown="0">god</Permission>
        <Permission Cooldown="0">tpa.send</Permission>
        <Permission Cooldown="0">tpa.accept</Permission>
        <Permission Cooldown="0">tpa.deny</Permission>
        <Permission Cooldown="0">tpa.cancel</Permission>
        <Permission Cooldown="0">tpa</Permission>
        <Permission Cooldown="0">home</Permission>
        <Permission Cooldown="0">teleport</Permission>
        <Permission Cooldown="0">tp</Permission>
        <Permission Cooldown="0">tphere</Permission>
        <Permission Cooldown="0">weather</Permission>
        <Permission Cooldown="0">ban</Permission>
        <Permission Cooldown="0">unban</Permission>
        <Permission Cooldown="0">kick</Permission>
        <Permission Cooldown="0">kill</Permission>
        <Permission Cooldown="0">slay</Permission>
        <Permission Cooldown="0">spy</Permission>
        <Permission Cooldown="0">vehicle</Permission>
        <Permission Cooldown="0">i</Permission>
        <Permission Cooldown="0">experience</Permission>
        <Permission Cooldown="0">reputation</Permission>
        <Permission Cooldown="0">time</Permission>
        <Permission Cooldown="0">day</Permission>
        <Permission Cooldown="0">night</Permission>
        <Permission Cooldown="0">pay</Permission>
        <Permission Cooldown="0">balance</Permission>
        <Permission Cooldown="0">save</Permission>
        <Permission Cooldown="0">say</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>ServerOwner</Id>
      <DisplayName>Server Owner</DisplayName>
      <Prefix>[Server Owner]</Prefix>
      <Suffix />
      <Color>#FE0000</Color>
      <Members>
        <Member>76561198149931409</Member>
      </Members>
      <ParentGroup>Citizen</ParentGroup>
      <Priority>100</Priority>
      <Permission>
        <Permission Cooldown="0">effect</Permission>
        <Permission Cooldown="0">heal</Permission>
        <Permission Cooldown="0">v</Permission>
        <Permission Cooldown="0">vanish</Permission>
        <Permission Cooldown="0">give</Permission>
        <Permission Cooldown="0">jail</Permission>
        <Permission Cooldown="0">god</Permission>
        <Permission Cooldown="0">tpa.send</Permission>
        <Permission Cooldown="0">tpa.accept</Permission>
        <Permission Cooldown="0">tpa.deny</Permission>
        <Permission Cooldown="0">tpa.cancel</Permission>
        <Permission Cooldown="0">tpa</Permission>
        <Permission Cooldown="0">home</Permission>
        <Permission Cooldown="0">teleport</Permission>
        <Permission Cooldown="0">tp</Permission>
        <Permission Cooldown="0">tphere</Permission>
        <Permission Cooldown="0">weather</Permission>
        <Permission Cooldown="0">ban</Permission>
        <Permission Cooldown="0">unban</Permission>
        <Permission Cooldown="0">kick</Permission>
        <Permission Cooldown="0">kill</Permission>
        <Permission Cooldown="0">slay</Permission>
        <Permission Cooldown="0">spy</Permission>
        <Permission Cooldown="0">vehicle</Permission>
        <Permission Cooldown="0">i</Permission>
        <Permission Cooldown="0">experience</Permission>
        <Permission Cooldown="0">reputation</Permission>
        <Permission Cooldown="0">time</Permission>
        <Permission Cooldown="0">day</Permission>
        <Permission Cooldown="0">night</Permission>
        <Permission Cooldown="0">pay</Permission>
        <Permission Cooldown="0">balance</Permission>
        <Permission Cooldown="0">save</Permission>
        <Permission Cooldown="0">say</Permission>
        <Permission Cooldown="0">jail.immune</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>

                                            Thank You, Please Try To Help Me.. XOXO

**Comment by Trojaner25** [comment]
Line 196 is broken
