### ISSUE TITLE
Update coming?

### ISSUE THREAD

**Issue by Wilgelmy** [RocketMod/Rocket#970]
**What problem did you noticed?** There is no new Rocketmod Version for the new Unturned Version 3.20.4.0

**What is the expected result?** Hopefully an Update of Rocketmod

**What is the current result?** I can´t install Rocketmod on an Nitrado Server

**How to reproduce the issue?** I put to Rocketmod data in the right folder and restart the server but nothing happens

Operating System and Version: Windows 10  Pro

Unturned Version: 3.20.4.0

Rocketmod Version: 3.20.3.0
--

**Comment by persiafighter** [comment]
1) Rocket doesn't require updating anymore when unturned updates.
2) I'm pretty sure the tutorial you followed to install rocket is outdated.
3) That's not rocketmod's version.
4) Contact Nitrado's support to install rocket if you are not able to.
