### ISSUE TITLE
Cannot connect to server, server encounters issue.

### ISSUE THREAD

**Issue by CharlieIzCookiez** [RocketMod/Rocket#971]
**What problem did you noticed?**
The server encountered this:
ArgumentOutOfRangeException: < 0
Parameter name: count - System.IO.FileStream.Read (System.Byte[] array, Int32 offset, Int32 count)
SDG.Unturned.River.readString ()
SDG.Unturned.GroupManager.load ()
SDG.Unturned.GroupManager.onLevelLoaded (Int32 level)
SDG.Unturned.Level+<init>c__Iterator0.MoveNext ()
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress)

**What is the expected result?**
To join the server, but it did not complete a connection to the server.

**What is the current result?**
The same issue said in the first question.

**How to reproduce the issue?**
Relaunch the server.

Operating System and Version: Windows 10, 

Unturned Version: 3.20.5.0

Rocketmod Version: V4.9.3.0

**Comment by persiafighter** [comment]
Groups.dat is corrupted. Delete it.
Close this issue as well, it's not a rocket issue.
