### ISSUE TITLE
Vehicle Spawn Command Error

### ISSUE THREAD

**Issue by emre24807** [RocketMod/Rocket#972]
The "/v 830" (Spawn War Machine) command gives an error. There is no message appearing for player. But a ghost warmachine spawns. Players cannot see or use it. But zombies or players cannot enter the area that warmachine should be spawned.

Operating System: Windows
Unturned Version: 3.20.6.0
Rocketmod Version: Rocket Unturned v4.9.3.0 for Unturned v3.20.6.0

Error Log: https://hastebin.com/eqerodukif.css

**Comment by xdlewisdx** [comment]
investigating.

**Comment by Trojaner25** [comment]
Seems like an unturned bug

**Comment by xdlewisdx** [comment]
@Trojaner25 Indeed but the Vanilla /vehicle command works and that is using VehicleTool

**Comment by cartman-2000** [comment]
The /v command in rocket is also using the VehicleTool class, if you looked at the trace.

https://github.com/RocketMod/Rocket.Unturned/blob/e609b86966f30fd6bf8418e67ded6567cdd5f402/Rocket.Unturned/Commands/CommandV.cs#L86

**Comment by xdlewisdx** [comment]
Vanilla command /vehicle works on singleplayer... So its gotta be some networking problem or something?

**Comment by xdlewisdx** [comment]
Bug has been fixed and will be released next Unturned update, closed
