### ISSUE TITLE
Hi, I'm encountering the below error when adding my map in unturned, someone could help me solve it?  (no plugins)

### ISSUE THREAD

**Issue by xXLostGameXx** [RocketMod/Rocket#978]
**_NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.LevelSavedata.fileExists (System.String path)
SDG.Unturned.GroupManager.load ()
SDG.Unturned.GroupManager.onLevelLoaded (Int32 level)
SDG.Unturned.Level.onSceneLoaded (Scene scene, LoadSceneMode mode)
UnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (Scene scene, LoadSceneMode mode)_**

**Comment by xdlewisdx** [comment]
Does not follow template.

**Comment by xXLostGameXx** [comment]
as well?

**Comment by xXLostGameXx** [comment]
How do I solve it?

**Comment by xdlewisdx** [comment]
Does not follow issue template, please close it

**Comment by xXLostGameXx** [comment]
But I need help, can you help me?

**Comment by xdlewisdx** [comment]
Are you even reading what i am saying, no you didn't even follow the issue template

**Comment by persiafighter** [comment]
Does not follow issue template provided when creating an issue.
Also, your fix is to delete groups.dat. Issue and solution have already been posted at https://github.com/RocketMod/Rocket/issues/971
Just like there, I request a close as well as this not being a rocket issue.

**Comment by Trojaner25** [comment]
Does not follow template, beside that this is an Unturned error
