### ISSUE TITLE
Unturned hosting server issue 3.20.9.1

### ISSUE THREAD

**Issue by FatalityPig** [RocketMod/Rocket#979]
i am running into an issue when i try to start up my unturned server (just a LAN one hosted through evolve and such) 
yesterday en the 2 days before that i had not a single problem hosting the server but i also forgot to save the game in all those instances yesterday however i did save the server and now i have this error :
ArgumentOutOfRangeException: < 0
Parameter name: count - System.IO.FileStream.Read (System.Byte[] array, Int32 offset, Int32 count)
SDG.Unturned.River.readString ()
SDG.Unturned.GroupManager.load ()
SDG.Unturned.GroupManager.onLevelLoaded (Int32 level)
SDG.Unturned.Level+<init>c__Iterator0.MoveNext ()
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress)

i personally do not understand this error and therefore am asking for some help out here.

**Comment by persiafighter** [comment]
Doesn't follow issue template.
It is also not a rocketmod issue and has been mentioned https://github.com/RocketMod/Rocket/issues/978 and https://github.com/RocketMod/Rocket/issues/971.
Solution is described there and it is to delete groups.dat.
Requesting again this issue to be closed.
