### ISSUE TITLE
USO rocket editor wont open

### ISSUE THREAD

**Issue by meowz2muchYT** [RocketMod/Rocket#980]
hi guys i need help my rocket editor wont open in uso and i cant install more mods from the web because it just crashes (btw im using unturned 3.21.1.0 the latest version) pls help me and i dont know how the glitch started.

**Comment by persiafighter** [comment]
Not a Rocketmod issue and doesn't follow the issue template. Requesting close. Bug was also fixed by USO about a week ago.
