### ISSUE TITLE
Rocket not loading on console

### ISSUE THREAD

**Issue by masterfranky** [RocketMod/Rocket#982]
**What problem did you noticed?**
after configuring permissions in the rocket permissions file. The plugin rocket no longer loads in the console. I added things to permissions folder and at first everything was working fine. then all of a sudden rocket no longer runs. Unable to find any resolutions searching online. all plugins are in the designated folders.
As i said things wee actually working at one point then just stopped

**What is the current result?**
not loading in console

**How to reproduce the issue?**
don't know, i've taken some of the permissions out I last added such as RP 911 and rocketJobs permissions. still not loading rocket. Attempted reloadnig plugins and no result.

**Operating System and Version:**
windows 10

**Unturned Version:**
3.21.2.0

**Rocketmod Version:**
4.9.3.0 build 1280

------

i have no logs because again rocket wont even load on console
are there plugins that conflict with each other?

**Comment by xdlewisdx** [comment]
Not a RocketMod issue most likely have a malformed config or perms file, join the discord to talk more. close
