### ISSUE TITLE
Error opening a server with ubuntu 16.04

### ISSUE THREAD

**Issue by educatalan02** [RocketMod/Rocket#983]
Error while compiling generated serializer
/tmp/2314fa66/7bb4656e.cs(27,36) : error CS0012: The type `Rocket.API.IDefaultable' is defined in an assembly that is not referenced. Consider adding a reference to assembly `Rocket.API, Version=2.6.4.0, Culture=neutral, PublicKeyToken=null'
(0,0) : error : /root/Unturned/Modules/Rocket.Unturned/Rocket.Core.dll (Location of the symbol related to previous error)

**Comment by Trojaner25** [comment]
This error is not a real error.
You can ignore it, it doesnt do anything
