### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by Ankeraout** [RocketMod/Rocket#986]
**What problem did you noticed?**
When I was developing a plugin, I realized that Visual Studio 2017 is not showing any documentation of any kind on methods and classes of the API.

**What is the expected result?**
I was expecting to see some description of the behaviour of each function, as it is done in .NET Framework.

**What is the current result?**
There is actually no information about what any method does, as there is no XML documentation in the source code.

**How to reproduce the issue?**
- Develop a plugin
- No documentation during development

Operating System and Version: Windows 10 x64 professional edition with VS2017 community edition

Unturned Version: 3.23.0.0

Rocketmod Version: 4.9.3.0

The information in the wiki also seems to be outdated, as I remember that developing a plugin with a single command class does not work as Rocket expects the plugin to have a RocketPlugin class.

**Comment by Ogyvan** [comment]
No documentation 30.01 1 month later

**Comment by Trojaner25** [comment]
Its unlikely and documentation will get added for master branch of RocketMod

**Comment by fr34kyn01535** [comment]
And then there is nobody contributing to documentation. We have alot of plugins GPL'd to learn from it though.

**Comment by Ogyvan** [comment]
Why the rocket rust has all the necessary documents, and You don't have it? it's so hard to add? If added to the documentation.

**Comment by Trojaner25** [comment]
@Ogyvan why dont you add them yourself if its that easy?
Dont forget that this is an open source project made by people who do it on their free time. You can not expect anything from us.

**Comment by Ogyvan** [comment]
Maybe because I'm not designing your rocket and do not know how to manage your suppliers? Sooner was the documentation, at the moment it is not present

**Comment by Trojaner25** [comment]
This is getting ridiculous.
As said this is a project of volunteers, you can not expect anything.

Closing.

**Comment by Trojaner25** [comment]
Nevermind,
I will not close the issue as its a legitimate feature request, but no discussions anymore.

**Comment by fr34kyn01535** [comment]
The rework deserves a nice documentation, shouldn't worry about it too mutch at this point.

**Comment by fr34kyn01535** [comment]
#1007
