### ISSUE TITLE
I have no perms as a owner

### ISSUE THREAD

**Issue by Ravi69** [RocketMod/Rocket#987]
Hi, No commands are working on my server, how can i fix that, plugins i use: Regions, airdropmanager, duty, JoinLeaveMessanges, kits, simpledeathmessanges, wreckingball, uessentials, zaupfeast and jobs

I use RocketMod.permissions.config,yml to perms. can someone help me maiking all the perms

**Comment by ChubbyQuokka** [comment]
Make sure you /admin yourself from the console, and please you the RocketMod discord instead of posting an issue on GitHub
