### ISSUE TITLE
When anybody sprints I get a bunch of errors

### ISSUE THREAD

**Issue by narnia1425** [RocketMod/Rocket#988]
When people run in the console I get a huge string of errors and somewhere in there says Method Not Found: 'SDG.Unturned.InteractableVehicle.kickplayer'
![12345](https://user-images.githubusercontent.com/25965884/35252037-78871d70-ffac-11e7-8307-101da6779ca7.png)

There shouldn't be any errors when anyone runs

Operating System and Version:
I'm using windows 10 Home edition 
Unturned Version:
3.23.4.1
Rocketmod Version:
v4.9.3.0

**Comment by Trojaner25** [comment]
Plugin bug; not Rocket related.
