### ISSUE TITLE
Rocket updater not working

### ISSUE THREAD

**Issue by mreasyy** [RocketMod/Rocket#994]
**What problem did you noticed?**
- linux server wont update rocket / unturned because of permission denied 
**What is the expected result?**
for rocket and unturned to update
**What is the current result?**

Archive:  rocket.zip
  inflating: RocketLauncher.exe
  inflating: Modules/Rocket.Unturned/English.dat
  inflating: Modules/Rocket.Unturned/Rocket.Core.dll
  inflating: Modules/Rocket.Unturned/Rocket.API.dll
  inflating: Modules/Rocket.Unturned/Rocket.Unturned.dll
  inflating: Modules/Rocket.Unturned/Rocket.LICENSE
 extracting: Modules/Rocket.Unturned/Icon.png
  inflating: Modules/Rocket.Unturned/README
  inflating: Modules/Rocket.Unturned/Rocket.Unturned.module
  inflating: Modules/Rocket.Unturned/Rocket.Unturned.LICENSE
  inflating: Scripts/README
  inflating: Scripts/start.sh
  inflating: Scripts/update.sh
mkdir: cannot create directory ‘/home/unturnedadmin/Scripts/../../steamcmd’: Permission denied
./update.sh: line 15: cd: /home/unturnedadmin/Scripts/../../steamcmd: No such file or directory
Redirecting stderr to '/home/unturnedadmin/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

**How to reproduce the issue?**
no clue fam

Operating System and Version:
 - Ubuntu 14.04 LTS
Unturned Version:
- 3.23.4.2
Rocketmod Version:
Latest

**Comment by ChubbyQuokka** [comment]
Run the updater with the **sudo** command.

**Comment by mreasyy** [comment]
@ChubbyQuokka thanks it worked, can close this now.
