### ISSUE TITLE
Server wont start 

### ISSUE THREAD

**Issue by mreasyy** [RocketMod/Rocket#995]
**What problem did you noticed?**
server will not start
**What is the expected result?**
server to start 
**What is the current result?**

General: Quit due to provider exception: GameServer API initialization failed!
[registered] /admins (Rocket.Unturned.Commands.UnturnedCommands/admins)
[registered] /animal (Rocket.Unturned.Commands.UnturnedCommands/animal)
[registered] /ban (Rocket.Unturned.Commands.UnturnedCommands/ban)
[registered] /bans (Rocket.Unturned.Commands.UnturnedCommands/bans)
[registered] /bind (Rocket.Unturned.Commands.UnturnedCommands/bind)
[registered] /chatrate (Rocket.Unturned.Commands.UnturnedCommands/chatrate)
[registered] /cheats (Rocket.Unturned.Commands.UnturnedCommands/cheats)
[registered] /cycle (Rocket.Unturned.Commands.UnturnedCommands/cycle)
[registered] /day (Rocket.Unturned.Commands.UnturnedCommands/day)
[registered] /debug (Rocket.Unturned.Commands.UnturnedCommands/debug)
[registered] /experience (Rocket.Unturned.Commands.UnturnedCommands/experience)
[registered] /filter (Rocket.Unturned.Commands.UnturnedCommands/filter)
[registered] /flag (Rocket.Unturned.Commands.UnturnedCommands/flag)
[registered] /gamemode (Rocket.Unturned.Commands.UnturnedCommands/gamemode)
[registered] /give (Rocket.Unturned.Commands.UnturnedCommands/give)
[registered] /gold (Rocket.Unturned.Commands.UnturnedCommands/gold)
[registered] /hide_admins (Rocket.Unturned.Commands.UnturnedCommands/hide_admins)
[registered] /kick (Rocket.Unturned.Commands.UnturnedCommands/kick)
[registered] /kill (Rocket.Unturned.Commands.UnturnedCommands/kill)
[registered] /loadout (Rocket.Unturned.Commands.UnturnedCommands/loadout)
[registered] /log (Rocket.Unturned.Commands.UnturnedCommands/log)
[registered] /map (Rocket.Unturned.Commands.UnturnedCommands/map)
[registered] /maxplayers (Rocket.Unturned.Commands.UnturnedCommands/maxplayers)
[registered] /mode (Rocket.Unturned.Commands.UnturnedCommands/mode)
[registered] /modules (Rocket.Unturned.Commands.UnturnedCommands/modules)
[registered] /name (Rocket.Unturned.Commands.UnturnedCommands/name)
[registered] /night (Rocket.Unturned.Commands.UnturnedCommands/night)
[registered] /owner (Rocket.Unturned.Commands.UnturnedCommands/owner)
[registered] /password (Rocket.Unturned.Commands.UnturnedCommands/password)
[registered] /permit (Rocket.Unturned.Commands.UnturnedCommands/permit)
[registered] /permits (Rocket.Unturned.Commands.UnturnedCommands/permits)
[registered] /perspective (Rocket.Unturned.Commands.UnturnedCommands/perspective)
[registered] /players (Rocket.Unturned.Commands.UnturnedCommands/players)
[registered] /port (Rocket.Unturned.Commands.UnturnedCommands/port)
[registered] /pve (Rocket.Unturned.Commands.UnturnedCommands/pve)
[registered] /quest (Rocket.Unturned.Commands.UnturnedCommands/quest)
[registered] /queue_size (Rocket.Unturned.Commands.UnturnedCommands/queue_size)
[registered] /reputation (Rocket.Unturned.Commands.UnturnedCommands/reputation)
[registered] /resetconfig (Rocket.Unturned.Commands.UnturnedCommands/resetconfig)
[registered] /save (Rocket.Unturned.Commands.UnturnedCommands/save)
[registered] /say (Rocket.Unturned.Commands.UnturnedCommands/say)
[registered] /shutdown (Rocket.Unturned.Commands.UnturnedCommands/shutdown)
[registered] /slay (Rocket.Unturned.Commands.UnturnedCommands/slay)
[registered] /spy (Rocket.Unturned.Commands.UnturnedCommands/spy)
[registered] /sync (Rocket.Unturned.Commands.UnturnedCommands/sync)
[registered] /teleport (Rocket.Unturned.Commands.UnturnedCommands/teleport)
[registered] /time (Rocket.Unturned.Commands.UnturnedCommands/time)
[registered] /timeout (Rocket.Unturned.Commands.UnturnedCommands/timeout)
[registered] /unban (Rocket.Unturned.Commands.UnturnedCommands/unban)
[registered] /unpermit (Rocket.Unturned.Commands.UnturnedCommands/unpermit)
[registered] /vehicle (Rocket.Unturned.Commands.UnturnedCommands/vehicle)
[registered] /votify (Rocket.Unturned.Commands.UnturnedCommands/votify)
[registered] /weather (Rocket.Unturned.Commands.UnturnedCommands/weather)
[registered] /welcome (Rocket.Unturned.Commands.UnturnedCommands/welcome)
[registered] /whitelisted (Rocket.Unturned.Commands.UnturnedCommands/whitelisted)
[registered] /more (Rocket.Unturned.Commands.CommandMore/more)
[registered] /admin (Rocket.Unturned.Commands.CommandAdmin/admin)
[registered] /broadcast (Rocket.Unturned.Commands.CommandBroadcast/broadcast)
[registered] /compass (Rocket.Unturned.Commands.CommandCompass/compass)
[registered] /effect (Rocket.Unturned.Commands.CommandEffect/effect)
[registered] /exit (Rocket.Unturned.Commands.CommandExit/exit)
[registered] /heal (Rocket.Unturned.Commands.CommandHeal/heal)
[registered] /help (Rocket.Unturned.Commands.CommandHelp/help)
[registered] /home (Rocket.Unturned.Commands.CommandHome/home)
[registered] /i (Rocket.Unturned.Commands.CommandI/i)
[registered] /item (Rocket.Unturned.Commands.CommandI/item)
[registered] /p (Rocket.Unturned.Commands.CommandP/p)
[registered] /permissions (Rocket.Unturned.Commands.CommandP/permissions)
[registered] /rocket (Rocket.Unturned.Commands.CommandRocket/rocket)
[registered] /tp (Rocket.Unturned.Commands.CommandTp/tp)
[registered] /tphere (Rocket.Unturned.Commands.CommandTphere/tphere)
[registered] /unadmin (Rocket.Unturned.Commands.CommandUnadmin/unadmin)
[registered] /v (Rocket.Unturned.Commands.CommandV/v)
Steam can not be initialized: Steamworks GameServer is not initialized.
System.SystemException: Error running gmcs: Cannot find the specified file
  at Mono.CSharp.CSharpCodeCompiler.CompileFromFileBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames) [0x00000] in <filename unknown>:0 
  at Mono.CSharp.CSharpCodeCompiler.CompileAssemblyFromFileBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames) [0x00000] in <filename unknown>:0 
  at Mono.CSharp.CSharpCodeCompiler.CompileAssemblyFromFile (System.CodeDom.Compiler.CompilerParameters options, System.String fileName) [0x00000] in <filename unknown>:0 
  at System.Xml.Serialization.XmlSerializer.GenerateSerializers (System.Xml.Serialization.GenerationBatch batch, System.CodeDom.Compiler.CompilerParameters cp) [0x00000] in <filename unknown>:0 
  at System.Xml.Serialization.XmlSerializer.RunSerializerGeneration (System.Object obj) [0x00000] in <filename unknown>:0 

**How to reproduce the issue?**
no clue 

Operating System and Version:
Ubunti 14.04

Rocketmod Version:
Latest

**Comment by ChubbyQuokka** [comment]
This is an Unturned issue: https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/172

Requesting close.
