### ISSUE TITLE
Unturned with Rocket crashing every hour or so

### ISSUE THREAD

**Issue by diamondpumpkin** [RocketMod/Rocket#998]
Upon updating from Ubuntu 15.04 to 16.04.2 I have noticed my servers will crash every hour or so depending on the server load (More players, quicker it crashes).
I am running a dedicated server with an Intel Xeon E3-1230v2 @3.5GHz (4Cores/8Threads) with 32GB DDR3 RAM and a 512GB SSD.
I have installed all of the pre-requisites as stated [here](https://github.com/RocketMod/Rocket.Unturned/tree/master/Rocket.Unturned/Scripts/Linux), even with the packages the servers are unable to stay up consistently.
I also had to use the Linux workaround for Unturned servers as stated [here](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/172#issuecomment-359150349), but had no change on the server's stability.
I have contacted some friends who claim to also have the same issue on Ubuntu 16.04.X.

Logs:
[Unturned.1.txt](https://github.com/RocketMod/Rocket/files/1704997/Unturned.1.txt)
[Rocket.1.txt](https://github.com/RocketMod/Rocket/files/1704999/Rocket.1.txt)

Crash report I obtained from console.
[crashreport.txt](https://github.com/RocketMod/Rocket/files/1705005/crashreport.txt)

Versions:
Rocket: v4.9.3.0 
Unturned: v3.23.4.2

**Comment by FunkyOfficial** [comment]
./serverstarter.sh: **line 39**: 14900 **Aborted** mono RocketLauncher.exe $INSTANCE_NAME

  Might be a issue with mono, mono is very unstable in **Linux**. Have you checked if there's an **update** for it on your **distro**?

**Comment by diamondpumpkin** [comment]
Yeah, there's a few mono programs that will crash the server upon start up. The ones required are at the latest version.

**Comment by Trojaner25** [comment]
> Might be a issue with mono, **mono is very unstable in Linux**

???

**Comment by diamondpumpkin** [comment]
Sigh, this is disappointing. I figured out how to downgrade and it turns out mono version 4.2.1.102 is only version available on Ubuntu 16.04.2. Support seriously need to be added.

Available versions:
```
root@s114323:/home/main# apt-cache policy mono-runtime
mono-runtime:
  Installed: 4.2.1.102+dfsg2-7ubuntu4
  Candidate: 4.2.1.102+dfsg2-7ubuntu4
  Version table:
 *** 4.2.1.102+dfsg2-7ubuntu4 500
        500 http://mirror.cogentco.com/pub/linux/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by Trojaner25** [comment]
Since the error is in native code, this isn't easy fixable, nor does this happen in Rockets or Unturneds code.
Its like that either Steam or Unity causes the crash.

**Comment by diamondpumpkin** [comment]
Would have no idea, vanilla doesn't start for me. Never has, not even on 15.04.

I run

`./Unturned_Headless.x86 -nographics -batchmode +secureserver/test`

Loads and gives the GameAPI failed to initialize. Even with the Linux

**Comment by fr34kyn01535** [comment]
Wontfix. Not enought information, will likely to need somebody to debug mono for unity on linux.
